[package]
name = "tsrs_checker"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
tsrs_core.workspace = true
tsrs_diagnostics.workspace = true
tsrs_ast.workspace = true
tsrs_scanner.workspace = true
tsrs_parser.workspace = true
tsrs_binder.workspace = true
tsrs_module.workspace = true
tsrs_pseudochecker.workspace = true
tsrs_modulespecifiers.workspace = true
tsrs_printer.workspace = true
rustc-hash.workspace = true
indexmap.workspace = true
bitflags.workspace = true
xxhash-rust = { version = "0.8", features = ["xxh3", "const_xxh3"] }
