[package]
name = "tsrs_modulespecifiers"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
tsrs_core.workspace = true
tsrs_ast.workspace = true
tsrs_module.workspace = true
tsrs_tsoptions.workspace = true
rustc-hash.workspace = true
regex-automata = { version = "0.4", default-features = false, features = ["std", "syntax", "nfa-pikevm", "unicode"] }
regex-syntax = "0.8"

[dev-dependencies]
regex = "1"
