[package]
name = "tsrs_testrunner"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[features]
default = []

[dependencies]
tsrs_core.workspace = true
tsrs_diagnostics.workspace = true
rustc-hash.workspace = true
regex = "1"
serde_json = "1"
similar = "2"

[[bin]]
name = "tsrs-test"
path = "src/main.rs"
