use crate::*;
use tsrs_ast::*;
use tsrs_core::*;
use tsrs_ast as ast;
use tsrs_diagnostics as diagnostics;
use tsrs_diagnostics::Message;
use rustc_hash::FxHashMap;
use std::fmt::Display;

// Stubs generated by tools/gosig. Keep the signatures; replace the todo!() bodies.

// Non-function declarations in checker.go:30510-end (hand-ported by checker-foundation):
//   type ObjectLiteralDiscriminator (checker.go:31202)

impl Checker {
    // checker.go:30511
    pub(crate) fn get_contextual_type_for_conditional_operand(&mut self, node: P<Node>, context_flags: ContextFlags) -> Option<P<Type>> {
        todo!()
    }

    // checker.go:30519
    pub(crate) fn get_contextual_type_for_substitution_expression(&mut self, template: P<Node>, substitution_expression: P<Node>) -> Option<P<Type>> {
        todo!()
    }

    // checker.go:30526
    pub(crate) fn get_contextual_import_attribute_type(&mut self, node: P<Node>) -> Option<P<Type>> {
        todo!()
    }

    // checker.go:30531
    pub(crate) fn get_effective_call_arguments(&mut self, node: P<Node>) -> Vec<P<Node>> {
        todo!()
    }

    // checker.go:30597
    pub(crate) fn get_spread_argument_index(&mut self, args: &[P<Node>]) -> i32 {
        todo!()
    }
}

// checker.go:30601
pub(crate) fn is_spread_argument(arg: P<Node>) -> bool {
    todo!()
}

impl Checker {
    // checker.go:30605
    pub(crate) fn create_synthetic_expression(&mut self, parent: P<Node>, t: P<Type>, is_spread: bool, tuple_name_source: Option<P<Node>>) -> P<Node> {
        todo!()
    }

    // checker.go:30612
    pub(crate) fn get_spread_indices(&mut self, node: P<Node>) -> (i32, i32) {
        todo!()
    }

    // checker.go:30631
    pub(crate) fn get_effective_decorator_arguments(&mut self, node: P<Node>) -> Vec<P<Node>> {
        todo!()
    }

    // checker.go:30644
    pub(crate) fn get_decorator_call_signature(&mut self, decorator: P<Node>) -> Option<P<Signature>> {
        todo!()
    }

    // checker.go:30651
    pub(crate) fn get_legacy_decorator_call_signature(&mut self, decorator: P<Node>) -> Option<P<Signature>> {
        todo!()
    }

    // checker.go:30718
    pub(crate) fn get_es_decorator_call_signature(&mut self, decorator: P<Node>) -> Option<P<Signature>> {
        todo!()
    }

    // checker.go:30896
    pub(crate) fn new_class_decorator_context_type(&mut self, class_type: P<Type>) -> P<Type> {
        todo!()
    }

    // checker.go:30900
    pub(crate) fn new_class_method_decorator_context_type(&mut self, class_type: P<Type>, value_type: P<Type>) -> P<Type> {
        todo!()
    }

    // checker.go:30904
    pub(crate) fn new_class_getter_decorator_context_type(&mut self, class_type: P<Type>, value_type: P<Type>) -> P<Type> {
        todo!()
    }

    // checker.go:30908
    pub(crate) fn new_class_setter_decorator_context_type(&mut self, class_type: P<Type>, value_type: P<Type>) -> P<Type> {
        todo!()
    }

    // checker.go:30912
    pub(crate) fn new_class_accessor_decorator_context_type(&mut self, this_type: P<Type>, value_type: P<Type>) -> P<Type> {
        todo!()
    }

    // checker.go:30916
    pub(crate) fn new_class_field_decorator_context_type(&mut self, this_type: P<Type>, value_type: P<Type>) -> P<Type> {
        todo!()
    }

    // checker.go:30922
    pub(crate) fn get_class_member_decorator_context_override_type(&mut self, name_type: P<Type>, is_private: bool, is_static: bool) -> P<Type> {
        todo!()
    }

    // checker.go:30941
    pub(crate) fn new_class_member_decorator_context_type_for_node(&mut self, node: P<Node>, this_type: P<Type>, value_type: P<Type>) -> P<Type> {
        todo!()
    }

    // checker.go:30969
    pub(crate) fn new_class_accessor_decorator_target_type(&mut self, this_type: P<Type>, value_type: P<Type>) -> P<Type> {
        todo!()
    }

    // checker.go:30973
    pub(crate) fn new_class_accessor_decorator_result_type(&mut self, this_type: P<Type>, value_type: P<Type>) -> P<Type> {
        todo!()
    }

    // checker.go:30977
    pub(crate) fn new_class_field_decorator_initializer_mutator_type(&mut self, this_type: P<Type>, value_type: P<Type>) -> P<Type> {
        todo!()
    }

    // checker.go:30985
    pub(crate) fn new_es_decorator_call_signature(&mut self, target_type: P<Type>, context_type: P<Type>, non_optional_return_type: P<Type>) -> P<Signature> {
        todo!()
    }

    // checker.go:30993
    pub(crate) fn new_function_type(&mut self, type_parameters: &[P<Type>], this_parameter: Option<P<Symbol>>, parameters: &[P<Symbol>], return_type: P<Type>) -> P<Type> {
        todo!()
    }

    // checker.go:30998
    pub(crate) fn new_getter_function_type(&mut self, t: P<Type>) -> P<Type> {
        todo!()
    }

    // checker.go:31002
    pub(crate) fn new_setter_function_type(&mut self, t: P<Type>) -> P<Type> {
        todo!()
    }

    // checker.go:31008
    pub(crate) fn new_call_signature(&mut self, type_parameters: &[P<Type>], this_parameter: Option<P<Symbol>>, parameters: &[P<Symbol>], return_type: P<Type>) -> P<Signature> {
        todo!()
    }

    // checker.go:31013
    pub(crate) fn new_typed_property_descriptor_type(&mut self, property_type: P<Type>) -> P<Type> {
        todo!()
    }

    // checker.go:31017
    pub(crate) fn get_parent_type_of_class_element(&mut self, node: P<Node>) -> P<Type> {
        todo!()
    }

    // checker.go:31025
    pub(crate) fn get_class_element_property_key_type(&mut self, element: P<Node>) -> P<Type> {
        todo!()
    }

    // checker.go:31040
    pub fn get_type_of_property_of_contextual_type(&mut self, t: P<Type>, name: &str) -> Option<P<Type>> {
        todo!()
    }

    // checker.go:31044
    pub(crate) fn get_type_of_property_of_contextual_type_ex(&mut self, t: P<Type>, name: &str, name_type: Option<P<Type>>) -> Option<P<Type>> {
        todo!()
    }

    // checker.go:31096
    pub(crate) fn get_indexed_mapped_type_substituted_type_of_contextual_type(&mut self, t: P<Type>, name: &str, name_type: Option<P<Type>>) -> Option<P<Type>> {
        todo!()
    }

    // checker.go:31113
    pub(crate) fn is_excluded_mapped_property_name(&mut self, t: P<Type>, property_name_type: P<Type>) -> bool {
        todo!()
    }

    // checker.go:31127
    pub(crate) fn get_type_of_concrete_property_of_contextual_type(&mut self, t: P<Type>, name: &str) -> Option<P<Type>> {
        todo!()
    }

    // checker.go:31135
    pub(crate) fn get_type_from_index_infos_of_contextual_type(&mut self, t: P<Type>, name: &str, name_type: Option<P<Type>>) -> Option<P<Type>> {
        todo!()
    }

    // checker.go:31152
    pub(crate) fn is_circular_mapped_property(&mut self, symbol: P<Symbol>) -> bool {
        todo!()
    }

    // checker.go:31160
    pub(crate) fn append_contextual_property_type_constituent(&mut self, types: &[P<Type>], t: Option<P<Type>>) -> Vec<P<Type>> {
        todo!()
    }

    // checker.go:31175
    pub(crate) fn get_apparent_type_of_contextual_type(&mut self, node: P<Node>, context_flags: ContextFlags) -> Option<P<Type>> {
        todo!()
    }
}

impl ObjectLiteralDiscriminator {
    // checker.go:31208
    pub(crate) fn len(&mut self, c: &mut Checker) -> i32 {
        todo!()
    }

    // checker.go:31212
    pub(crate) fn name(&mut self, c: &mut Checker, index: i32) -> String {
        todo!()
    }

    // checker.go:31219
    pub(crate) fn matches(&mut self, c: &mut Checker, index: i32, t: P<Type>) -> bool {
        todo!()
    }
}

impl Checker {
    // checker.go:31244
    pub(crate) fn discriminate_contextual_type_by_object_members(&mut self, node: P<Node>, contextual_type: P<Type>) -> P<Type> {
        todo!()
    }

    // checker.go:31274
    pub(crate) fn get_matching_union_constituent_for_object_literal(&mut self, union_type: P<Type>, node: P<Node>) -> Option<P<Type>> {
        todo!()
    }

    // checker.go:31291
    pub(crate) fn is_possibly_discriminant_value(&mut self, node: P<Node>) -> bool {
        todo!()
    }

    // checker.go:31306
    pub(crate) fn instantiate_contextual_type(&mut self, contextual_type: P<Type>, node: P<Node>, context_flags: ContextFlags) -> P<Type> {
        todo!()
    }

    // checker.go:31344
    pub(crate) fn instantiate_instantiable_types(&mut self, t: P<Type>, mapper: P<TypeMapper>) -> P<Type> {
        todo!()
    }

    // checker.go:31361
    pub(crate) fn push_cached_contextual_type(&mut self, node: P<Node>) {
        todo!()
    }

    // checker.go:31365
    pub(crate) fn push_contextual_type(&mut self, node: P<Node>, t: P<Type>, is_cache: bool) {
        todo!()
    }

    // checker.go:31369
    pub(crate) fn pop_contextual_type(&mut self) {
        todo!()
    }

    // checker.go:31375
    pub(crate) fn find_contextual_node(&mut self, node: P<Node>, include_caches: bool) -> i32 {
        todo!()
    }

    // checker.go:31386
    pub fn is_context_sensitive(&mut self, node: P<Node>) -> bool {
        todo!()
    }

    // checker.go:31420
    pub(crate) fn is_context_sensitive_function_like_declaration(&mut self, node: P<Node>) -> bool {
        todo!()
    }

    // checker.go:31424
    pub(crate) fn has_context_sensitive_return_expression(&mut self, node: P<Node>) -> bool {
        todo!()
    }

    // checker.go:31440
    pub(crate) fn has_context_sensitive_yield_expression(&mut self, node: P<Node>) -> bool {
        todo!()
    }

    // checker.go:31444
    pub(crate) fn push_inference_context(&mut self, node: P<Node>, context: Option<P<InferenceContext>>) {
        todo!()
    }

    // checker.go:31448
    pub(crate) fn pop_inference_context(&mut self) {
        todo!()
    }

    // checker.go:31454
    pub(crate) fn get_inference_context(&mut self, node: P<Node>) -> Option<P<InferenceContext>> {
        todo!()
    }

    // checker.go:31463
    pub(crate) fn get_type_facts(&mut self, t: P<Type>, mask: TypeFacts) -> TypeFacts {
        todo!()
    }

    // checker.go:31467
    pub(crate) fn has_type_facts(&mut self, t: P<Type>, mask: TypeFacts) -> bool {
        todo!()
    }

    // checker.go:31471
    pub(crate) fn get_type_facts_worker(&mut self, t: P<Type>, caller_only_needs: TypeFacts) -> TypeFacts {
        todo!()
    }

    // checker.go:31607
    pub(crate) fn get_intersection_type_facts(&mut self, t: P<Type>, caller_only_needs: TypeFacts) -> TypeFacts {
        todo!()
    }
}

// checker.go:31625
pub(crate) fn is_zero_big_int(t: P<Type>) -> bool {
    todo!()
}

impl Checker {
    // checker.go:31629
    pub(crate) fn is_function_object_type(&mut self, t: P<Type>) -> bool {
        todo!()
    }

    // checker.go:31639
    pub(crate) fn get_type_with_facts(&mut self, t: P<Type>, include: TypeFacts) -> P<Type> {
        todo!()
    }

    // checker.go:31648
    pub(crate) fn get_adjusted_type_with_facts(&mut self, t: P<Type>, facts: TypeFacts) -> P<Type> {
        todo!()
    }

    // checker.go:31668
    pub(crate) fn remove_nullable_by_intersection(&mut self, t: P<Type>, target_facts: TypeFacts, other_facts: TypeFacts, other_includes_facts: TypeFacts, other_type: P<Type>) -> P<Type> {
        todo!()
    }

    // checker.go:31690
    pub(crate) fn recombine_unknown_type(&mut self, t: P<Type>) -> P<Type> {
        todo!()
    }

    // checker.go:31697
    pub(crate) fn get_global_non_nullable_type_instantiation(&mut self, t: P<Type>) -> P<Type> {
        todo!()
    }

    // checker.go:31705
    pub(crate) fn convert_auto_to_any(&mut self, t: P<Type>) -> P<Type> {
        todo!()
    }

    // checker.go:31721
    pub(crate) fn check_awaited_type(&mut self, t: P<Type>, with_alias: bool, error_node: P<Node>, diagnostic_message: &'static Message) -> P<Type> {
        todo!()
    }

    // checker.go:31742
    pub fn get_awaited_type(&mut self, t: P<Type>) -> Option<P<Type>> {
        todo!()
    }

    // checker.go:31746
    pub(crate) fn get_awaited_type_ex(&mut self, t: P<Type>, error_node: Option<P<Node>>, diagnostic_message: Option<&'static Message>, args: &[&dyn Display]) -> Option<P<Type>> {
        todo!()
    }

    // checker.go:31755
    pub(crate) fn get_awaited_type_no_alias(&mut self, t: P<Type>) -> Option<P<Type>> {
        todo!()
    }

    // checker.go:31759
    pub(crate) fn get_awaited_type_no_alias_ex(&mut self, t: P<Type>, error_node: Option<P<Node>>, diagnostic_message: Option<&'static Message>, args: &[&dyn Display]) -> Option<P<Type>> {
        todo!()
    }

    // checker.go:31873
    pub(crate) fn is_awaited_type_instantiation(&mut self, t: P<Type>) -> bool {
        todo!()
    }

    // checker.go:31881
    pub(crate) fn is_awaited_type_needed(&mut self, t: P<Type>) -> bool {
        todo!()
    }

    // checker.go:31899
    pub(crate) fn create_awaited_type_if_needed(&mut self, t: P<Type>) -> P<Type> {
        todo!()
    }

    // checker.go:31916
    pub(crate) fn try_create_awaited_type(&mut self, t: P<Type>) -> Option<P<Type>> {
        todo!()
    }

    // checker.go:31928
    pub(crate) fn unwrap_awaited_type(&mut self, t: P<Type>) -> P<Type> {
        todo!()
    }

    // checker.go:31938
    pub(crate) fn is_thenable_type(&mut self, t: P<Type>) -> bool {
        todo!()
    }

    // checker.go:31947
    pub(crate) fn get_awaited_type_of_promise(&mut self, t: P<Type>) -> Option<P<Type>> {
        todo!()
    }

    // checker.go:31951
    pub(crate) fn get_awaited_type_of_promise_ex(&mut self, t: P<Type>, error_node: Option<P<Node>>, diagnostic_message: Option<&'static Message>, args: &[&dyn Display]) -> Option<P<Type>> {
        todo!()
    }

    // checker.go:31960
    pub(crate) fn is_some_symbol_assigned(&mut self, root_declaration: P<Node>) -> bool {
        todo!()
    }

    // checker.go:31964
    pub(crate) fn is_some_symbol_assigned_worker(&mut self, node: P<Node>) -> bool {
        todo!()
    }

    // checker.go:31973
    pub(crate) fn get_target_type(&mut self, t: P<Type>) -> Option<P<Type>> {
        todo!()
    }

    // checker.go:31980
    pub(crate) fn get_narrowable_type_for_reference(&mut self, t: P<Type>, reference: P<Node>, check_mode: CheckMode) -> P<Type> {
        todo!()
    }

    // checker.go:31998
    pub(crate) fn is_constraint_position(&mut self, t: P<Type>, node: P<Node>) -> bool {
        todo!()
    }

    // checker.go:32008
    pub(crate) fn is_generic_type_with_union_constraint(&mut self, t: P<Type>) -> bool {
        todo!()
    }

    // checker.go:32015
    pub(crate) fn is_generic_type_without_nullable_constraint(&mut self, t: P<Type>) -> bool {
        todo!()
    }

    // checker.go:32022
    pub(crate) fn has_contextual_type_with_no_generic_types(&mut self, node: P<Node>, check_mode: CheckMode) -> bool {
        todo!()
    }

    // checker.go:32037
    pub(crate) fn get_non_undefined_type(&mut self, t: P<Type>) -> P<Type> {
        todo!()
    }

    // checker.go:32050
    pub(crate) fn is_generic_type_with_undefined_constraint(&mut self, t: P<Type>) -> bool {
        todo!()
    }

    // checker.go:32060
    pub(crate) fn get_actual_type_variable(&mut self, t: P<Type>) -> Option<P<Type>> {
        todo!()
    }

    // checker.go:32074
    pub fn get_symbol_at_location_exported(&mut self, node: P<Node>) -> Option<P<Symbol>> {
        todo!()
    }

    // checker.go:32087
    pub(crate) fn get_symbol_at_location(&mut self, node: P<Node>, ignore_errors: bool) -> Option<P<Symbol>> {
        todo!()
    }

    // checker.go:32257
    pub fn get_index_signatures_at_location(&mut self, node: P<Node>) -> Vec<P<Node>> {
        todo!()
    }

    // checker.go:32273
    pub(crate) fn get_symbol_of_name_or_property_access_expression(&mut self, name: P<Node>) -> Option<P<Symbol>> {
        todo!()
    }

    // checker.go:32408
    pub(crate) fn is_this_property_and_this_typed(&mut self, node: P<Node>) -> bool {
        todo!()
    }

    // checker.go:32423
    pub(crate) fn get_type_of_node(&mut self, node: P<Node>) -> P<Type> {
        todo!()
    }

    // checker.go:32535
    pub(crate) fn get_this_type_of_object_literal_from_contextual_type(&mut self, containing_literal: P<Node>, contextual_type: P<Type>) -> Option<P<Type>> {
        todo!()
    }

    // checker.go:32552
    pub(crate) fn get_this_type_from_contextual_type(&mut self, t: P<Type>) -> Option<P<Type>> {
        todo!()
    }

    // checker.go:32568
    pub(crate) fn get_this_type_argument(&mut self, t: P<Type>) -> Option<P<Type>> {
        todo!()
    }

    // checker.go:32575
    pub(crate) fn get_applicable_index_infos(&mut self, t: P<Type>, key_type: P<Type>) -> Vec<P<IndexInfo>> {
        todo!()
    }

    // checker.go:32579
    pub(crate) fn get_applicable_index_symbol(&mut self, t: P<Type>, key_type: P<Type>) -> Option<P<Symbol>> {
        todo!()
    }

    // checker.go:32608
    pub(crate) fn get_regular_type_of_expression(&mut self, expr: P<Node>) -> P<Type> {
        todo!()
    }

    // checker.go:32615
    pub(crate) fn contains_arguments_reference(&mut self, node: P<Node>) -> bool {
        todo!()
    }

    // checker.go:32652
    pub fn get_type_at_location(&mut self, node: P<Node>) -> P<Type> {
        todo!()
    }

    // checker.go:32656
    pub fn get_emit_resolver(&mut self) -> P<EmitResolver> {
        todo!()
    }

    // checker.go:32664
    pub fn get_aliased_symbol(&mut self, symbol: P<Symbol>) -> P<Symbol> {
        todo!()
    }
}
