use crate::*;
use tsrs_ast::*;
use tsrs_core::*;
use tsrs_ast as ast;
use tsrs_diagnostics as diagnostics;
use tsrs_diagnostics::Message;
use rustc_hash::FxHashMap;
use std::fmt::Display;

// Stubs generated by tools/gosig. Keep the signatures; replace the todo!() bodies.

impl Checker {
    // checker.go:10857
    pub(crate) fn get_instantiation_expression_type(&mut self, expr_type: P<Type>, node: P<Node>) -> P<Type> {
        todo!()
    }

    // checker.go:10941
    pub(crate) fn check_satisfies_expression(&mut self, node: P<Node>) -> P<Type> {
        todo!()
    }

    // checker.go:10953
    pub(crate) fn check_meta_property(&mut self, node: P<Node>) -> P<Type> {
        todo!()
    }

    // checker.go:10968
    pub(crate) fn check_new_target_meta_property(&mut self, node: P<Node>) -> P<Type> {
        todo!()
    }

    // checker.go:10982
    pub(crate) fn check_import_meta_property(&mut self, node: P<Node>) -> P<Type> {
        todo!()
    }

    // checker.go:10999
    pub(crate) fn check_meta_property_keyword(&mut self, node: P<Node>) -> P<Type> {
        todo!()
    }

    // checker.go:11004
    pub(crate) fn check_delete_expression(&mut self, node: P<Node>) -> P<Type> {
        todo!()
    }

    // checker.go:11025
    pub(crate) fn check_delete_expression_must_be_optional(&mut self, expr: P<Node>, symbol: P<Symbol>) {
        todo!()
    }

    // checker.go:11040
    pub(crate) fn check_void_expression(&mut self, node: P<Node>) -> P<Type> {
        todo!()
    }

    // checker.go:11045
    pub(crate) fn check_await_expression(&mut self, node: P<Node>) -> P<Type> {
        todo!()
    }

    // checker.go:11055
    pub(crate) fn check_prefix_unary_expression(&mut self, node: P<Node>) -> P<Type> {
        todo!()
    }

    // checker.go:11109
    pub(crate) fn check_postfix_unary_expression(&mut self, node: P<Node>) -> P<Type> {
        todo!()
    }

    // checker.go:11123
    pub(crate) fn get_unary_result_type(&mut self, operand_type: P<Type>) -> P<Type> {
        todo!()
    }

    // checker.go:11134
    pub(crate) fn check_conditional_expression(&mut self, node: P<Node>, check_mode: CheckMode) -> P<Type> {
        todo!()
    }

    // checker.go:11143
    pub(crate) fn check_truthiness_expression(&mut self, node: P<Node>, check_mode: CheckMode) -> P<Type> {
        todo!()
    }

    // checker.go:11147
    pub(crate) fn check_spread_expression(&mut self, node: P<Node>, check_mode: CheckMode) -> P<Type> {
        todo!()
    }

    // checker.go:11152
    pub(crate) fn check_yield_expression(&mut self, node: P<Node>) -> P<Type> {
        todo!()
    }

    // checker.go:11218
    pub(crate) fn get_yielded_type_of_yield_expression(&mut self, node: P<Node>, expression_type: P<Type>, sent_type: P<Type>, is_async: bool) -> Option<P<Type>> {
        todo!()
    }

    // checker.go:11234
    pub(crate) fn check_synthetic_expression(&mut self, node: P<Node>) -> P<Type> {
        todo!()
    }

    // checker.go:11242
    pub(crate) fn check_identifier(&mut self, node: P<Node>, check_mode: CheckMode) -> P<Type> {
        todo!()
    }

    // checker.go:11402
    pub(crate) fn is_same_scoped_binding_element(&mut self, node: P<Node>, declaration: P<Node>) -> bool {
        todo!()
    }

    // checker.go:11411
    pub(crate) fn remove_optionality_from_declared_type(&mut self, declared_type: P<Type>, declaration: P<Node>) -> P<Type> {
        todo!()
    }

    // checker.go:11419
    pub(crate) fn parameter_initializer_contains_undefined(&mut self, declaration: P<Node>) -> bool {
        todo!()
    }

    // checker.go:11438
    pub(crate) fn is_in_ambient_or_type_node(&mut self, node: P<Node>) -> bool {
        todo!()
    }

    // checker.go:11444
    pub(crate) fn check_property_access_expression(&mut self, node: P<Node>, check_mode: CheckMode, write_only: bool) -> P<Type> {
        todo!()
    }

    // checker.go:11452
    pub(crate) fn check_property_access_chain(&mut self, node: P<Node>, check_mode: CheckMode) -> P<Type> {
        todo!()
    }

    // checker.go:11458
    pub(crate) fn check_property_access_expression_or_qualified_name(&mut self, node: P<Node>, left: P<Node>, left_type: P<Type>, right: P<Node>, check_mode: CheckMode, write_only: bool) -> P<Type> {
        todo!()
    }

    // checker.go:11592
    pub(crate) fn get_flow_type_of_access_expression(&mut self, node: P<Node>, prop: Option<P<Symbol>>, prop_type: P<Type>, error_node: P<Node>, check_mode: CheckMode) -> P<Type> {
        todo!()
    }

    // checker.go:11639
    pub(crate) fn get_control_flow_container(&mut self, node: P<Node>) -> Option<P<Node>> {
        todo!()
    }

    // checker.go:11645
    pub(crate) fn get_flow_type_of_property(&mut self, reference: P<Node>, prop: Option<P<Symbol>>) -> P<Type> {
        todo!()
    }

    // checker.go:11656
    pub(crate) fn get_type_of_property_in_base_class(&mut self, property: P<Symbol>) -> Option<P<Type>> {
        todo!()
    }

    // checker.go:11667
    pub(crate) fn is_method_access_for_call(&mut self, node: P<Node>) -> bool {
        todo!()
    }

    // checker.go:11675
    pub(crate) fn lookup_symbol_for_private_identifier_declaration(&mut self, prop_name: &str, location: P<Node>) -> Option<P<Symbol>> {
        todo!()
    }

    // checker.go:11691
    pub(crate) fn get_private_identifier_property_of_type(&mut self, left_type: P<Type>, lexically_scoped_identifier: P<Symbol>) -> Option<P<Symbol>> {
        todo!()
    }

    // checker.go:11695
    pub(crate) fn check_private_identifier_property_access(&mut self, left_type: P<Type>, right: P<Node>, lexically_scoped_identifier: Option<P<Symbol>>) -> bool {
        todo!()
    }

    // checker.go:11731
    pub(crate) fn report_nonexistent_property(&mut self, prop_node: P<Node>, containing_type: P<Type>, is_unchecked_js: bool) {
        todo!()
    }

    // checker.go:11794
    pub(crate) fn get_suggested_lib_for_non_existent_property(&mut self, missing_property: &str, containing_type: P<Type>) -> String {
        todo!()
    }

    // checker.go:11809
    pub(crate) fn get_suggested_symbol_for_nonexistent_property(&mut self, name: P<Node>, containing_type: P<Type>) -> Option<P<Symbol>> {
        todo!()
    }

    // checker.go:11828
    pub(crate) fn is_valid_property_access_for_completions(&mut self, node: P<Node>, t: P<Type>, property: P<Symbol>) -> bool {
        todo!()
    }

    // checker.go:11841
    pub fn is_property_accessible(&mut self, node: P<Node>, is_super: bool, is_write: bool, containing_type: P<Type>, property: P<Symbol>) -> bool {
        todo!()
    }

    // checker.go:11855
    pub(crate) fn container_seems_to_be_empty_dom_element(&mut self, containing_type: P<Type>) -> bool {
        todo!()
    }
}

// checker.go:11859
pub(crate) fn has_common_dom_type_name(t: P<Type>) -> bool {
    todo!()
}

impl Checker {
    // checker.go:11867
    pub(crate) fn check_and_report_error_for_extending_interface(&mut self, error_location: P<Node>) -> bool {
        todo!()
    }

    // checker.go:11879
    pub(crate) fn get_entity_name_for_extending_interface(&mut self, node: P<Node>) -> Option<P<Node>> {
        todo!()
    }

    // checker.go:11895
    pub(crate) fn is_uncalled_function_reference(&mut self, node: P<Node>, symbol: P<Symbol>) -> bool {
        todo!()
    }

    // checker.go:11911
    pub(crate) fn check_property_not_used_before_declaration(&mut self, prop: P<Symbol>, node: P<Node>, right: P<Node>) {
        todo!()
    }

    // checker.go:11933
    pub(crate) fn is_optional_property_declaration(&mut self, node: P<Node>) -> bool {
        todo!()
    }

    // checker.go:11937
    pub(crate) fn is_property_declared_in_ancestor_class(&mut self, prop: P<Symbol>) -> bool {
        todo!()
    }

    // checker.go:11955
    pub(crate) fn check_property_accessibility(&mut self, node: P<Node>, is_super: bool, writing: bool, t: P<Type>, prop: P<Symbol>) -> bool {
        todo!()
    }

    // checker.go:11959
    pub(crate) fn check_property_accessibility_ex(&mut self, node: P<Node>, is_super: bool, writing: bool, t: P<Type>, prop: P<Symbol>, report_error: bool) -> bool {
        todo!()
    }

    // checker.go:11988
    pub(crate) fn check_property_accessibility_at_location(&mut self, location: P<Node>, is_super: bool, writing: bool, containing_type: P<Type>, prop: P<Symbol>, error_node: Option<P<Node>>) -> bool {
        todo!()
    }

    // checker.go:12103
    pub(crate) fn symbol_has_non_method_declaration(&mut self, symbol: P<Symbol>) -> bool {
        todo!()
    }

    // checker.go:12109
    pub(crate) fn for_each_property(&mut self, prop: P<Symbol>, callback: impl FnMut(&mut Checker, P<Symbol>) -> bool) -> bool {
        todo!()
    }

    // checker.go:12123
    pub(crate) fn get_declaring_class(&mut self, prop: P<Symbol>) -> Option<P<Type>> {
        todo!()
    }

    // checker.go:12131
    pub(crate) fn is_valid_override_of(&mut self, source_prop: P<Symbol>, target_prop: P<Symbol>) -> bool {
        todo!()
    }

    // checker.go:12142
    pub(crate) fn is_property_in_class_derived_from(&mut self, prop: P<Symbol>, base_class: P<Type>) -> bool {
        todo!()
    }

    // checker.go:12152
    pub(crate) fn is_node_used_during_class_initialization(&mut self, node: P<Node>) -> bool {
        todo!()
    }

    // checker.go:12163
    pub(crate) fn is_node_within_class(&mut self, node: P<Node>, class_declaration: P<Node>) -> bool {
        todo!()
    }

    // checker.go:12167
    pub(crate) fn for_each_enclosing_class(&mut self, node: P<Node>, callback: impl FnMut(&mut Checker, P<Node>) -> bool) -> bool {
        todo!()
    }

    // checker.go:12181
    pub(crate) fn is_class_derived_from_declaring_classes(&mut self, check_class: P<Type>, prop: P<Symbol>, writing: bool) -> bool {
        todo!()
    }

    // checker.go:12190
    pub(crate) fn get_enclosing_class_from_this_parameter(&mut self, node: P<Node>) -> Option<P<Type>> {
        todo!()
    }
}

// checker.go:12216
pub(crate) fn get_this_parameter_from_node_context(node: P<Node>) -> Option<P<Node>> {
    todo!()
}

impl Checker {
    // checker.go:12224
    pub(crate) fn get_contextual_this_parameter_type(&mut self, fn_: P<Node>) -> Option<P<Type>> {
        todo!()
    }

    // checker.go:12280
    pub(crate) fn check_this_expression(&mut self, node: P<Node>) -> P<Type> {
        todo!()
    }

    // checker.go:12337
    pub(crate) fn try_get_this_type_at(&mut self, node: P<Node>) -> Option<P<Type>> {
        todo!()
    }

    // checker.go:12341
    pub fn try_get_this_type_at_ex_exported(&mut self, node: P<Node>, include_global_this: bool, container: P<Node>) -> Option<P<Type>> {
        todo!()
    }

    // checker.go:12349
    pub(crate) fn try_get_this_type_at_ex(&mut self, node: P<Node>, include_global_this: bool, container: Option<P<Node>>) -> Option<P<Type>> {
        todo!()
    }

    // checker.go:12391
    pub(crate) fn get_this_container(&mut self, node: P<Node>, include_arrow_functions: bool, include_class_computed_property_name: bool) -> Option<P<Node>> {
        todo!()
    }

    // checker.go:12438
    pub(crate) fn is_in_parameter_initializer_before_containing_function(&mut self, node: P<Node>) -> bool {
        todo!()
    }

    // checker.go:12457
    pub(crate) fn check_this_in_static_class_field_initializer_in_decorated_class(&mut self, this_expression: P<Node>, container: P<Node>) {
        todo!()
    }

    // checker.go:12466
    pub(crate) fn check_this_before_super(&mut self, node: P<Node>, container: P<Node>, diagnostic_message: &'static Message) {
        todo!()
    }

    // checker.go:12483
    pub(crate) fn class_declaration_extends_null(&mut self, class_decl: P<Node>) -> bool {
        todo!()
    }

    // checker.go:12490
    pub(crate) fn check_assertion(&mut self, node: P<Node>, check_mode: CheckMode) -> P<Type> {
        todo!()
    }

    // checker.go:12518
    pub(crate) fn check_assertion_deferred(&mut self, node: P<Node>) {
        todo!()
    }

    // checker.go:12534
    pub(crate) fn check_binary_expression(&mut self, node: P<Node>, check_mode: CheckMode) -> P<Type> {
        todo!()
    }

    // checker.go:12539
    pub(crate) fn check_binary_like_expression(&mut self, left: P<Node>, operator_token: P<Node>, right: P<Node>, check_mode: CheckMode, error_node: Option<P<Node>>) -> P<Type> {
        todo!()
    }

    // checker.go:12755
    pub(crate) fn check_destructuring_assignment(&mut self, node: P<Node>, source_type: P<Type>, check_mode: CheckMode, right_is_this: bool) -> P<Type> {
        todo!()
    }

    // checker.go:12788
    pub(crate) fn check_object_literal_assignment(&mut self, node: P<Node>, source_type: P<Type>, right_is_this: bool) -> P<Type> {
        todo!()
    }

    // checker.go:12800
    pub(crate) fn check_object_literal_destructuring_property_assignment(&mut self, node: P<Node>, object_literal_type: P<Type>, property_index: i32, all_properties: Option<P<NodeList>>, right_is_this: bool) -> Option<P<Type>> {
        todo!()
    }

    // checker.go:12851
    pub(crate) fn check_array_literal_assignment(&mut self, node: P<Node>, source_type: P<Type>, check_mode: CheckMode) -> P<Type> {
        todo!()
    }

    // checker.go:12871
    pub(crate) fn check_array_literal_destructuring_element_assignment(&mut self, node: P<Node>, source_type: P<Type>, element_index: i32, element_type: P<Type>, check_mode: CheckMode) -> Option<P<Type>> {
        todo!()
    }

    // checker.go:12912
    pub(crate) fn check_reference_assignment(&mut self, target: P<Node>, source_type: P<Type>, check_mode: CheckMode) -> P<Type> {
        todo!()
    }

    // checker.go:12926
    pub(crate) fn report_operator_error(&mut self, left_type: P<Type>, operator: Kind, right_type: P<Type>, error_node: Option<P<Node>>, is_related: Option<&mut dyn FnMut(&mut Checker, P<Type>, P<Type>) -> bool>) {
        todo!()
    }

    // checker.go:12947
    pub(crate) fn report_operator_error_unless(&mut self, left_type: P<Type>, operator: Kind, right_type: P<Type>, error_node: Option<P<Node>>, types_are_compatible: impl FnMut(&mut Checker, P<Type>, P<Type>) -> bool) {
        todo!()
    }

    // checker.go:12953
    pub(crate) fn get_base_types_if_unrelated(&mut self, left_type: P<Type>, right_type: P<Type>, is_related: impl FnMut(&mut Checker, P<Type>, P<Type>) -> bool) -> (P<Type>, P<Type>) {
        todo!()
    }

    // checker.go:12965
    pub(crate) fn check_assignment_operator(&mut self, left: P<Node>, operator: Kind, right: P<Node>, left_type: P<Type>, right_type: P<Type>) {
        todo!()
    }

    // checker.go:12991
    pub(crate) fn both_are_big_int_like(&mut self, left: P<Type>, right: P<Type>) -> bool {
        todo!()
    }

    // checker.go:12995
    pub(crate) fn get_suggested_boolean_operator(&mut self, operator: Kind) -> Kind {
        todo!()
    }

    // checker.go:13007
    pub(crate) fn check_arithmetic_operand_type(&mut self, operand: P<Node>, t: P<Type>, diagnostic: &'static Message, is_await_valid: bool) -> bool {
        todo!()
    }

    // checker.go:13020
    pub(crate) fn check_for_disallowed_es_symbol_operand(&mut self, left: P<Node>, right: P<Node>, left_type: P<Type>, right_type: P<Type>, operator: Kind) -> bool {
        todo!()
    }

    // checker.go:13035
    pub(crate) fn check_nan_equality(&mut self, error_node: Option<P<Node>>, operator: Kind, left: P<Node>, right: P<Node>) {
        todo!()
    }

    // checker.go:13061
    pub(crate) fn is_global_nan(&mut self, expr: P<Node>) -> bool {
        todo!()
    }
}
