use crate::*;
use tsrs_ast::*;
use tsrs_core::*;
use tsrs_ast as ast;
use tsrs_diagnostics as diagnostics;
use tsrs_diagnostics::Message;
use rustc_hash::FxHashMap;
use std::fmt::Display;

// Stubs generated by tools/gosig. Keep the signatures; replace the todo!() bodies.

impl Checker {
    // exports.go:8
    pub fn get_string_type(&mut self) -> P<Type> {
        todo!()
    }

    // exports.go:12
    pub fn get_number_type(&mut self) -> P<Type> {
        todo!()
    }

    // exports.go:16
    pub fn get_boolean_type(&mut self) -> P<Type> {
        todo!()
    }

    // exports.go:20
    pub fn get_void_type(&mut self) -> P<Type> {
        todo!()
    }

    // exports.go:24
    pub fn get_undefined_type(&mut self) -> P<Type> {
        todo!()
    }

    // exports.go:28
    pub fn get_null_type(&mut self) -> P<Type> {
        todo!()
    }

    // exports.go:32
    pub fn get_any_type(&mut self) -> P<Type> {
        todo!()
    }

    // exports.go:36
    pub fn get_error_type(&mut self) -> P<Type> {
        todo!()
    }

    // exports.go:40
    pub fn get_never_type(&mut self) -> P<Type> {
        todo!()
    }

    // exports.go:44
    pub fn get_unknown_type(&mut self) -> P<Type> {
        todo!()
    }

    // exports.go:48
    pub fn get_big_int_type(&mut self) -> P<Type> {
        todo!()
    }

    // exports.go:52
    pub fn get_es_symbol_type(&mut self) -> P<Type> {
        todo!()
    }

    // exports.go:56
    pub fn get_non_primitive_type(&mut self) -> P<Type> {
        todo!()
    }

    // exports.go:64
    pub fn get_unknown_symbol(&mut self) -> P<Symbol> {
        todo!()
    }

    // exports.go:68
    pub fn get_undefined_symbol(&mut self) -> P<Symbol> {
        todo!()
    }

    // exports.go:72
    pub fn get_arguments_symbol(&mut self) -> P<Symbol> {
        todo!()
    }

    // exports.go:76
    pub fn get_unknown_signature(&mut self) -> P<Signature> {
        todo!()
    }

    // exports.go:84
    pub fn get_name_type_of_symbol(&mut self, symbol: P<Symbol>) -> Option<P<Type>> {
        todo!()
    }

    // exports.go:99
    pub fn get_global_symbol_exported(&mut self, name: &str, meaning: SymbolFlags, diagnostic: &'static Message) -> Option<P<Symbol>> {
        todo!()
    }

    // exports.go:107
    pub fn try_find_ambient_module_exported(&mut self, module_name: &str) -> Option<P<Symbol>> {
        todo!()
    }

    // exports.go:115
    pub fn get_target_symbol_exported(&mut self, symbol: P<Symbol>) -> Option<P<Symbol>> {
        todo!()
    }

    // exports.go:123
    pub fn resolve_external_module_name_exported(&mut self, module_specifier: P<Node>, import_attributes_type: P<Type>) -> Option<P<Symbol>> {
        todo!()
    }

    // exports.go:127
    pub fn resolve_external_module_symbol_exported(&mut self, module_symbol: P<Symbol>) -> P<Symbol> {
        todo!()
    }

    // exports.go:171
    pub fn was_canceled(&mut self) -> bool {
        todo!()
    }

    // exports.go:195
    pub fn get_true_type_of_conditional_type(&mut self, t: P<Type>) -> P<Type> {
        todo!()
    }

    // exports.go:199
    pub fn get_false_type_of_conditional_type(&mut self, t: P<Type>) -> P<Type> {
        todo!()
    }

    // exports.go:203
    pub fn get_default_from_type_parameter_exported(&mut self, type_parameter: P<Type>) -> Option<P<Type>> {
        todo!()
    }
}

// exports.go:223
pub fn is_tuple_type_target(t: P<Type>) -> bool {
    todo!()
}

impl Checker {
    // exports.go:251
    pub fn type_predicate_to_string_exported(&mut self, t: P<TypePredicate>) -> String {
        todo!()
    }

    // exports.go:255
    pub fn get_expanded_parameters_exported(&mut self, signature: P<Signature>, skip_union_expanding: bool) -> Vec<Vec<P<Symbol>>> {
        todo!()
    }

    // exports.go:259
    pub fn get_resolved_signature_exported(&mut self, node: P<Node>) -> P<Signature> {
        todo!()
    }

    // exports.go:268
    pub fn get_contextual_type_for_argument_at_index_exported(&mut self, node: P<Node>, arg_index: i32) -> Option<P<Type>> {
        todo!()
    }

    // exports.go:284
    pub fn get_jsx_namespace_exported(&mut self, location: P<Node>) -> String {
        todo!()
    }

    // exports.go:288
    pub fn get_jsx_fragment_factory(&mut self, location: P<Node>) -> String {
        todo!()
    }

    // exports.go:296
    pub fn resolve_name_exported(&mut self, name: &str, location: P<Node>, meaning: SymbolFlags, exclude_globals: bool) -> Option<P<Symbol>> {
        todo!()
    }

    // exports.go:318
    pub fn get_fully_qualified_name_exported(&mut self, symbol: P<Symbol>) -> String {
        todo!()
    }

    // exports.go:326
    pub fn get_member_override_modifier_status_exported(&mut self, node: P<Node>, member: P<Node>, member_symbol: P<Symbol>) -> MemberOverrideStatus {
        todo!()
    }

    // exports.go:330
    pub fn get_rest_type_of_signature_exported(&mut self, sig: P<Signature>) -> P<Type> {
        todo!()
    }

    // exports.go:370
    pub fn get_union_type_ex_exported(&mut self, types: &[P<Type>], union_reduction: UnionReduction) -> P<Type> {
        todo!()
    }

    // exports.go:374
    pub fn requires_adding_implicit_undefined(&mut self, node: P<Node>) -> bool {
        todo!()
    }

    // exports.go:394
    pub fn compare_symbols_exported(&mut self, s1: P<Symbol>, s2: P<Symbol>) -> i32 {
        todo!()
    }
}

// exports.go:398
pub fn is_distributed_type_parameter(t: P<Type>) -> bool {
    todo!()
}
