use crate::*;
use tsrs_ast::*;
use tsrs_core::*;
use tsrs_ast as ast;
use tsrs_diagnostics as diagnostics;
use tsrs_diagnostics::Message;
use rustc_hash::FxHashMap;
use std::fmt::Display;
use tsrs_binder as binder;
use tsrs_core::{stringutil, tspath, TextRange};
use tsrs_scanner as scanner;

// Stubs generated by tools/gosig. Keep the signatures; replace the todo!() bodies.

impl Checker {
    // grammarchecks.go:19
    pub(crate) fn grammar_error_on_first_token(&mut self, node: P<Node>, message: &'static Message, args: &[&dyn Display]) -> bool {
        let source_file = ast::get_source_file_of_node(node).unwrap();
        if !self.has_parse_diagnostics(source_file) {
            let span = scanner::get_range_of_token_at_position(source_file, node.pos());
            self.add_diagnostic(ast::new_diagnostic(Some(source_file), span, message, args));
            return true;
        }
        false
    }

    // grammarchecks.go:29
    pub(crate) fn grammar_error_at_pos(&mut self, node_for_source_file: P<Node>, start: i32, length: i32, message: &'static Message, args: &[&dyn Display]) -> bool {
        let source_file = ast::get_source_file_of_node(node_for_source_file).unwrap();
        if !self.has_parse_diagnostics(source_file) {
            self.add_diagnostic(ast::new_diagnostic(Some(source_file), TextRange::new(start, start + length), message, args));
            return true;
        }
        false
    }

    // grammarchecks.go:38
    pub(crate) fn grammar_error_on_node(&mut self, node: P<Node>, message: &'static Message, args: &[&dyn Display]) -> bool {
        let source_file = ast::get_source_file_of_node(node).unwrap();
        if !self.has_parse_diagnostics(source_file) {
            self.error(Some(node), message, args);
            return true;
        }
        false
    }

    // grammarchecks.go:47
    pub(crate) fn grammar_error_on_node_skipped_on_no_emit(&mut self, node: P<Node>, message: &'static Message, args: &[&dyn Display]) -> bool {
        let source_file = ast::get_source_file_of_node(node).unwrap();
        if !self.has_parse_diagnostics(source_file) {
            let d = new_diagnostic_for_node(Some(node), Some(message), args);
            d.set_skipped_on_no_emit();
            self.add_diagnostic(d);
            return true;
        }
        false
    }
}

// grammarchecks.go:58
pub(crate) fn get_identifier_from_entity_name_expression(node: P<Node>) -> Option<P<Node>> {
    match node.kind {
        Kind::Identifier => Some(node),
        Kind::PropertyAccessExpression => Some(node.as_property_access_expression().name),
        _ => None,
    }
}

// Body of the scanner error callback installed by checkGrammarRegularExpressionLiteral. The Rust scanner buffers
// errors instead of calling back, so they are drained (in report order) right after every scanner call.
fn on_reg_exp_scanner_errors(c: &mut Checker, s: &mut Scanner, source_file: P<SourceFile>, last_error: &mut Option<P<Diagnostic>>) {
    for e in s.take_errors() {
        let (message, start, length) = (e.message, e.start, e.length);
        let args: Vec<&dyn Display> = e.args.iter().map(|a| a as &dyn Display).collect();
        if message.category() == diagnostics::Category::Message && last_error.is_some_and(|le| start == le.pos() && length == le.len()) {
            // For providing spelling suggestions.
            let err = ast::new_diagnostic(None, TextRange::new(start, start + length), message, &args);
            last_error.unwrap().add_related_info(err);
        } else if last_error.is_none_or(|le| start != le.pos()) {
            let d = ast::new_diagnostic(Some(source_file), TextRange::new(start, start + length), message, &args);
            *last_error = Some(c.add_diagnostic(d));
        }
    }
}

impl Checker {
    // grammarchecks.go:69
    pub(crate) fn check_grammar_regular_expression_literal(&mut self, node: P<Node>) -> bool {
        let source_file = ast::get_source_file_of_node(node).unwrap();
        if !self.has_parse_diagnostics(source_file) {
            let mut last_error: Option<P<Diagnostic>> = None;
            if self.reg_exp_scanner.is_none() {
                self.reg_exp_scanner = Some(Box::new(Scanner::new()));
            }
            let mut s = self.reg_exp_scanner.take().unwrap();
            s.set_script_target(self.language_version);
            s.set_language_variant(source_file.language_variant());
            s.set_on_error(true);
            s.set_text(source_file.text());
            s.reset_token_state(node.pos());
            s.scan();
            on_reg_exp_scanner_errors(self, &mut s, source_file, &mut last_error);
            let token_is_regular_expression_literal = s.re_scan_slash_token(true) == Kind::RegularExpressionLiteral;
            on_reg_exp_scanner_errors(self, &mut s, source_file, &mut last_error);
            s.set_text("");
            s.set_on_error(false);
            self.reg_exp_scanner = Some(s);
            assert!(token_is_regular_expression_literal);
            return last_error.is_some();
        }
        false
    }

    // grammarchecks.go:100
    pub(crate) fn check_grammar_private_identifier_expression(&mut self, priv_id: P<Node>) -> bool {
        let priv_id_as_node = priv_id;
        if ast::get_containing_class(priv_id).is_none() {
            return self.grammar_error_on_node(priv_id, &diagnostics::Private_identifiers_are_not_allowed_outside_class_bodies, &[]);
        }

        let parent = priv_id.parent().unwrap();
        if !is_for_in_statement(parent) {
            if !ast::is_expression_node(priv_id_as_node) {
                return self.grammar_error_on_node(priv_id_as_node, &diagnostics::Private_identifiers_are_only_allowed_in_class_bodies_and_may_only_be_used_as_part_of_a_class_member_declaration_property_access_or_on_the_left_hand_side_of_an_in_expression, &[]);
            }

            let is_in_operation = is_binary_expression(parent) && parent.as_binary_expression().operator_token.kind == Kind::InKeyword;
            if self.get_symbol_for_private_identifier_expression(priv_id_as_node).is_none() && !is_in_operation {
                return self.grammar_error_on_node(priv_id_as_node, &diagnostics::Cannot_find_name_0, &[&priv_id.text()]);
            }
        }

        false
    }

    // grammarchecks.go:120
    pub(crate) fn check_grammar_mapped_type(&mut self, node: P<Node>) -> bool {
        let members = node.as_mapped_type_node().members.unwrap();
        if !members.nodes.is_empty() {
            return self.grammar_error_on_node(members.nodes[0], &diagnostics::A_mapped_type_may_not_declare_properties_or_methods, &[]);
        }
        false
    }

    // grammarchecks.go:127
    pub(crate) fn check_grammar_decorator(&mut self, decorator: P<Node>) -> bool {
        let source_file = ast::get_source_file_of_node(decorator).unwrap();
        if !self.has_parse_diagnostics(source_file) {
            let mut node = decorator.as_decorator().expression;

            // DecoratorParenthesizedExpression :
            //   `(` Expression `)`

            if is_parenthesized_expression(node) {
                return false;
            }

            let mut can_have_call_expression = true;
            let mut error_node: Option<P<Node>> = None;
            loop {
                // Allow TS syntax such as non-null assertions and instantiation expressions
                if is_expression_with_type_arguments(node) || is_non_null_expression(node) {
                    node = node.expression().unwrap();
                    continue;
                }

                // DecoratorCallExpression :
                //   DecoratorMemberExpression Arguments

                if is_call_expression(node) {
                    let call_expr = node.as_call_expression();
                    if !can_have_call_expression {
                        error_node = Some(node);
                    }
                    if call_expr.question_dot_token.is_some() {
                        // Even if we already have an error node, error at the `?.` token since it appears earlier.
                        error_node = call_expr.question_dot_token;
                    }
                    node = call_expr.expression;
                    can_have_call_expression = false;
                    continue;
                }

                // DecoratorMemberExpression :
                //   IdentifierReference
                //   DecoratorMemberExpression `.` IdentifierName
                //   DecoratorMemberExpression `.` PrivateIdentifier

                if is_property_access_expression(node) {
                    let property_access_expr = node.as_property_access_expression();
                    if property_access_expr.question_dot_token.is_some() {
                        // Even if we already have an error node, error at the `?.` token since it appears earlier.
                        error_node = property_access_expr.question_dot_token;
                    }
                    node = property_access_expr.expression;
                    can_have_call_expression = false;
                    continue;
                }

                if !is_identifier(node) {
                    // Even if we already have an error node, error at this node since it appears earlier.
                    error_node = Some(node);
                }

                break;
            }

            if let Some(error_node) = error_node {
                let err = self.error(Some(decorator.as_decorator().expression), &diagnostics::Expression_must_be_enclosed_in_parentheses_to_be_used_as_a_decorator, &[]);
                err.add_related_info(create_diagnostic_for_node(Some(error_node), &diagnostics::Invalid_syntax_in_decorator, &[]));
                return true;
            }
        }

        false
    }

    // grammarchecks.go:199
    pub(crate) fn check_grammar_export_declaration(&mut self, node: P<Node>) -> bool {
        let export_decl = node.as_export_declaration();
        if export_decl.is_type_only {
            if let Some(export_clause) = export_decl.export_clause {
                if export_clause.kind == Kind::NamedExports {
                    return self.check_grammar_type_only_named_imports_or_exports(export_clause);
                }
            }
        }
        false
    }

    // grammarchecks.go:206
    pub(crate) fn check_grammar_module_element_context(&mut self, node: P<Node>, error_message: &'static Message) -> bool {
        let parent_kind = node.parent().unwrap().kind;
        let is_in_appropriate_context = parent_kind == Kind::SourceFile || parent_kind == Kind::ModuleBlock || parent_kind == Kind::ModuleDeclaration;
        if !is_in_appropriate_context {
            self.grammar_error_on_first_token(node, error_message, &[]);
        }
        !is_in_appropriate_context
    }

    // grammarchecks.go:214
    pub(crate) fn check_grammar_modifiers(&mut self, node: P<Node>) -> bool {
        if node.modifiers().is_none() {
            return false;
        }
        if self.report_obvious_decorator_errors(node) || self.report_obvious_modifier_errors(node) {
            return true;
        }
        if ast::is_this_parameter(node) {
            return self.grammar_error_on_first_token(node, &diagnostics::Neither_decorators_nor_modifiers_may_be_applied_to_this_parameters, &[]);
        }
        let mut block_scope_kind = NodeFlags::None;
        if is_variable_statement(node) {
            block_scope_kind = node.as_variable_statement().declaration_list.flags() & NodeFlags::BlockScoped;
        }
        let mut last_static: Option<P<Node>> = None;
        let mut last_declare: Option<P<Node>> = None;
        let mut last_async: Option<P<Node>> = None;
        let mut last_override: Option<P<Node>> = None;
        let mut first_decorator: Option<P<Node>> = None;
        let mut flags = ModifierFlags::None;
        let mut saw_export_before_decorators = false;
        // We parse decorators and modifiers in four contiguous chunks:
        // [...leadingDecorators, ...leadingModifiers, ...trailingDecorators, ...trailingModifiers]. It is an error to
        // have both leading and trailing decorators.
        let mut has_leading_decorators = false;
        let parent = node.parent().unwrap();
        let modifiers = node.modifier_nodes();
        for &modifier in modifiers {
            if is_decorator(modifier) {
                if !ast::node_can_be_decorated(self.legacy_decorators, node, Some(parent), parent.parent()) {
                    if node.kind == Kind::MethodDeclaration && !ast::node_is_present(node.body()) {
                        return self.grammar_error_on_first_token(node, &diagnostics::A_decorator_can_only_decorate_a_method_implementation_not_an_overload, &[]);
                    } else {
                        return self.grammar_error_on_first_token(node, &diagnostics::Decorators_are_not_valid_here, &[]);
                    }
                } else if self.legacy_decorators && (node.kind == Kind::GetAccessor || node.kind == Kind::SetAccessor) {
                    let symbol = self.get_symbol_of_declaration(node).unwrap();
                    let declarations: Vec<P<Node>> = symbol.declarations().clone();
                    let accessors = ast::get_all_accessor_declarations_for_declaration(node, &declarations);
                    if ast::has_decorators(accessors.first_accessor) && Some(node) == accessors.second_accessor {
                        return self.grammar_error_on_first_token(node, &diagnostics::Decorators_cannot_be_applied_to_multiple_get_Slashset_accessors_of_the_same_name, &[]);
                    }
                }

                // if we've seen any modifiers aside from `export`, `default`, or another decorator, then this is an invalid position
                if flags.intersects(!(ModifierFlags::ExportDefault | ModifierFlags::Decorator)) {
                    return self.grammar_error_on_node(modifier, &diagnostics::Decorators_are_not_valid_here, &[]);
                }

                // if we've already seen leading decorators and leading modifiers, then trailing decorators are an invalid position
                if has_leading_decorators && flags.intersects(ModifierFlags::Modifier) {
                    if first_decorator.is_none() {
                        panic!("Expected firstDecorator to be set");
                    }
                    let source_file = ast::get_source_file_of_node(modifier).unwrap();
                    if !self.has_parse_diagnostics(source_file) {
                        let err = self.error(Some(modifier), &diagnostics::Decorators_may_not_appear_after_export_or_export_default_if_they_also_appear_before_export, &[]);
                        err.add_related_info(create_diagnostic_for_node(first_decorator, &diagnostics::Decorator_used_before_export_here, &[]));
                        return true;
                    }
                    return false;
                }

                flags |= ModifierFlags::Decorator;

                // if we have not yet seen a modifier, then these are leading decorators
                if !flags.intersects(ModifierFlags::Modifier) {
                    has_leading_decorators = true;
                } else if flags.intersects(ModifierFlags::Export) {
                    saw_export_before_decorators = true;
                }

                if first_decorator.is_none() {
                    first_decorator = Some(modifier);
                }
            } else {
                let modifier_not_reparsed = !modifier.flags().intersects(NodeFlags::Reparsed);
                if modifier.kind != Kind::ReadonlyKeyword {
                    if node.kind == Kind::PropertySignature || node.kind == Kind::MethodSignature {
                        return self.grammar_error_on_node(modifier, &diagnostics::X_0_modifier_cannot_appear_on_a_type_member, &[&scanner::token_to_string(modifier.kind)]);
                    }
                    if node.kind == Kind::IndexSignature && (modifier.kind != Kind::StaticKeyword || !ast::is_class_like(parent)) {
                        return self.grammar_error_on_node(modifier, &diagnostics::X_0_modifier_cannot_appear_on_an_index_signature, &[&scanner::token_to_string(modifier.kind)]);
                    }
                }
                if modifier.kind != Kind::InKeyword && modifier.kind != Kind::OutKeyword && modifier.kind != Kind::ConstKeyword {
                    if node.kind == Kind::TypeParameter {
                        return self.grammar_error_on_node(modifier, &diagnostics::X_0_modifier_cannot_appear_on_a_type_parameter, &[&scanner::token_to_string(modifier.kind)]);
                    }
                }
                match modifier.kind {
                    Kind::ConstKeyword => {
                        if node.kind != Kind::EnumDeclaration && node.kind != Kind::TypeParameter {
                            return self.grammar_error_on_node(node, &diagnostics::A_class_member_cannot_have_the_0_keyword, &[&scanner::token_to_string(Kind::ConstKeyword)]);
                        }
                        if node.kind == Kind::TypeParameter {
                            if !(ast::is_function_like_declaration(parent) || ast::is_class_like(parent) || is_function_type_node(parent) || is_constructor_type_node(parent) || is_call_signature_declaration(parent) || is_construct_signature_declaration(parent) || ast::is_method_signature_declaration(parent)) {
                                return self.grammar_error_on_node(modifier, &diagnostics::X_0_modifier_can_only_appear_on_a_type_parameter_of_a_function_method_or_class, &[&scanner::token_to_string(modifier.kind)]);
                            }
                        }
                    }
                    Kind::OverrideKeyword => {
                        // If node.kind === SyntaxKind.Parameter, checkParameter reports an error if it's not a parameter property.
                        if flags.intersects(ModifierFlags::Override) {
                            return self.grammar_error_on_node(modifier, &diagnostics::X_0_modifier_already_seen, &[&"override"]);
                        } else if flags.intersects(ModifierFlags::Ambient) {
                            return self.grammar_error_on_node(modifier, &diagnostics::X_0_modifier_cannot_be_used_with_1_modifier, &[&"override", &"declare"]);
                        } else if flags.intersects(ModifierFlags::Readonly) && modifier_not_reparsed {
                            return self.grammar_error_on_node(modifier, &diagnostics::X_0_modifier_must_precede_1_modifier, &[&"override", &"readonly"]);
                        } else if flags.intersects(ModifierFlags::Accessor) && modifier_not_reparsed {
                            return self.grammar_error_on_node(modifier, &diagnostics::X_0_modifier_must_precede_1_modifier, &[&"override", &"accessor"]);
                        } else if flags.intersects(ModifierFlags::Async) && modifier_not_reparsed {
                            return self.grammar_error_on_node(modifier, &diagnostics::X_0_modifier_must_precede_1_modifier, &[&"override", &"async"]);
                        }
                        flags |= ModifierFlags::Override;
                        last_override = Some(modifier);
                    }
                    Kind::PublicKeyword | Kind::ProtectedKeyword | Kind::PrivateKeyword => {
                        let text = visibility_to_string(ast::modifier_to_flag(modifier.kind));

                        if flags.intersects(ModifierFlags::AccessibilityModifier) {
                            return self.grammar_error_on_node(modifier, &diagnostics::Accessibility_modifier_already_seen, &[]);
                        } else if flags.intersects(ModifierFlags::Override) && modifier_not_reparsed {
                            return self.grammar_error_on_node(modifier, &diagnostics::X_0_modifier_must_precede_1_modifier, &[&text, &"override"]);
                        } else if flags.intersects(ModifierFlags::Static) && modifier_not_reparsed {
                            return self.grammar_error_on_node(modifier, &diagnostics::X_0_modifier_must_precede_1_modifier, &[&text, &"static"]);
                        } else if flags.intersects(ModifierFlags::Accessor) && modifier_not_reparsed {
                            return self.grammar_error_on_node(modifier, &diagnostics::X_0_modifier_must_precede_1_modifier, &[&text, &"accessor"]);
                        } else if flags.intersects(ModifierFlags::Readonly) && modifier_not_reparsed {
                            return self.grammar_error_on_node(modifier, &diagnostics::X_0_modifier_must_precede_1_modifier, &[&text, &"readonly"]);
                        } else if flags.intersects(ModifierFlags::Async) && modifier_not_reparsed {
                            return self.grammar_error_on_node(modifier, &diagnostics::X_0_modifier_must_precede_1_modifier, &[&text, &"async"]);
                        } else if parent.kind == Kind::ModuleBlock || parent.kind == Kind::SourceFile {
                            return self.grammar_error_on_node(modifier, &diagnostics::X_0_modifier_cannot_appear_on_a_module_or_namespace_element, &[&text]);
                        } else if flags.intersects(ModifierFlags::Abstract) {
                            if modifier.kind == Kind::PrivateKeyword {
                                return self.grammar_error_on_node(modifier, &diagnostics::X_0_modifier_cannot_be_used_with_1_modifier, &[&text, &"abstract"]);
                            } else if modifier_not_reparsed {
                                return self.grammar_error_on_node(modifier, &diagnostics::X_0_modifier_must_precede_1_modifier, &[&text, &"abstract"]);
                            }
                        } else if ast::is_private_identifier_class_element_declaration(node) {
                            return self.grammar_error_on_node(modifier, &diagnostics::An_accessibility_modifier_cannot_be_used_with_a_private_identifier, &[]);
                        }
                        flags |= ast::modifier_to_flag(modifier.kind);
                    }
                    Kind::StaticKeyword => {
                        if flags.intersects(ModifierFlags::Static) {
                            return self.grammar_error_on_node(modifier, &diagnostics::X_0_modifier_already_seen, &[&"static"]);
                        } else if flags.intersects(ModifierFlags::Readonly) && modifier_not_reparsed {
                            return self.grammar_error_on_node(modifier, &diagnostics::X_0_modifier_must_precede_1_modifier, &[&"static", &"readonly"]);
                        } else if flags.intersects(ModifierFlags::Async) && modifier_not_reparsed {
                            return self.grammar_error_on_node(modifier, &diagnostics::X_0_modifier_must_precede_1_modifier, &[&"static", &"async"]);
                        } else if flags.intersects(ModifierFlags::Accessor) && modifier_not_reparsed {
                            return self.grammar_error_on_node(modifier, &diagnostics::X_0_modifier_must_precede_1_modifier, &[&"static", &"accessor"]);
                        } else if parent.kind == Kind::ModuleBlock || parent.kind == Kind::SourceFile {
                            return self.grammar_error_on_node(modifier, &diagnostics::X_0_modifier_cannot_appear_on_a_module_or_namespace_element, &[&"static"]);
                        } else if node.kind == Kind::Parameter {
                            return self.grammar_error_on_node(modifier, &diagnostics::X_0_modifier_cannot_appear_on_a_parameter, &[&"static"]);
                        } else if flags.intersects(ModifierFlags::Abstract) {
                            return self.grammar_error_on_node(modifier, &diagnostics::X_0_modifier_cannot_be_used_with_1_modifier, &[&"static", &"abstract"]);
                        } else if flags.intersects(ModifierFlags::Override) && modifier_not_reparsed {
                            return self.grammar_error_on_node(modifier, &diagnostics::X_0_modifier_must_precede_1_modifier, &[&"static", &"override"]);
                        }
                        flags |= ModifierFlags::Static;
                        last_static = Some(modifier);
                    }
                    Kind::AccessorKeyword => {
                        if flags.intersects(ModifierFlags::Accessor) {
                            return self.grammar_error_on_node(modifier, &diagnostics::X_0_modifier_already_seen, &[&"accessor"]);
                        } else if flags.intersects(ModifierFlags::Readonly) {
                            return self.grammar_error_on_node(modifier, &diagnostics::X_0_modifier_cannot_be_used_with_1_modifier, &[&"accessor", &"readonly"]);
                        } else if flags.intersects(ModifierFlags::Ambient) {
                            return self.grammar_error_on_node(modifier, &diagnostics::X_0_modifier_cannot_be_used_with_1_modifier, &[&"accessor", &"declare"]);
                        } else if node.kind != Kind::PropertyDeclaration {
                            return self.grammar_error_on_node(modifier, &diagnostics::X_accessor_modifier_can_only_appear_on_a_property_declaration, &[]);
                        }

                        flags |= ModifierFlags::Accessor;
                    }
                    Kind::ReadonlyKeyword => {
                        if flags.intersects(ModifierFlags::Readonly) {
                            return self.grammar_error_on_node(modifier, &diagnostics::X_0_modifier_already_seen, &[&"readonly"]);
                        } else if node.kind != Kind::PropertyDeclaration && node.kind != Kind::PropertySignature && node.kind != Kind::IndexSignature && node.kind != Kind::Parameter {
                            // If node.kind === SyntaxKind.Parameter, checkParameter reports an error if it's not a parameter property.
                            return self.grammar_error_on_node(modifier, &diagnostics::X_readonly_modifier_can_only_appear_on_a_property_declaration_or_index_signature, &[]);
                        } else if flags.intersects(ModifierFlags::Accessor) {
                            return self.grammar_error_on_node(modifier, &diagnostics::X_0_modifier_cannot_be_used_with_1_modifier, &[&"readonly", &"accessor"]);
                        }
                        flags |= ModifierFlags::Readonly;
                    }
                    Kind::ExportKeyword => {
                        if self.compiler_options.verbatim_module_syntax == Tristate::True
                            && !node.flags().intersects(NodeFlags::Ambient)
                            && node.kind != Kind::TypeAliasDeclaration
                            && node.kind != Kind::InterfaceDeclaration
                            && node.kind != Kind::ModuleDeclaration
                            && parent.kind == Kind::SourceFile
                            && self.program.get_emit_module_format_of_file(ast::get_source_file_of_node(node).unwrap()) == ModuleKind::CommonJS
                        {
                            return self.grammar_error_on_node(modifier, &diagnostics::A_top_level_export_modifier_cannot_be_used_on_value_declarations_in_a_CommonJS_module_when_verbatimModuleSyntax_is_enabled, &[]);
                        }
                        if flags.intersects(ModifierFlags::Export) {
                            return self.grammar_error_on_node(modifier, &diagnostics::X_0_modifier_already_seen, &[&"export"]);
                        } else if flags.intersects(ModifierFlags::Ambient) && modifier_not_reparsed {
                            return self.grammar_error_on_node(modifier, &diagnostics::X_0_modifier_must_precede_1_modifier, &[&"export", &"declare"]);
                        } else if flags.intersects(ModifierFlags::Abstract) && modifier_not_reparsed {
                            return self.grammar_error_on_node(modifier, &diagnostics::X_0_modifier_must_precede_1_modifier, &[&"export", &"abstract"]);
                        } else if flags.intersects(ModifierFlags::Async) && modifier_not_reparsed {
                            return self.grammar_error_on_node(modifier, &diagnostics::X_0_modifier_must_precede_1_modifier, &[&"export", &"async"]);
                        } else if ast::is_class_like(parent) && !is_js_type_alias_declaration(node) {
                            return self.grammar_error_on_node(modifier, &diagnostics::X_0_modifier_cannot_appear_on_class_elements_of_this_kind, &[&"export"]);
                        } else if node.kind == Kind::Parameter {
                            return self.grammar_error_on_node(modifier, &diagnostics::X_0_modifier_cannot_appear_on_a_parameter, &[&"export"]);
                        } else if block_scope_kind == NodeFlags::Using {
                            return self.grammar_error_on_node(modifier, &diagnostics::X_0_modifier_cannot_appear_on_a_using_declaration, &[&"export"]);
                        } else if block_scope_kind == NodeFlags::AwaitUsing {
                            return self.grammar_error_on_node(modifier, &diagnostics::X_0_modifier_cannot_appear_on_an_await_using_declaration, &[&"export"]);
                        }
                        flags |= ModifierFlags::Export;
                    }
                    Kind::DefaultKeyword => {
                        let container = if parent.kind == Kind::SourceFile { parent } else { parent.parent().unwrap() };
                        if container.kind == Kind::ModuleDeclaration && !ast::is_ambient_module(container) {
                            return self.grammar_error_on_node(modifier, &diagnostics::A_default_export_can_only_be_used_in_an_ECMAScript_style_module, &[]);
                        } else if block_scope_kind == NodeFlags::Using {
                            return self.grammar_error_on_node(modifier, &diagnostics::X_0_modifier_cannot_appear_on_a_using_declaration, &[&"default"]);
                        } else if block_scope_kind == NodeFlags::AwaitUsing {
                            return self.grammar_error_on_node(modifier, &diagnostics::X_0_modifier_cannot_appear_on_an_await_using_declaration, &[&"default"]);
                        } else if !flags.intersects(ModifierFlags::Export) && modifier_not_reparsed {
                            return self.grammar_error_on_node(modifier, &diagnostics::X_0_modifier_must_precede_1_modifier, &[&"export", &"default"]);
                        } else if saw_export_before_decorators {
                            return self.grammar_error_on_node(first_decorator.unwrap(), &diagnostics::Decorators_are_not_valid_here, &[]);
                        }

                        flags |= ModifierFlags::Default;
                    }
                    Kind::DeclareKeyword => {
                        if flags.intersects(ModifierFlags::Ambient) {
                            return self.grammar_error_on_node(modifier, &diagnostics::X_0_modifier_already_seen, &[&"declare"]);
                        } else if flags.intersects(ModifierFlags::Async) {
                            return self.grammar_error_on_node(modifier, &diagnostics::X_0_modifier_cannot_be_used_in_an_ambient_context, &[&"async"]);
                        } else if flags.intersects(ModifierFlags::Override) {
                            return self.grammar_error_on_node(modifier, &diagnostics::X_0_modifier_cannot_be_used_in_an_ambient_context, &[&"override"]);
                        } else if ast::is_class_like(parent) && !is_property_declaration(node) {
                            return self.grammar_error_on_node(modifier, &diagnostics::X_0_modifier_cannot_appear_on_class_elements_of_this_kind, &[&"declare"]);
                        } else if node.kind == Kind::Parameter {
                            return self.grammar_error_on_node(modifier, &diagnostics::X_0_modifier_cannot_appear_on_a_parameter, &[&"declare"]);
                        } else if block_scope_kind == NodeFlags::Using {
                            return self.grammar_error_on_node(modifier, &diagnostics::X_0_modifier_cannot_appear_on_a_using_declaration, &[&"declare"]);
                        } else if block_scope_kind == NodeFlags::AwaitUsing {
                            return self.grammar_error_on_node(modifier, &diagnostics::X_0_modifier_cannot_appear_on_an_await_using_declaration, &[&"declare"]);
                        } else if parent.flags().intersects(NodeFlags::Ambient) && parent.kind == Kind::ModuleBlock {
                            return self.grammar_error_on_node(modifier, &diagnostics::A_declare_modifier_cannot_be_used_in_an_already_ambient_context, &[]);
                        } else if ast::is_private_identifier_class_element_declaration(node) {
                            return self.grammar_error_on_node(modifier, &diagnostics::X_0_modifier_cannot_be_used_with_a_private_identifier, &[&"declare"]);
                        } else if flags.intersects(ModifierFlags::Accessor) {
                            return self.grammar_error_on_node(modifier, &diagnostics::X_0_modifier_cannot_be_used_with_1_modifier, &[&"declare", &"accessor"]);
                        }
                        flags |= ModifierFlags::Ambient;
                        last_declare = Some(modifier);
                    }
                    Kind::AbstractKeyword => {
                        if flags.intersects(ModifierFlags::Abstract) {
                            return self.grammar_error_on_node(modifier, &diagnostics::X_0_modifier_already_seen, &[&"abstract"]);
                        }
                        if node.kind != Kind::ClassDeclaration && node.kind != Kind::ConstructorType {
                            if node.kind != Kind::MethodDeclaration && node.kind != Kind::PropertyDeclaration && node.kind != Kind::GetAccessor && node.kind != Kind::SetAccessor {
                                return self.grammar_error_on_node(modifier, &diagnostics::X_abstract_modifier_can_only_appear_on_a_class_method_or_property_declaration, &[]);
                            }
                            if !(parent.kind == Kind::ClassDeclaration && ast::has_syntactic_modifier(parent, ModifierFlags::Abstract)) {
                                let message = if node.kind == Kind::PropertyDeclaration {
                                    &diagnostics::Abstract_properties_can_only_appear_within_an_abstract_class
                                } else {
                                    &diagnostics::Abstract_methods_can_only_appear_within_an_abstract_class
                                };
                                return self.grammar_error_on_node(modifier, message, &[]);
                            }
                            if flags.intersects(ModifierFlags::Static) {
                                return self.grammar_error_on_node(modifier, &diagnostics::X_0_modifier_cannot_be_used_with_1_modifier, &[&"static", &"abstract"]);
                            }
                            if flags.intersects(ModifierFlags::Private) {
                                return self.grammar_error_on_node(modifier, &diagnostics::X_0_modifier_cannot_be_used_with_1_modifier, &[&"private", &"abstract"]);
                            }
                            if flags.intersects(ModifierFlags::Async) {
                                if let Some(last_async) = last_async {
                                    return self.grammar_error_on_node(last_async, &diagnostics::X_0_modifier_cannot_be_used_with_1_modifier, &[&"async", &"abstract"]);
                                }
                            }
                            if flags.intersects(ModifierFlags::Override) && modifier_not_reparsed {
                                return self.grammar_error_on_node(modifier, &diagnostics::X_0_modifier_must_precede_1_modifier, &[&"abstract", &"override"]);
                            }
                            if flags.intersects(ModifierFlags::Accessor) && modifier_not_reparsed {
                                return self.grammar_error_on_node(modifier, &diagnostics::X_0_modifier_must_precede_1_modifier, &[&"abstract", &"accessor"]);
                            }
                        }
                        if let Some(name) = node.name() {
                            if name.kind == Kind::PrivateIdentifier {
                                return self.grammar_error_on_node(modifier, &diagnostics::X_0_modifier_cannot_be_used_with_a_private_identifier, &[&"abstract"]);
                            }
                        }

                        flags |= ModifierFlags::Abstract;
                    }
                    Kind::AsyncKeyword => {
                        if flags.intersects(ModifierFlags::Async) {
                            return self.grammar_error_on_node(modifier, &diagnostics::X_0_modifier_already_seen, &[&"async"]);
                        } else if flags.intersects(ModifierFlags::Ambient) || parent.flags().intersects(NodeFlags::Ambient) {
                            return self.grammar_error_on_node(modifier, &diagnostics::X_0_modifier_cannot_be_used_in_an_ambient_context, &[&"async"]);
                        } else if node.kind == Kind::Parameter {
                            return self.grammar_error_on_node(modifier, &diagnostics::X_0_modifier_cannot_appear_on_a_parameter, &[&"async"]);
                        }
                        if flags.intersects(ModifierFlags::Abstract) {
                            return self.grammar_error_on_node(modifier, &diagnostics::X_0_modifier_cannot_be_used_with_1_modifier, &[&"async", &"abstract"]);
                        }
                        flags |= ModifierFlags::Async;
                        last_async = Some(modifier);
                    }
                    Kind::InKeyword | Kind::OutKeyword => {
                        let in_out_flag = if modifier.kind == Kind::InKeyword { ModifierFlags::In } else { ModifierFlags::Out };
                        let in_out_text = if modifier.kind == Kind::InKeyword { "in" } else { "out" };
                        let parent = node.parent();
                        if node.kind != Kind::TypeParameter
                            || parent.is_some_and(|parent| !(is_interface_declaration(parent) || ast::is_class_like(parent) || ast::is_type_or_js_type_alias_declaration(parent)))
                        {
                            return self.grammar_error_on_node(modifier, &diagnostics::X_0_modifier_can_only_appear_on_a_type_parameter_of_a_class_interface_or_type_alias, &[&in_out_text]);
                        }
                        if flags.intersects(in_out_flag) {
                            return self.grammar_error_on_node(modifier, &diagnostics::X_0_modifier_already_seen, &[&in_out_text]);
                        }
                        if in_out_flag.intersects(ModifierFlags::In) && flags.intersects(ModifierFlags::Out) {
                            return self.grammar_error_on_node(modifier, &diagnostics::X_0_modifier_must_precede_1_modifier, &[&"in", &"out"]);
                        }
                        flags |= in_out_flag;
                    }
                    _ => {}
                }
            }
        }

        if node.kind == Kind::Constructor {
            if flags.intersects(ModifierFlags::Static) {
                return self.grammar_error_on_node(last_static.unwrap(), &diagnostics::X_0_modifier_cannot_appear_on_a_constructor_declaration, &[&"static"]);
            }
            if flags.intersects(ModifierFlags::Override) {
                return self.grammar_error_on_node(last_override.unwrap(), &diagnostics::X_0_modifier_cannot_appear_on_a_constructor_declaration, &[&"override"]);
            }
            if flags.intersects(ModifierFlags::Async) {
                return self.grammar_error_on_node(last_async.unwrap(), &diagnostics::X_0_modifier_cannot_appear_on_a_constructor_declaration, &[&"async"]);
            }
            return false;
        } else if (node.kind == Kind::ImportDeclaration || node.kind == Kind::JSImportDeclaration || node.kind == Kind::ImportEqualsDeclaration) && flags.intersects(ModifierFlags::Ambient) {
            return self.grammar_error_on_node(last_declare.unwrap(), &diagnostics::A_0_modifier_cannot_be_used_with_an_import_declaration, &[&"declare"]);
        } else if node.kind == Kind::Parameter && flags.intersects(ModifierFlags::ParameterPropertyModifier) && node.name().is_some_and(ast::is_binding_pattern) {
            return self.grammar_error_on_node(node, &diagnostics::A_parameter_property_may_not_be_declared_using_a_binding_pattern, &[]);
        } else if node.kind == Kind::Parameter && flags.intersects(ModifierFlags::ParameterPropertyModifier) && node.as_parameter_declaration().dot_dot_dot_token.is_some() {
            return self.grammar_error_on_node(node, &diagnostics::A_parameter_property_cannot_be_declared_using_a_rest_parameter, &[]);
        }
        if flags.intersects(ModifierFlags::Async) {
            return self.check_grammar_async_modifier(node, last_async);
        }
        false
    }

    // grammarchecks.go:571
    pub(crate) fn report_obvious_modifier_errors(&mut self, node: P<Node>) -> bool {
        let Some(modifier) = self.find_first_illegal_modifier(node) else {
            return false;
        };
        self.grammar_error_on_first_token(modifier, &diagnostics::Modifiers_cannot_appear_here, &[])
    }

    // grammarchecks.go:579
    pub(crate) fn find_first_modifier_except(&mut self, node: P<Node>, allowed_modifier: Kind) -> Option<P<Node>> {
        let modifier = node.modifier_nodes().iter().copied().find(|&m| ast::is_modifier(m));
        if let Some(modifier) = modifier {
            if modifier.kind != allowed_modifier {
                return Some(modifier);
            }
        }
        None
    }

    // grammarchecks.go:587
    pub(crate) fn find_first_illegal_modifier(&mut self, node: P<Node>) -> Option<P<Node>> {
        match node.kind {
            Kind::GetAccessor
            | Kind::SetAccessor
            | Kind::Constructor
            | Kind::PropertyDeclaration
            | Kind::PropertySignature
            | Kind::MethodDeclaration
            | Kind::MethodSignature
            | Kind::IndexSignature
            | Kind::ModuleDeclaration
            | Kind::ImportDeclaration
            | Kind::JSImportDeclaration
            | Kind::ImportEqualsDeclaration
            | Kind::ExportDeclaration
            | Kind::ExportAssignment
            | Kind::FunctionExpression
            | Kind::ArrowFunction
            | Kind::Parameter
            | Kind::TypeParameter
            | Kind::JSTypeAliasDeclaration => None,
            Kind::ClassStaticBlockDeclaration | Kind::PropertyAssignment | Kind::ShorthandPropertyAssignment | Kind::NamespaceExportDeclaration | Kind::MissingDeclaration => {
                node.modifier_nodes().iter().copied().find(|&m| ast::is_modifier(m))
            }
            _ => {
                let parent = node.parent().unwrap();
                if parent.kind == Kind::ModuleBlock || parent.kind == Kind::SourceFile {
                    return None;
                }
                match node.kind {
                    Kind::FunctionDeclaration => self.find_first_modifier_except(node, Kind::AsyncKeyword),
                    Kind::ClassDeclaration | Kind::ConstructorType => self.find_first_modifier_except(node, Kind::AbstractKeyword),
                    Kind::ClassExpression | Kind::InterfaceDeclaration | Kind::TypeAliasDeclaration => node.modifier_nodes().iter().copied().find(|&m| ast::is_modifier(m)),
                    Kind::VariableStatement => {
                        if node.as_variable_statement().declaration_list.flags().intersects(NodeFlags::Using) {
                            return self.find_first_modifier_except(node, Kind::AwaitKeyword);
                        }
                        node.modifier_nodes().iter().copied().find(|&m| ast::is_modifier(m))
                    }
                    Kind::EnumDeclaration => self.find_first_modifier_except(node, Kind::ConstKeyword),
                    _ => panic!("Unhandled case in findFirstIllegalModifier."),
                }
            }
        }
    }

    // grammarchecks.go:642
    pub(crate) fn report_obvious_decorator_errors(&mut self, node: P<Node>) -> bool {
        let Some(decorator) = self.find_first_illegal_decorator(node) else {
            return false;
        };
        self.grammar_error_on_first_token(decorator, &diagnostics::Decorators_are_not_valid_here, &[])
    }

    // grammarchecks.go:650
    pub(crate) fn find_first_illegal_decorator(&mut self, node: P<Node>) -> Option<P<Node>> {
        if ast::can_have_illegal_decorators(node) {
            node.modifier_nodes().iter().copied().find(|&m| is_decorator(m))
        } else {
            None
        }
    }

    // grammarchecks.go:659
    pub(crate) fn check_grammar_async_modifier(&mut self, node: P<Node>, async_modifier: Option<P<Node>>) -> bool {
        match node.kind {
            Kind::MethodDeclaration | Kind::FunctionDeclaration | Kind::FunctionExpression | Kind::ArrowFunction => return false,
            _ => {}
        }

        self.grammar_error_on_node(async_modifier.unwrap(), &diagnostics::X_0_modifier_cannot_be_used_here, &[&"async"])
    }

    // grammarchecks.go:671
    pub(crate) fn check_grammar_for_disallowed_trailing_comma(&mut self, list: Option<P<NodeList>>, diag: &'static Message) -> bool {
        if let Some(list) = list {
            if list.has_trailing_comma() {
                return self.grammar_error_at_pos(list.nodes[0], list.end() - ",".len() as i32, ",".len() as i32, diag, &[]);
            }
        }
        false
    }

    // grammarchecks.go:678
    pub(crate) fn check_grammar_type_parameter_list(&mut self, type_parameters: Option<P<NodeList>>, file: P<SourceFile>) -> bool {
        if let Some(type_parameters) = type_parameters {
            if type_parameters.nodes.is_empty() {
                let start = type_parameters.pos() - "<".len() as i32;
                let end = scanner::skip_trivia(file.text(), type_parameters.end()) + ">".len() as i32;
                return self.grammar_error_at_pos(file.as_node(), start, end - start, &diagnostics::Type_parameter_list_cannot_be_empty, &[]);
            }
        }
        false
    }

    // grammarchecks.go:687
    pub(crate) fn check_grammar_parameter_list(&mut self, parameters: P<NodeList>) -> bool {
        let mut seen_optional_parameter = false;
        let parameter_count = parameters.nodes.len();

        for i in 0..parameter_count {
            let parameter_node = parameters.nodes[i];
            let parameter = parameter_node.as_parameter_declaration();
            if let Some(dot_dot_dot_token) = parameter.dot_dot_dot_token {
                if i != parameter_count - 1 {
                    return self.grammar_error_on_node(dot_dot_dot_token, &diagnostics::A_rest_parameter_must_be_last_in_a_parameter_list, &[]);
                }
                if !parameter_node.flags().intersects(NodeFlags::Ambient) {
                    self.check_grammar_for_disallowed_trailing_comma(Some(parameters), &diagnostics::A_rest_parameter_or_binding_pattern_may_not_have_a_trailing_comma);
                }

                if let Some(question_token) = parameter.question_token() {
                    return self.grammar_error_on_node(question_token, &diagnostics::A_rest_parameter_cannot_be_optional, &[]);
                }

                if parameter.initializer.is_some() {
                    return self.grammar_error_on_node(parameter.name, &diagnostics::A_rest_parameter_cannot_have_an_initializer, &[]);
                }
            } else if crate::is_optional_declaration(parameter_node) {
                seen_optional_parameter = true;
                // A reparsed '?' token indicates a bracketed name in @param tag
                if parameter.question_token().is_some_and(|q| !q.flags().intersects(NodeFlags::Reparsed)) && parameter.initializer.is_some() {
                    return self.grammar_error_on_node(parameter.name, &diagnostics::Parameter_cannot_have_question_mark_and_initializer, &[]);
                }
            } else if seen_optional_parameter && parameter.initializer.is_none() {
                return self.grammar_error_on_node(parameter.name, &diagnostics::A_required_parameter_cannot_follow_an_optional_parameter, &[]);
            }
        }

        false
    }

    // grammarchecks.go:722
    pub(crate) fn check_grammar_for_use_strict_simple_parameter_list(&mut self, node: P<Node>) -> bool {
        todo!()
    }

    // grammarchecks.go:758
    pub(crate) fn check_grammar_function_like_declaration(&mut self, node: P<Node>) -> bool {
        todo!()
    }

    // grammarchecks.go:767
    pub(crate) fn check_grammar_class_like_declaration(&mut self, node: P<Node>) -> bool {
        todo!()
    }

    // grammarchecks.go:772
    pub(crate) fn check_grammar_arrow_function(&mut self, node: P<Node>, file: P<SourceFile>) -> bool {
        todo!()
    }

    // grammarchecks.go:796
    pub(crate) fn check_grammar_index_signature_parameters(&mut self, node: P<Node>) -> bool {
        todo!()
    }

    // grammarchecks.go:840
    pub(crate) fn check_grammar_index_signature(&mut self, node: P<Node>) -> bool {
        todo!()
    }

    // grammarchecks.go:845
    pub(crate) fn check_grammar_for_at_least_one_type_argument(&mut self, node: P<Node>, type_arguments: Option<P<NodeList>>) -> bool {
        todo!()
    }

    // grammarchecks.go:855
    pub(crate) fn check_grammar_type_arguments(&mut self, node: P<Node>, type_arguments: Option<P<NodeList>>) -> bool {
        todo!()
    }

    // grammarchecks.go:859
    pub(crate) fn check_grammar_tagged_template_chain(&mut self, node: P<Node>) -> bool {
        todo!()
    }

    // grammarchecks.go:866
    pub(crate) fn check_grammar_heritage_clause(&mut self, node: P<Node>) -> bool {
        todo!()
    }

    // grammarchecks.go:885
    pub(crate) fn check_grammar_expression_with_type_arguments(&mut self, node: P<Node>) -> bool {
        todo!()
    }

    // grammarchecks.go:892
    pub(crate) fn check_grammar_class_declaration_heritage_clauses(&mut self, node: P<Node>, file: P<SourceFile>) -> bool {
        todo!()
    }

    // grammarchecks.go:935
    pub(crate) fn check_grammar_interface_declaration(&mut self, node: P<Node>) -> bool {
        todo!()
    }

    // grammarchecks.go:961
    pub(crate) fn check_grammar_computed_property_name(&mut self, node: P<Node>) -> bool {
        todo!()
    }

    // grammarchecks.go:974
    pub(crate) fn check_grammar_for_generator(&mut self, node: P<Node>) -> bool {
        todo!()
    }

    // grammarchecks.go:990
    pub(crate) fn check_grammar_for_invalid_question_mark(&mut self, postfix_token: Option<P<Node>>, message: &'static Message) -> bool {
        todo!()
    }

    // grammarchecks.go:994
    pub(crate) fn check_grammar_for_invalid_exclamation_token(&mut self, postfix_token: Option<P<Node>>, message: &'static Message) -> bool {
        todo!()
    }

    // grammarchecks.go:998
    pub(crate) fn check_grammar_object_literal_expression(&mut self, node: P<Node>, in_destructuring: bool) -> bool {
        todo!()
    }

    // grammarchecks.go:1138
    pub(crate) fn check_grammar_jsx_element(&mut self, node: P<Node>) -> bool {
        todo!()
    }

    // grammarchecks.go:1162
    pub(crate) fn check_grammar_jsx_name(&mut self, node: P<Node>) -> bool {
        todo!()
    }

    // grammarchecks.go:1174
    pub(crate) fn check_grammar_jsx_expression(&mut self, node: P<Node>) -> bool {
        todo!()
    }

    // grammarchecks.go:1182
    pub(crate) fn check_grammar_for_in_or_for_of_statement(&mut self, for_in_or_of_statement: P<Node>) -> bool {
        todo!()
    }

    // grammarchecks.go:1289
    pub(crate) fn check_grammar_accessor(&mut self, accessor: P<Node>) -> bool {
        todo!()
    }

    // grammarchecks.go:1345
    pub(crate) fn does_accessor_have_correct_parameter_count(&mut self, accessor: P<Node>) -> bool {
        todo!()
    }

    // grammarchecks.go:1351
    pub(crate) fn check_grammar_type_operator_node(&mut self, node: P<Node>) -> bool {
        todo!()
    }

    // grammarchecks.go:1391
    pub(crate) fn check_grammar_for_invalid_dynamic_name(&mut self, node: P<Node>, message: &'static Message) -> bool {
        todo!()
    }

    // grammarchecks.go:1410
    pub(crate) fn is_non_bindable_dynamic_name(&mut self, node: P<Node>) -> bool {
        todo!()
    }

    // grammarchecks.go:1414
    pub(crate) fn check_grammar_method(&mut self, node: P<Node>) -> bool {
        todo!()
    }

    // grammarchecks.go:1462
    pub(crate) fn check_grammar_break_or_continue_statement(&mut self, node: P<Node>) -> bool {
        todo!()
    }

    // grammarchecks.go:1518
    pub(crate) fn check_grammar_binding_element(&mut self, node: P<Node>) -> bool {
        todo!()
    }

    // grammarchecks.go:1539
    pub(crate) fn check_grammar_variable_declaration(&mut self, node: P<Node>) -> bool {
        todo!()
    }

    // grammarchecks.go:1596
    pub(crate) fn check_grammar_for_es_module_marker_in_binding_name(&mut self, name: P<Node>) -> bool {
        todo!()
    }

    // grammarchecks.go:1611
    pub(crate) fn check_grammar_name_in_let_or_const_declarations(&mut self, name: P<Node>) -> bool {
        todo!()
    }

    // grammarchecks.go:1628
    pub(crate) fn check_grammar_variable_declaration_list(&mut self, declaration_list: P<Node>) -> bool {
        todo!()
    }

    // grammarchecks.go:1658
    pub(crate) fn check_grammar_await_or_await_using(&mut self, node: P<Node>) -> bool {
        todo!()
    }

    // grammarchecks.go:1759
    pub(crate) fn check_grammar_yield_expression(&mut self, node: P<Node>) -> bool {
        todo!()
    }

    // grammarchecks.go:1772
    pub(crate) fn check_grammar_for_disallowed_block_scoped_variable_statement(&mut self, node: P<Node>) -> bool {
        todo!()
    }

    // grammarchecks.go:1796
    pub(crate) fn container_allows_block_scoped_variable(&mut self, parent: P<Node>) -> bool {
        todo!()
    }

    // grammarchecks.go:1813
    pub(crate) fn check_grammar_meta_property(&mut self, node: P<Node>) -> bool {
        todo!()
    }

    // grammarchecks.go:1841
    pub(crate) fn check_grammar_constructor_type_parameters(&mut self, node: P<Node>) -> bool {
        todo!()
    }

    // grammarchecks.go:1856
    pub(crate) fn check_grammar_constructor_type_annotation(&mut self, node: P<Node>) -> bool {
        todo!()
    }

    // grammarchecks.go:1864
    pub(crate) fn check_grammar_property(&mut self, node: P<Node>) -> bool {
        todo!()
    }

    // grammarchecks.go:1925
    pub(crate) fn check_ambient_initializer(&mut self, node: P<Node>) -> bool {
        todo!()
    }
}

// grammarchecks.go:1960
pub(crate) fn is_initializer_string_or_number_literal_expression(expr: P<Node>) -> bool {
    todo!()
}

// grammarchecks.go:1965
pub(crate) fn is_initializer_big_int_literal_expression(expr: P<Node>) -> bool {
    todo!()
}

impl Checker {
    // grammarchecks.go:1978
    pub(crate) fn is_initializer_simple_literal_enum_reference(&mut self, expr: P<Node>) -> bool {
        todo!()
    }

    // grammarchecks.go:1994
    pub(crate) fn check_grammar_top_level_element_for_required_declare_modifier(&mut self, node: P<Node>) -> bool {
        todo!()
    }

    // grammarchecks.go:2014
    pub(crate) fn check_grammar_top_level_elements_for_required_declare_modifier(&mut self, file: P<SourceFile>) -> bool {
        todo!()
    }

    // grammarchecks.go:2025
    pub(crate) fn check_grammar_source_file(&mut self, node: P<SourceFile>) -> bool {
        todo!()
    }

    // grammarchecks.go:2029
    pub(crate) fn check_grammar_statement_in_ambient_context(&mut self, node: P<Node>) -> bool {
        todo!()
    }

    // grammarchecks.go:2059
    pub(crate) fn check_grammar_numeric_literal(&mut self, node: P<Node>) {
        todo!()
    }

    // grammarchecks.go:2087
    pub(crate) fn check_grammar_big_int_literal(&mut self, node: P<Node>) -> bool {
        todo!()
    }

    // grammarchecks.go:2100
    pub(crate) fn check_grammar_import_clause(&mut self, node: P<Node>) -> bool {
        todo!()
    }

    // grammarchecks.go:2123
    pub(crate) fn check_grammar_import_attribute_values(&mut self, node: P<Node>) -> bool {
        todo!()
    }

    // grammarchecks.go:2136
    pub(crate) fn check_grammar_type_only_named_imports_or_exports(&mut self, named_bindings: P<Node>) -> bool {
        todo!()
    }

    // grammarchecks.go:2157
    pub(crate) fn check_grammar_import_call_expression(&mut self, node: P<Node>) -> bool {
        todo!()
    }

    // grammarchecks.go:2200
    pub(crate) fn check_grammar_import_attributes_type(&mut self, attributes: P<Node>) -> bool {
        todo!()
    }
}
