use crate::*;
use tsrs_ast::*;
use tsrs_core::*;
use tsrs_ast as ast;
use tsrs_diagnostics as diagnostics;
use tsrs_diagnostics::Message;
use rustc_hash::FxHashMap;
use std::fmt::Display;

// Stubs generated by tools/gosig. Keep the signatures; replace the todo!() bodies.

impl Checker {
    // jsdoc.go:9
    pub(crate) fn check_unmatched_jsdoc_parameters(&mut self, node: P<Node>) {
        todo!()
    }
}

// jsdoc.go:86
pub(crate) fn get_all_jsdoc_tags(node: P<Node>) -> Vec<P<Node>> {
    todo!()
}
