use crate::*;
use tsrs_ast::*;
use tsrs_core::*;
use tsrs_ast as ast;
use tsrs_diagnostics as diagnostics;
use tsrs_diagnostics::Message;
use rustc_hash::FxHashMap;
use std::fmt::Display;

// Stubs generated by tools/gosig. Keep the signatures; replace the todo!() bodies.

// Non-function declarations in jsx.go (not generated; port by hand in this file):
//   type JsxFlags (jsx.go:17)
//   const (jsx.go:19): JsxFlagsNone, JsxFlagsIntrinsicNamedElement, JsxFlagsIntrinsicIndexedElement,
//     JsxFlagsIntrinsicElement
//   type JsxReferenceKind (jsx.go:26)
//   const (jsx.go:28): JsxReferenceKindComponent, JsxReferenceKindFunction, JsxReferenceKindMixed
//   type JsxElementLinks (jsx.go:34)
//   var JsxNames (jsx.go:42)
//   var ReactNames (jsx.go:66)
//   type JsxElaborationElement (jsx.go:369)

impl Checker {
    // jsx.go:72
    pub(crate) fn check_jsx_element(&mut self, node: P<Node>, check_mode: CheckMode) -> P<Type> {
        todo!()
    }

    // jsx.go:77
    pub(crate) fn check_jsx_element_deferred(&mut self, node: P<Node>) {
        todo!()
    }

    // jsx.go:89
    pub(crate) fn check_jsx_expression(&mut self, node: P<Node>, check_mode: CheckMode) -> P<Type> {
        todo!()
    }

    // jsx.go:101
    pub(crate) fn check_jsx_self_closing_element(&mut self, node: P<Node>, check_mode: CheckMode) -> P<Type> {
        todo!()
    }

    // jsx.go:106
    pub(crate) fn check_jsx_self_closing_element_deferred(&mut self, node: P<Node>) {
        todo!()
    }

    // jsx.go:110
    pub(crate) fn check_jsx_fragment(&mut self, node: P<Node>) -> P<Type> {
        todo!()
    }

    // jsx.go:126
    pub(crate) fn check_jsx_attributes(&mut self, node: P<Node>, check_mode: CheckMode) -> P<Type> {
        todo!()
    }

    // jsx.go:131
    pub(crate) fn check_jsx_opening_like_element_or_opening_fragment(&mut self, node: P<Node>) {
        todo!()
    }

    // jsx.go:160
    pub(crate) fn check_jsx_preconditions(&mut self, error_node: P<Node>) {
        todo!()
    }

    // jsx.go:170
    pub(crate) fn check_jsx_return_assignable_to_appropriate_bound(&mut self, ref_kind: JsxReferenceKind, elem_instance_type: P<Type>, opening_like_element: P<Node>) {
        todo!()
    }

    // jsx.go:198
    pub(crate) fn infer_jsx_type_arguments(&mut self, node: P<Node>, signature: P<Signature>, check_mode: CheckMode, context: P<InferenceContext>) -> Vec<P<Type>> {
        todo!()
    }

    // jsx.go:205
    pub(crate) fn get_contextual_type_for_jsx_expression(&mut self, node: P<Node>, context_flags: ContextFlags) -> Option<P<Type>> {
        todo!()
    }

    // jsx.go:215
    pub(crate) fn get_contextual_type_for_jsx_attribute(&mut self, attribute: P<Node>, context_flags: ContextFlags) -> Option<P<Type>> {
        todo!()
    }

    // jsx.go:229
    pub(crate) fn get_contextual_jsx_element_attributes_type(&mut self, node: P<Node>, context_flags: ContextFlags) -> Option<P<Type>> {
        todo!()
    }

    // jsx.go:242
    pub(crate) fn get_contextual_type_for_child_jsx_expression(&mut self, node: P<Node>, child: P<Node>, context_flags: ContextFlags) -> Option<P<Type>> {
        todo!()
    }

    // jsx.go:266
    pub(crate) fn discriminate_contextual_type_by_jsx_attributes(&mut self, node: P<Node>, contextual_type: P<Type>) -> P<Type> {
        todo!()
    }

    // jsx.go:296
    pub(crate) fn elaborate_jsx_components(&mut self, node: P<Node>, source: P<Type>, target: P<Type>, relation: P<Relation>, diagnostic_output: Option<&mut Vec<P<Diagnostic>>>) -> bool {
        todo!()
    }

    // jsx.go:376
    pub(crate) fn generate_jsx_children(&mut self, node: P<Node>, get_invalid_text_diagnostic: impl FnMut(&mut Checker) -> (&'static Message, Vec<String>)) -> Vec<JsxElaborationElement> {
        todo!()
    }

    // jsx.go:393
    pub(crate) fn get_elaboration_element_for_jsx_child(&mut self, child: P<Node>, name_type: P<Type>, get_invalid_text_diagnostic: impl FnMut(&mut Checker) -> (&'static Message, Vec<String>)) -> JsxElaborationElement {
        todo!()
    }

    // jsx.go:420
    pub(crate) fn elaborate_iterable_or_array_like_target_elementwise(&mut self, iterator: &[JsxElaborationElement], source: P<Type>, target: P<Type>, relation: P<Relation>, diagnostic_output: Option<&mut Vec<P<Diagnostic>>>) -> bool {
        todo!()
    }

    // jsx.go:485
    pub(crate) fn get_suggested_symbol_for_nonexistent_jsx_attribute(&mut self, name: &str, containing_type: P<Type>) -> Option<P<Symbol>> {
        todo!()
    }

    // jsx.go:500
    pub(crate) fn get_jsx_fragment_type(&mut self, node: P<Node>) -> P<Type> {
        todo!()
    }

    // jsx.go:545
    pub(crate) fn resolve_jsx_opening_like_element(&mut self, node: P<Node>, candidates_out_array: Option<&mut Vec<P<Signature>>>, check_mode: CheckMode) -> P<Signature> {
        todo!()
    }

    // jsx.go:591
    pub(crate) fn check_applicable_signature_for_jsx_call_like_element(&mut self, node: P<Node>, signature: P<Signature>, relation: P<Relation>, check_mode: CheckMode, report_errors: bool, diagnostic_output: Option<&mut Vec<P<Diagnostic>>>) -> bool {
        todo!()
    }

    // jsx.go:710
    pub(crate) fn create_jsx_attributes_type_from_attributes_property(&mut self, opening_like_element: P<Node>, check_mode: CheckMode) -> P<Type> {
        todo!()
    }

    // jsx.go:869
    pub(crate) fn check_jsx_attribute(&mut self, node: P<Node>, check_mode: CheckMode) -> P<Type> {
        todo!()
    }

    // jsx.go:877
    pub(crate) fn check_jsx_children(&mut self, node: P<Node>, check_mode: CheckMode) -> Vec<P<Type>> {
        todo!()
    }

    // jsx.go:896
    pub(crate) fn get_uninstantiated_jsx_signatures_of_type(&mut self, element_type: P<Type>, caller: P<Node>) -> Vec<P<Signature>> {
        todo!()
    }

    // jsx.go:925
    pub(crate) fn get_effective_first_argument_for_jsx_signature(&mut self, signature: P<Signature>, node: P<Node>) -> Option<P<Type>> {
        todo!()
    }

    // jsx.go:932
    pub(crate) fn get_jsx_props_type_from_call_signature(&mut self, sig: P<Signature>, context: P<Node>) -> Option<P<Type>> {
        todo!()
    }

    // jsx.go:942
    pub(crate) fn get_jsx_props_type_from_class_type(&mut self, sig: P<Signature>, context: P<Node>) -> Option<P<Type>> {
        todo!()
    }

    // jsx.go:989
    pub(crate) fn get_jsx_props_type_for_signature_from_member(&mut self, sig: P<Signature>, forced_lookup_location: &str) -> Option<P<Type>> {
        todo!()
    }

    // jsx.go:1018
    pub(crate) fn get_jsx_managed_attributes_from_located_attributes(&mut self, context: P<Node>, ns: P<Symbol>, attributes_type: P<Type>) -> P<Type> {
        todo!()
    }

    // jsx.go:1030
    pub(crate) fn instantiate_alias_or_interface_with_defaults(&mut self, managed_sym: P<Symbol>, type_arguments: &[P<Type>], in_java_script: bool) -> Option<P<Type>> {
        todo!()
    }

    // jsx.go:1050
    pub(crate) fn get_jsx_library_managed_attributes(&mut self, jsx_namespace: Option<P<Symbol>>) -> Option<P<Symbol>> {
        todo!()
    }

    // jsx.go:1057
    pub(crate) fn get_jsx_element_type_symbol(&mut self, jsx_namespace: Option<P<Symbol>>) -> Option<P<Symbol>> {
        todo!()
    }

    // jsx.go:1073
    pub(crate) fn get_jsx_element_properties_name(&mut self, jsx_namespace: P<Symbol>) -> String {
        todo!()
    }

    // jsx.go:1077
    pub(crate) fn get_jsx_element_children_property_name(&mut self, jsx_namespace: P<Symbol>) -> String {
        todo!()
    }

    // jsx.go:1091
    pub(crate) fn get_name_from_jsx_element_attributes_container(&mut self, name_of_attrib_prop_container: &str, jsx_namespace: Option<P<Symbol>>) -> String {
        todo!()
    }

    // jsx.go:1114
    pub(crate) fn get_static_type_of_referenced_jsx_constructor(&mut self, context: P<Node>) -> P<Type> {
        todo!()
    }

    // jsx.go:1135
    pub(crate) fn get_intrinsic_attributes_type_from_string_literal_type(&mut self, t: P<Type>, location: P<Node>) -> Option<P<Type>> {
        todo!()
    }

    // jsx.go:1157
    pub(crate) fn get_jsx_reference_kind(&mut self, node: P<Node>) -> JsxReferenceKind {
        todo!()
    }

    // jsx.go:1171
    pub(crate) fn create_signature_for_jsx_intrinsic(&mut self, node: P<Node>, result: P<Type>) -> P<Signature> {
        todo!()
    }

    // jsx.go:1188
    pub(crate) fn get_intrinsic_attributes_type_from_jsx_opening_like_element(&mut self, node: P<Node>) -> Option<P<Type>> {
        todo!()
    }

    // jsx.go:1214
    pub(crate) fn get_intrinsic_tag_symbol(&mut self, node: P<Node>) -> Option<P<Symbol>> {
        todo!()
    }

    // jsx.go:1257
    pub(crate) fn get_jsx_stateless_element_type_at(&mut self, location: P<Node>) -> Option<P<Type>> {
        todo!()
    }

    // jsx.go:1265
    pub(crate) fn get_jsx_element_class_type_at(&mut self, location: P<Node>) -> Option<P<Type>> {
        todo!()
    }

    // jsx.go:1273
    pub(crate) fn get_jsx_element_type_at(&mut self, location: P<Node>) -> P<Type> {
        todo!()
    }

    // jsx.go:1277
    pub(crate) fn get_jsx_element_type_type_at(&mut self, location: P<Node>) -> Option<P<Type>> {
        todo!()
    }

    // jsx.go:1293
    pub(crate) fn get_jsx_type(&mut self, name: &str, location: P<Node>) -> P<Type> {
        todo!()
    }

    // jsx.go:1304
    pub(crate) fn get_jsx_namespace_at(&mut self, location: Option<P<Node>>) -> Option<P<Symbol>> {
        todo!()
    }

    // jsx.go:1339
    pub(crate) fn get_jsx_namespace(&mut self, location: Option<P<Node>>) -> String {
        todo!()
    }

    // jsx.go:1388
    pub(crate) fn get_local_jsx_namespace(&mut self, file: P<SourceFile>) -> String {
        todo!()
    }

    // jsx.go:1404
    pub(crate) fn get_jsx_factory_entity(&mut self, location: Option<P<Node>>) -> Option<P<Node>> {
        todo!()
    }

    // jsx.go:1414
    pub(crate) fn get_jsx_fragment_factory_entity(&mut self, location: Option<P<Node>>) -> Option<P<Node>> {
        todo!()
    }

    // jsx.go:1435
    pub(crate) fn parse_isolated_entity_name(&mut self, name: &str) -> P<Node> {
        todo!()
    }
}

// jsx.go:1443
pub(crate) fn mark_as_synthetic(node: P<Node>) -> bool {
    todo!()
}

impl Checker {
    // jsx.go:1449
    pub(crate) fn get_jsx_namespace_container_for_implicit_import(&mut self, location: P<Node>) -> Option<P<Symbol>> {
        todo!()
    }

    // jsx.go:1486
    pub(crate) fn get_jsx_runtime_import_specifier(&mut self, file: P<SourceFile>) -> (String, P<Node>) {
        todo!()
    }
}
