//! Port of `internal/checker` (and `internal/evaluator`). See docs/CHECKER.md.
//!
//! Every module does `use crate::*;`, which brings the data model and the common imports below into scope.

// Common imports for all checker modules.
pub(crate) use std::cell::{Cell, RefCell};

pub(crate) use rustc_hash::{FxHashMap, FxHashSet};
pub(crate) use tsrs_ast as ast;
pub(crate) use tsrs_ast::{CheckFlags, Diagnostic, FlowNode, Kind, ModifierFlags, Node, NodeFlags, NodeId, SourceFile, Symbol, SymbolFlags, SymbolId, SymbolTable};
pub(crate) use tsrs_binder::{NameResolver, ReferenceResolver};
pub(crate) use tsrs_core::collections::{OrderedMap, OrderedSet, Set};
pub(crate) use tsrs_core::jsnum::{self, Number, PseudoBigInt};
pub(crate) use tsrs_core::{alloc, alloc_slice, alloc_str, alloc_vec, CompilerOptions, ModuleKind, ModuleResolutionKind, ResolutionMode, ScriptTarget, Tristate, P};
pub(crate) use tsrs_diagnostics::{self as diagnostics, Message};
pub(crate) use tsrs_module::ResolvedModule;
pub(crate) use tsrs_scanner::Scanner;
pub(crate) use tsrs_pseudochecker as pseudochecker;
pub(crate) use tsrs_modulespecifiers as modulespecifiers;
pub(crate) use tsrs_modulespecifiers::ModuleSpecifierGenerationHost;
pub(crate) use tsrs_pseudochecker::{new_pseudo_checker, PseudoChecker, PseudoParameter, PseudoType};

// Data model (checker-foundation).
pub mod workcensus;
pub mod checker;
pub mod evaluator;
pub mod flow_types;
pub mod inference_types;
pub mod jsx_types;
pub mod links;
pub mod mapper;
pub mod nodebuilder_types;
pub mod printer_types;
pub mod program;
pub mod relater_types;
pub mod types;
pub mod utilities_types;

pub use checker::*;
pub use flow_types::*;
pub use inference_types::*;
pub use jsx_types::*;
pub use links::*;
pub use mapper::*;
pub use nodebuilder_types::*;
pub use printer_types::*;
pub use program::*;
pub use relater_types::*;
pub use types::*;
pub use utilities_types::*;

// Function bodies (stubs generated by tools/gosig, filled in by the body-porting agents).
mod checker_01;
pub(crate) use checker_01::*;
mod checker_02;
mod checker_03;
pub(crate) use checker_03::*;
mod checker_04;
mod checker_05;
mod checker_06;
mod checker_07;
pub(crate) use checker_07::*;
mod checker_08;
pub(crate) use checker_08::*;
mod checker_09;
pub(crate) use checker_09::*;
mod checker_10;
pub(crate) use checker_10::*;
mod checker_11;
pub(crate) use checker_11::*;
mod checker_12;
pub(crate) use checker_12::*;
mod checker_13;
pub(crate) use checker_13::*;
mod checker_14;
pub(crate) use checker_14::*;
mod checker_15;
pub(crate) use checker_15::*;
mod relater_1;
pub(crate) use relater_1::*;
mod relater_2;
mod relater_derived;
mod unioncache;
mod flow;
pub(crate) use flow::*;
pub mod flowmemo;
mod inference;
pub(crate) use inference::*;
mod grammarchecks;
pub(crate) use grammarchecks::*;
mod utilities;
pub(crate) use utilities::*;
pub use utilities::new_diagnostic_for_node;
mod jsx;
mod exports;
mod jsdoc;
mod printer;
pub(crate) use printer::*;
mod nodebuilder;
mod nodebuilderimpl_1;
pub(crate) use nodebuilderimpl_1::*;
mod nodebuilderimpl_2;
pub(crate) use nodebuilderimpl_2::*;
mod nodebuilderscopes;
mod nodecopy;
mod pseudotypenodebuilder;
mod emitresolver;
pub(crate) use emitresolver::*;
mod nodebuilder_hover;
pub(crate) use nodebuilder_hover::*;
mod services;
pub use tsrs_astnav as astnav;

// Exported Go package-level functions (the baseline writer, the language service and the project system call them).
pub use exports::{
    get_declaration_modifier_flags_from_symbol_exported, get_property_name_from_type_exported, is_distributed_type_parameter, is_tuple_type_exported,
    is_tuple_type_target, is_type_usable_as_property_name_exported,
};
pub use checker_09::is_non_deferred_type_reference;
pub use checker_14::get_mapped_type_modifiers;
pub use nodebuilder::{new_node_builder, new_node_builder_ex};
pub use nodebuilderimpl_1::try_get_module_specifier_from_declaration;
pub use printer::new_symbol_tracker_impl;
pub use services::get_resolved_signature_for_signature_help;
pub use utilities::{
    compare_types, create_mode_mismatch_details, create_module_not_found_chain, get_set_accessor_value_parameter, get_single_variable_of_variable_statement,
    is_external_module_symbol, is_in_type_query, is_known_symbol, is_private_identifier_symbol, is_type_any, new_diagnostic_chain_for_node, skip_alias,
    value_to_string,
};
