//! Port of `internal/checker` (and `internal/evaluator`). See docs/CHECKER.md.
//!
//! Every module does `use crate::*;`, which brings the data model and the common imports below into scope.

// Common imports for all checker modules.
pub(crate) use std::cell::{Cell, RefCell};

pub(crate) use rustc_hash::{FxHashMap, FxHashSet};
pub(crate) use tsrs_ast as ast;
pub(crate) use tsrs_ast::{CheckFlags, Diagnostic, FlowNode, Kind, ModifierFlags, Node, NodeFlags, NodeId, SourceFile, Symbol, SymbolFlags, SymbolId, SymbolTable};
pub(crate) use tsrs_binder::NameResolver;
pub(crate) use tsrs_core::collections::{OrderedMap, OrderedSet, Set};
pub(crate) use tsrs_core::jsnum::{self, Number, PseudoBigInt};
pub(crate) use tsrs_core::tspath::Path;
pub(crate) use tsrs_core::{alloc, alloc_slice, alloc_str, alloc_vec, CompilerOptions, ModuleKind, ModuleResolutionKind, ResolutionMode, ScriptTarget, Tristate, P};
pub(crate) use tsrs_diagnostics::{self as diagnostics, Message};
pub(crate) use tsrs_module::ResolvedModule;
pub(crate) use tsrs_scanner::Scanner;

// Data model (checker-foundation).
pub mod checker;
pub mod evaluator;
pub mod flow_types;
pub mod inference_types;
pub mod jsx_types;
pub mod links;
pub mod mapper;
pub mod program;
pub mod relater_types;
pub mod types;
pub mod utilities_types;

pub use checker::*;
pub use flow_types::*;
pub use inference_types::*;
pub use jsx_types::*;
pub use links::*;
pub use mapper::*;
pub use program::*;
pub use relater_types::*;
pub use types::*;
pub use utilities_types::*;

// Function bodies (stubs generated by tools/gosig, filled in by the body-porting agents).
