//! Port of `internal/checker` (and `internal/evaluator`). See docs/CHECKER.md.
//!
//! Every module does `use crate::*;`, which brings the data model and the common imports below into scope.

// Common imports for all checker modules.
pub(crate) use std::cell::{Cell, RefCell};

pub(crate) use rustc_hash::{FxHashMap, FxHashSet};
pub(crate) use tsrs_ast as ast;
pub(crate) use tsrs_ast::{CheckFlags, Diagnostic, FlowNode, Kind, ModifierFlags, Node, NodeFlags, NodeId, SourceFile, Symbol, SymbolFlags, SymbolId, SymbolTable};
pub(crate) use tsrs_binder::NameResolver;
pub(crate) use tsrs_core::collections::{OrderedMap, OrderedSet, Set};
pub(crate) use tsrs_core::jsnum::{self, Number, PseudoBigInt};
pub(crate) use tsrs_core::tspath::Path;
pub(crate) use tsrs_core::{alloc, alloc_slice, alloc_str, alloc_vec, CompilerOptions, ModuleKind, ModuleResolutionKind, ResolutionMode, ScriptTarget, Tristate, P};
pub(crate) use tsrs_diagnostics::{self as diagnostics, Message};
pub(crate) use tsrs_module::ResolvedModule;
pub(crate) use tsrs_scanner::Scanner;
pub(crate) use tsrs_pseudochecker as pseudochecker;
pub(crate) use tsrs_pseudochecker::{new_pseudo_checker, PseudoChecker, PseudoObjectElement, PseudoParameter, PseudoType};

// Data model (checker-foundation).
pub mod checker;
pub mod evaluator;
pub mod flow_types;
pub mod inference_types;
pub mod jsx_types;
pub mod links;
pub mod mapper;
pub mod nodebuilder_types;
pub mod printer_types;
mod printer_standin;
pub mod program;
pub mod relater_types;
pub mod types;
pub mod utilities_types;

pub use checker::*;
pub use flow_types::*;
pub use inference_types::*;
pub use jsx_types::*;
pub use links::*;
pub use mapper::*;
pub use nodebuilder_types::*;
pub use printer_types::*;
pub use program::*;
pub use relater_types::*;
pub use types::*;
pub use utilities_types::*;

// Function bodies (stubs generated by tools/gosig, filled in by the body-porting agents).
mod checker_01;
pub(crate) use checker_01::*;
mod checker_02;
pub(crate) use checker_02::*;
mod checker_03;
pub(crate) use checker_03::*;
mod checker_04;
pub(crate) use checker_04::*;
mod checker_05;
pub(crate) use checker_05::*;
mod checker_06;
pub(crate) use checker_06::*;
mod checker_07;
pub(crate) use checker_07::*;
mod checker_08;
pub(crate) use checker_08::*;
mod checker_09;
pub(crate) use checker_09::*;
mod checker_10;
pub(crate) use checker_10::*;
mod checker_11;
pub(crate) use checker_11::*;
mod checker_12;
pub(crate) use checker_12::*;
mod checker_13;
pub(crate) use checker_13::*;
mod checker_14;
pub(crate) use checker_14::*;
mod checker_15;
pub(crate) use checker_15::*;
mod relater_1;
pub(crate) use relater_1::*;
mod relater_2;
pub(crate) use relater_2::*;
mod flow;
pub(crate) use flow::*;
mod inference;
pub(crate) use inference::*;
mod grammarchecks;
pub(crate) use grammarchecks::*;
mod utilities;
pub(crate) use utilities::*;
mod jsx;
pub(crate) use jsx::*;
mod exports;
pub(crate) use exports::*;
mod jsdoc;
pub(crate) use jsdoc::*;
mod printer;
pub(crate) use printer::*;
mod nodebuilder;
pub(crate) use nodebuilder::*;
mod nodebuilderimpl_1;
pub(crate) use nodebuilderimpl_1::*;
mod nodebuilderimpl_2;
pub(crate) use nodebuilderimpl_2::*;
mod nodebuilderscopes;
pub(crate) use nodebuilderscopes::*;
