use crate::*;
use tsrs_ast::*;
use tsrs_core::*;
use tsrs_ast as ast;
use tsrs_diagnostics as diagnostics;
use tsrs_diagnostics::Message;
use rustc_hash::FxHashMap;
use std::fmt::Display;
use std::rc::Rc;

// Stubs generated by tools/gosig. Keep the signatures; replace the todo!() bodies.

// Non-function declarations in nodebuilderimpl.go:1-1850 (hand-ported by printer-foundation in nodebuilder_types.rs):
//   type CompositeSymbolIdentity (nodebuilderimpl.go:24)
//   type TrackedSymbolArgs (nodebuilderimpl.go:30)
//   type SerializedTypeEntry (nodebuilderimpl.go:36)
//   type CompositeTypeCacheIdentity (nodebuilderimpl.go:43)
//   type NodeBuilderLinks (nodebuilderimpl.go:49)
//   type NodeBuilderSymbolLinks (nodebuilderimpl.go:54)
//   type moduleSpecifierResult (nodebuilderimpl.go:58)
//   type NodeBuilderContext (nodebuilderimpl.go:63)
//   type NodeBuilderImpl (nodebuilderimpl.go:97)
//   const (nodebuilderimpl.go:118): defaultMaximumTruncationLength, noTruncationMaximumTruncationLength
//   type sortedSymbolNamePair (nodebuilderimpl.go:1081)

// nodebuilderimpl.go:125
pub(crate) fn new_node_builder_impl(ch: &mut Checker, e: P<EmitContext>, id_to_symbol: Option<&FxHashMap<P<Node>, P<Symbol>>>) -> P<NodeBuilderImpl> {
    // Go shares the caller's map (language service inlay hints read it back); the checker never passes one.
    let id_to_symbol = match id_to_symbol {
        Some(id_to_symbol) => id_to_symbol.clone(),
        None => FxHashMap::default(),
    };
    let b = P::new(NodeBuilderImpl {
        f: e.factory.as_node_factory().clone(),
        e,
        pc: new_pseudo_checker(ch.strict_null_checks, ch.exact_optional_property_types),
        links: Default::default(),
        symbol_links: Default::default(),
        ctx: Cell::new(None),
        clone_binding_name_visitor: std::cell::OnceCell::new(),
        id_to_symbol: RefCell::new(id_to_symbol),
        checker_slot: P::new(CheckerSlot::default()),
        this: std::cell::OnceCell::new(),
    });
    let _ = b.this.set(b);
    // Go: b.cloneBindingNameVisitor = ast.NewNodeVisitor(b.cloneBindingName, b.f, ast.NodeVisitorHooks{})
    let slot = b.checker_slot;
    let visit: VisitFn = Rc::new(move |_v: &mut NodeVisitor, node: P<Node>| slot.with(|c| b.clone_binding_name(c, node)));
    let _ = b.clone_binding_name_visitor.set(visit);
    b
}

impl NodeBuilderImpl {
    // nodebuilderimpl.go:134
    pub(crate) fn save_restore_flags(&self, c: &mut Checker) -> Box<dyn FnMut(&mut Checker)> {
        todo!()
    }

    // nodebuilderimpl.go:146
    pub(crate) fn check_truncation_length(&self, c: &mut Checker) -> bool {
        todo!()
    }

    // nodebuilderimpl.go:164
    pub(crate) fn check_truncation_length_if_expanding(&self, c: &mut Checker) -> bool {
        todo!()
    }

    // nodebuilderimpl.go:175
    pub(crate) fn is_expandable_type(&self, c: &mut Checker, t: P<Type>, is_alias: bool) -> bool {
        todo!()
    }

    // nodebuilderimpl.go:197
    pub(crate) fn is_type_on_stack(&self, c: &mut Checker, t: P<Type>) -> bool {
        todo!()
    }

    // nodebuilderimpl.go:212
    pub(crate) fn should_expand_type(&self, c: &mut Checker, t: P<Type>, is_alias: bool) -> bool {
        todo!()
    }

    // nodebuilderimpl.go:231
    pub(crate) fn is_actively_expanding(&self, c: &mut Checker) -> bool {
        todo!()
    }

    // nodebuilderimpl.go:239
    pub(crate) fn check_type_expandability(&self, c: &mut Checker, t: Option<P<Type>>) {
        todo!()
    }

    // nodebuilderimpl.go:272
    pub(crate) fn append_reference_to_type(&self, c: &mut Checker, root: P<Node>, ref_: P<Node>) -> Option<P<Node>> {
        todo!()
    }
}

// nodebuilderimpl.go:325
pub(crate) fn get_access_stack(ref_: P<Node>) -> Vec<P<Node>> {
    todo!()
}

// nodebuilderimpl.go:337
pub(crate) fn is_class_instance_side(c: &mut Checker, t: P<Type>) -> bool {
    todo!()
}

impl NodeBuilderImpl {
    // nodebuilderimpl.go:341
    pub(crate) fn create_elided_information_placeholder(&self, c: &mut Checker) -> P<Node> {
        todo!()
    }

    // nodebuilderimpl.go:349
    pub(crate) fn map_to_type_nodes(&self, c: &mut Checker, list: &[P<Type>], is_bare_list: bool) -> Option<P<NodeList>> {
        todo!()
    }

    // nodebuilderimpl.go:442
    pub(crate) fn serialize_type_name(&self, c: &mut Checker, node: P<Node>, is_type_of: bool, type_arguments: P<NodeList>) -> Option<P<Node>> {
        todo!()
    }
}

// nodebuilderimpl.go:463
pub(crate) fn is_identifier_type_reference(node: P<Node>) -> bool {
    todo!()
}

// nodebuilderimpl.go:467
pub(crate) fn array_is_homogeneous<T>(array: &[T], comparer: impl FnMut(T, T) -> bool) -> bool {
    todo!()
}

// nodebuilderimpl.go:481
pub(crate) fn types_are_same_reference(a: P<Type>, b: P<Type>) -> bool {
    todo!()
}

impl NodeBuilderImpl {
    // nodebuilderimpl.go:485
    pub(crate) fn set_comment_range(&self, c: &mut Checker, node: P<Node>, range_: Option<P<Node>>) {
        todo!()
    }

    // nodebuilderimpl.go:492
    pub(crate) fn type_node_is_equivalent_to_type(&self, c: &mut Checker, annotated_declaration: Option<P<Node>>, t: P<Type>, type_from_type_node: P<Type>) -> bool {
        todo!()
    }

    // nodebuilderimpl.go:507
    pub(crate) fn can_reuse_existing_js_type_node(&self, c: &mut Checker, existing: P<Node>, t: P<Type>) -> bool {
        todo!()
    }

    // nodebuilderimpl.go:511
    pub(crate) fn try_get_resolved_symbol_from_type_node(&self, c: &mut Checker, node: P<Node>) -> Option<P<Symbol>> {
        todo!()
    }

    // nodebuilderimpl.go:524
    pub(crate) fn existing_type_node_is_not_reference_or_is_reference_with_compatible_type_argument_count(&self, c: &mut Checker, existing: P<Node>, t: P<Type>) -> bool {
        todo!()
    }

    // nodebuilderimpl.go:548
    pub(crate) fn try_reuse_existing_non_parameter_type_node(&self, c: &mut Checker, existing: P<Node>, t: P<Type>, host: Option<P<Node>>, annotation_type: Option<P<Type>>) -> Option<P<Node>> {
        todo!()
    }

    // nodebuilderimpl.go:564
    pub(crate) fn get_resolved_type_without_abstract_construct_signatures(&self, c: &mut Checker, t: &'static StructuredType) -> P<Type> {
        todo!()
    }

    // nodebuilderimpl.go:584
    pub(crate) fn symbol_to_node(&self, c: &mut Checker, symbol: P<Symbol>, meaning: SymbolFlags) -> P<Node> {
        todo!()
    }

    // nodebuilderimpl.go:606
    pub(crate) fn symbol_to_name(&self, c: &mut Checker, symbol: P<Symbol>, meaning: SymbolFlags, expects_identifier: bool) -> P<Node> {
        todo!()
    }

    // nodebuilderimpl.go:614
    pub(crate) fn create_entity_name_from_symbol_chain(&self, c: &mut Checker, chain: &[P<Symbol>], index: i32) -> P<Node> {
        todo!()
    }

    // nodebuilderimpl.go:642
    pub(crate) fn symbol_to_entity_name_node(&self, c: &mut Checker, symbol: P<Symbol>) -> P<Node> {
        todo!()
    }

    // nodebuilderimpl.go:650
    pub(crate) fn symbol_to_type_node(&self, c: &mut Checker, symbol: P<Symbol>, mask: SymbolFlags, type_arguments: Option<P<NodeList>>) -> Option<P<Node>> {
        todo!()
    }
}

// nodebuilderimpl.go:745
pub(crate) fn get_topmost_indexed_access_type(node: P<Node>) -> P<Node> {
    todo!()
}

impl NodeBuilderImpl {
    // nodebuilderimpl.go:752
    pub(crate) fn create_access_from_symbol_chain(&self, c: &mut Checker, chain: &[P<Symbol>], index: i32, stopper: i32, override_type_arguments: Option<P<NodeList>>) -> P<Node> {
        todo!()
    }

    // nodebuilderimpl.go:848
    pub(crate) fn symbol_to_expression(&self, c: &mut Checker, symbol: P<Symbol>, mask: SymbolFlags) -> P<Node> {
        todo!()
    }

    // nodebuilderimpl.go:853
    pub(crate) fn symbol_to_expression_worker(&self, c: &mut Checker, symbol: P<Symbol>, mask: SymbolFlags) -> P<Node> {
        todo!()
    }

    // nodebuilderimpl.go:858
    pub(crate) fn create_expression_from_symbol_chain(&self, c: &mut Checker, chain: &[P<Symbol>], index: i32) -> P<Node> {
        todo!()
    }
}

// nodebuilderimpl.go:912
pub(crate) fn can_use_property_access(name: &str) -> bool {
    todo!()
}

// nodebuilderimpl.go:924
pub(crate) fn starts_with_single_or_double_quote(str: &str) -> bool {
    todo!()
}

// nodebuilderimpl.go:928
pub(crate) fn starts_with_square_bracket(str: &str) -> bool {
    todo!()
}

// nodebuilderimpl.go:932
pub(crate) fn is_default_binding_context(location: P<Node>) -> bool {
    todo!()
}

impl NodeBuilderImpl {
    // nodebuilderimpl.go:936
    pub(crate) fn get_name_of_symbol_from_name_type(&self, c: &mut Checker, symbol: P<Symbol>) -> String {
        todo!()
    }

    // nodebuilderimpl.go:973
    pub(crate) fn get_name_of_symbol_as_written(&self, c: &mut Checker, symbol: P<Symbol>) -> String {
        todo!()
    }

    // nodebuilderimpl.go:1029
    pub(crate) fn get_type_parameters_of_class_or_interface(&self, c: &mut Checker, symbol: P<Symbol>) -> Vec<P<Type>> {
        todo!()
    }

    // nodebuilderimpl.go:1036
    pub(crate) fn lookup_type_parameter_nodes(&self, c: &mut Checker, chain: &[P<Symbol>], index: i32) -> Option<P<NodeList>> {
        todo!()
    }

    // nodebuilderimpl.go:1061
    pub(crate) fn lookup_symbol_chain(&self, c: &mut Checker, symbol: P<Symbol>, meaning: SymbolFlags, yield_module_symbol: bool) -> Vec<P<Symbol>> {
        todo!()
    }

    // nodebuilderimpl.go:1066
    pub(crate) fn lookup_symbol_chain_worker(&self, c: &mut Checker, symbol: P<Symbol>, meaning: SymbolFlags, yield_module_symbol: bool) -> Vec<P<Symbol>> {
        todo!()
    }

    // nodebuilderimpl.go:1087
    pub(crate) fn get_symbol_chain(&self, c: &mut Checker, symbol: P<Symbol>, meaning: SymbolFlags, end_of_chain: bool, yield_module_symbol: bool) -> Vec<P<Symbol>> {
        todo!()
    }

    // nodebuilderimpl.go:1153
    pub(crate) fn sort_by_best_name(&self, c: &mut Checker, a: sortedSymbolNamePair, b: sortedSymbolNamePair) -> i32 {
        todo!()
    }
}

// nodebuilderimpl.go:1172
pub(crate) fn can_have_module_specifier(node: Option<P<Node>>) -> bool {
    todo!()
}

// nodebuilderimpl.go:1193
pub fn try_get_module_specifier_from_declaration(node: P<Node>) -> Option<P<Node>> {
    todo!()
}

// nodebuilderimpl.go:1201
pub(crate) fn try_get_module_specifier_from_declaration_worker(node: P<Node>) -> Option<P<Node>> {
    todo!()
}

impl NodeBuilderImpl {
    // nodebuilderimpl.go:1249
    pub(crate) fn get_specifier_for_module_symbol(&self, c: &mut Checker, symbol: P<Symbol>, override_import_mode: ModuleKind) -> moduleSpecifierResult {
        todo!()
    }

    // nodebuilderimpl.go:1340
    pub(crate) fn module_specifier_result_for_symbol(&self, c: &mut Checker, result: moduleSpecifierResult, import_attributes_type: Option<P<Type>>, symbol: P<Symbol>) -> moduleSpecifierResult {
        todo!()
    }

    // nodebuilderimpl.go:1347
    pub(crate) fn module_specifier_resolves_to_symbol(&self, c: &mut Checker, specifier: &str, import_attributes_type: P<Type>, symbol: P<Symbol>) -> bool {
        todo!()
    }

    // nodebuilderimpl.go:1359
    pub(crate) fn create_import_attributes_for_module_specifier(&self, c: &mut Checker, result: moduleSpecifierResult, import_mode_override: ModuleKind) -> Option<P<Node>> {
        todo!()
    }

    // nodebuilderimpl.go:1401
    pub(crate) fn type_parameter_to_declaration_with_constraint(&self, c: &mut Checker, type_parameter: P<Type>, constraint_node: Option<P<Node>>) -> P<Node> {
        todo!()
    }

    // nodebuilderimpl.go:1434
    pub(crate) fn set_text_range(&self, c: &mut Checker, range_: P<Node>, location: Option<P<Node>>) -> Option<P<Node>> {
        todo!()
    }

    // nodebuilderimpl.go:1468
    pub(crate) fn type_parameter_shadows_other_type_parameter_in_scope(&self, c: &mut Checker, name: &str, type_parameter: P<Type>) -> bool {
        todo!()
    }

    // nodebuilderimpl.go:1476
    pub(crate) fn type_parameter_to_name(&self, c: &mut Checker, type_parameter: P<Type>) -> P<Node> {
        todo!()
    }

    // nodebuilderimpl.go:1522
    pub(crate) fn is_mapped_type_homomorphic(&self, c: &mut Checker, mapped: P<Type>) -> bool {
        todo!()
    }

    // nodebuilderimpl.go:1526
    pub(crate) fn is_homomorphic_mapped_type_with_non_homomorphic_instantiation(&self, c: &mut Checker, mapped: &'static MappedType) -> bool {
        todo!()
    }

    // nodebuilderimpl.go:1530
    pub(crate) fn create_mapped_type_node_from_type(&self, c: &mut Checker, t: P<Type>) -> P<Node> {
        todo!()
    }

    // nodebuilderimpl.go:1646
    pub(crate) fn type_predicate_to_type_predicate_node(&self, c: &mut Checker, predicate: P<TypePredicate>) -> P<Node> {
        todo!()
    }

    // nodebuilderimpl.go:1669
    pub(crate) fn type_to_type_node_helper_with_possible_reusable_type_node(&self, c: &mut Checker, t: Option<P<Type>>, type_node: Option<P<Node>>) -> Option<P<Node>> {
        todo!()
    }

    // nodebuilderimpl.go:1683
    pub(crate) fn type_parameter_to_declaration(&self, c: &mut Checker, parameter: P<Type>) -> P<Node> {
        todo!()
    }

    // nodebuilderimpl.go:1692
    pub(crate) fn symbol_to_type_parameter_declarations(&self, c: &mut Checker, symbol: P<Symbol>) -> Vec<P<Node>> {
        todo!()
    }

    // nodebuilderimpl.go:1696
    pub(crate) fn type_parameters_to_type_parameter_declarations(&self, c: &mut Checker, symbol: P<Symbol>) -> Vec<P<Node>> {
        todo!()
    }
}

// nodebuilderimpl.go:1715
pub(crate) fn get_effective_parameter_declaration(symbol: P<Symbol>) -> Option<P<Node>> {
    todo!()
}

impl NodeBuilderImpl {
    // nodebuilderimpl.go:1726
    pub(crate) fn symbol_to_parameter_declaration(&self, c: &mut Checker, parameter_symbol: P<Symbol>, preserve_modifier_flags: bool) -> P<Node> {
        todo!()
    }

    // nodebuilderimpl.go:1763
    pub(crate) fn parameter_to_parameter_declaration_name(&self, c: &mut Checker, parameter_symbol: P<Symbol>, parameter_declaration: Option<P<Node>>) -> Option<P<Node>> {
        todo!()
    }

    // nodebuilderimpl.go:1785
    pub(crate) fn clone_binding_name(&self, c: &mut Checker, node: P<Node>) -> Option<P<Node>> {
        todo!()
    }

    // nodebuilderimpl.go:1811
    pub(crate) fn serialize_type_for_expression(&self, c: &mut Checker, expr: P<Node>) -> Option<P<Node>> {
        todo!()
    }

    // nodebuilderimpl.go:1817
    pub(crate) fn serialize_inferred_return_type_for_signature(&self, c: &mut Checker, signature: P<Signature>, return_type: P<Type>) -> Option<P<Node>> {
        todo!()
    }

    // nodebuilderimpl.go:1837
    pub(crate) fn type_predicate_to_type_predicate_node_helper(&self, c: &mut Checker, type_predicate: P<TypePredicate>) -> P<Node> {
        todo!()
    }
}
