[package]
name = "tsrs_cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
tsrs_core.workspace = true
tsrs_diagnostics.workspace = true
tsrs_ast.workspace = true
tsrs_scanner.workspace = true
tsrs_parser.workspace = true
tsrs_binder.workspace = true
tsrs_vfs.workspace = true
tsrs_module.workspace = true
tsrs_tsoptions.workspace = true
tsrs_compiler = { path = "../tsrs_compiler", default-features = false }
rustc-hash.workspace = true
mimalloc = "0.1.52"
[features]
default = ["checker"]
checker = ["tsrs_compiler/checker"]

[[bin]]
name = "tsrs"
path = "src/main.rs"
