// tsrs-oracle-lsproto exercises the Go lsproto JSON codecs for the tsrs_lsproto differential test
// (tools/oracle/lsproto/run.sh).
//
//	gen <seed> <perType>  prints "Type\tJSON" lines: random values of every protocol type, marshaled.
//	filename              reads DocumentUris and prints "uri\tFileName()" lines.
//	check                 reads "Type\tJSON" lines and prints, per line, "OK <re-marshaled JSON>" or
//	                      "ERR <error>" (json.Unmarshal into a new value, then json.Marshal).
//
// The type registry (registry_gen.go) is generated by run.sh from lsp_generated.go.
package main

import (
	"bufio"
	"fmt"
	"math/rand/v2"
	"os"
	"reflect"
	"strconv"
	"strings"

	"github.com/microsoft/TypeScript/tsc/internal/json"
	"github.com/microsoft/TypeScript/tsc/internal/lsp/lsproto"
)

func main() {
	switch os.Args[1] {
	case "gen":
		seed, _ := strconv.Atoi(os.Args[2])
		perType, _ := strconv.Atoi(os.Args[3])
		gen(uint64(seed), perType)
	case "check":
		check()
	case "filename":
		filename()
	}
}

// filename reads one DocumentUri per line and prints its FileName() (or the panic).
func filename() {
	sc := bufio.NewScanner(os.Stdin)
	w := bufio.NewWriter(os.Stdout)
	defer w.Flush()
	for sc.Scan() {
		uri := lsproto.DocumentUri(sc.Text())
		fmt.Fprintf(w, "%s\t%s\n", uri, fileNameOrPanic(uri))
	}
}

func fileNameOrPanic(uri lsproto.DocumentUri) (out string) {
	defer func() {
		if r := recover(); r != nil {
			out = fmt.Sprintf("PANIC %v", r)
		}
	}()
	return uri.FileName()
}

func check() {
	sc := bufio.NewScanner(os.Stdin)
	sc.Buffer(make([]byte, 1<<20), 1<<28)
	w := bufio.NewWriter(os.Stdout)
	defer w.Flush()
	for sc.Scan() {
		name, input, _ := strings.Cut(sc.Text(), "\t")
		mk, ok := registry[name]
		if !ok {
			fmt.Fprintf(w, "NOTYPE %s\n", name)
			continue
		}
		v := mk()
		if err := json.Unmarshal([]byte(input), v); err != nil {
			fmt.Fprintf(w, "ERR %s\n", strings.ReplaceAll(err.Error(), "\n", "\\n"))
			continue
		}
		out, err := marshal(v)
		if err != nil {
			fmt.Fprintf(w, "MERR %s\n", err)
			continue
		}
		fmt.Fprintf(w, "OK %s\n", out)
	}
}

func marshal(v any) (out []byte, err error) {
	defer func() {
		if r := recover(); r != nil {
			err = fmt.Errorf("panic: %v", r)
		}
	}()
	return json.Marshal(v, json.Deterministic(true))
}

const maxDepth = 4

type generator struct {
	r *rand.Rand
}

func gen(seed uint64, perType int) {
	g := &generator{r: rand.New(rand.NewPCG(seed, seed^0x9e3779b97f4a7c15))}
	w := bufio.NewWriter(os.Stdout)
	defer w.Flush()
	for _, name := range registryNames {
		for range perType {
			v := registry[name]()
			g.fill(reflect.ValueOf(v).Elem(), 0)
			out, err := marshal(v)
			if err != nil {
				continue
			}
			fmt.Fprintf(w, "%s\t%s\n", name, out)
		}
	}
}

var (
	jsonMarshalerTo = reflect.TypeFor[json.MarshalerTo]()
	registration    = reflect.TypeFor[lsproto.Registration]()
)

func isUnion(t reflect.Type) bool {
	if t.Kind() != reflect.Struct || t.NumField() == 0 || t == registration {
		return false
	}
	if !reflect.PointerTo(t).Implements(jsonMarshalerTo) {
		return false
	}
	for i := range t.NumField() {
		if t.Field(i).Type.Kind() != reflect.Pointer {
			return false
		}
	}
	return true
}

var words = []string{"", "a", "file:///a.ts", "x y", "kind", "begin", "é😀", "\"q\"", "markdown", "plaintext", "refactor.extract"}

func (g *generator) fill(v reflect.Value, depth int) {
	t := v.Type()
	switch t.Kind() {
	case reflect.Struct:
		if t == registration {
			v.FieldByName("Id").SetString(words[g.r.IntN(len(words))])
			opts := reflect.New(t.Field(1).Type.Elem()).Elem()
			for {
				f := opts.Field(g.r.IntN(opts.NumField()))
				f.Set(reflect.New(f.Type().Elem()))
				g.fill(f.Elem(), depth+1)
				break
			}
			v.FieldByName("RegisterOptions").Set(opts.Addr())
			return
		}
		if isUnion(t) {
			if strings.HasSuffix(t.Name(), "OrNull") && g.r.IntN(5) == 0 {
				return
			}
			f := v.Field(g.r.IntN(t.NumField()))
			f.Set(reflect.New(f.Type().Elem()))
			g.fill(f.Elem(), depth+1)
			return
		}
		for i := range t.NumField() {
			sf := t.Field(i)
			if !sf.IsExported() || sf.Tag.Get("json") == "-" {
				continue
			}
			tag := sf.Tag.Get("json")
			optional := strings.Contains(tag, ",omitzero")
			if optional && (depth >= maxDepth || g.r.IntN(3) == 0) {
				continue
			}
			g.fill(v.Field(i), depth+1)
		}
	case reflect.Pointer:
		v.Set(reflect.New(t.Elem()))
		g.fill(v.Elem(), depth)
	case reflect.Slice:
		n := 0
		if depth < maxDepth {
			n = g.r.IntN(3)
		}
		s := reflect.MakeSlice(t, n, n)
		for i := range n {
			g.fill(s.Index(i), depth+1)
		}
		v.Set(s)
	case reflect.Map:
		m := reflect.MakeMap(t)
		if depth < maxDepth {
			for i := range g.r.IntN(3) {
				k := reflect.New(t.Key()).Elem()
				k.SetString(fmt.Sprintf("file:///k%d.ts", i))
				e := reflect.New(t.Elem()).Elem()
				g.fill(e, depth+1)
				m.SetMapIndex(k, e)
			}
		}
		v.Set(m)
	case reflect.Array:
		for i := range v.Len() {
			g.fill(v.Index(i), depth+1)
		}
	case reflect.Interface:
		if a := g.anyValue(depth); a != nil {
			v.Set(reflect.ValueOf(a))
		}
	case reflect.String:
		v.SetString(words[g.r.IntN(len(words))])
	case reflect.Bool:
		v.SetBool(g.r.IntN(2) == 0)
	case reflect.Int32:
		v.SetInt(int64(g.r.IntN(40) - 5))
	case reflect.Uint32:
		v.SetUint(uint64(g.r.IntN(40)))
	case reflect.Uint64:
		v.SetUint(uint64(g.r.IntN(1 << 20)))
	case reflect.Float64:
		v.SetFloat([]float64{0, 1, 1.5, -2.25, 1e21, 123456789.125}[g.r.IntN(6)])
	default:
		panic("unhandled kind " + t.Kind().String())
	}
}

func (g *generator) anyValue(depth int) any {
	switch g.r.IntN(7) {
	case 0:
		return nil
	case 1:
		return float64(g.r.IntN(100)) / 4
	case 2:
		return words[g.r.IntN(len(words))]
	case 3:
		return g.r.IntN(2) == 0
	case 4:
		if depth >= maxDepth {
			return []any{}
		}
		return []any{g.anyValue(depth + 1), g.anyValue(depth + 1)}
	default:
		if depth >= maxDepth {
			return map[string]any{}
		}
		return map[string]any{"a": g.anyValue(depth + 1)}
	}
}
