#!/usr/bin/env python3
"""Compile generated stubs against auto-generated dummy types.

Usage: python3 tools/gosig/check_stubs.py <stub dir> [<scratch dir>]

Copies every generated *.rs in <stub dir> (files with the stub marker, minus the prelude `use` lines) into a throwaway crate,
declares one dummy struct per type name the signatures mention, and runs `cargo check`.
This catches what a parse check cannot: duplicate method names across impl blocks, invalid
`impl Trait` positions, lifetime errors. It says nothing about the real types.
"""
import glob
import os
import re
import subprocess
import sys

KNOWN = {'Option', 'Vec', 'String', 'Box', 'FnMut', 'Fn', 'FnOnce', 'Display', 'FxHashMap', 'Checker',
         'P', 'Self', 'Some', 'None', 'Any', 'Copy', 'Eq', 'Ord', 'Hash', 'Clone'}
SIG = re.compile(r'^\s*(pub(\(crate\))? fn .*)\{$')
IMPL = re.compile(r"^impl(<[^>]*>)? ([A-Za-z_][A-Za-z0-9_]*)(<([^>]*)>)? \{")


def build(stub_dir, scratch, extra):
    files = sorted(f for f in glob.glob(os.path.join(stub_dir, '*.rs'))
                   if 'Stubs generated by tools/gosig' in open(f).read())
    names, holders, traits = {}, set(), set()
    for f in files:
        for line in open(f):
            m = IMPL.match(line)
            if m:
                if m.group(4) and "'" in m.group(4):
                    holders.add(m.group(2))
                elif m.group(2) != 'Checker':
                    names[m.group(2)] = max(names.get(m.group(2), 0), len(m.group(4).split(',')) if m.group(4) else 0)
            m = SIG.match(line)
            if not m:
                continue
            sig = re.sub(r'/\*.*?\*/', '', m.group(1))
            for t in re.findall(r"dyn\s+([A-Z][A-Za-z0-9_]*)", sig):
                if t not in KNOWN:
                    traits.add(t)
            for t in re.findall(r"\b([A-Z][A-Za-z0-9_]*)<'_>", sig):
                holders.add(t)
            for tm in re.finditer(r'\b([A-Z][A-Za-z0-9_]*)\b(\s*<)?', sig):
                n = tm.group(1)
                if n in KNOWN or len(n) == 1:
                    continue
                names[n] = max(names.get(n, 0), 3 if tm.group(2) else 0)
    for e in extra:
        names.setdefault(e, 0)
    for h in holders | traits:
        names.pop(h, None)
    src = os.path.join(scratch, 'src')
    os.makedirs(src, exist_ok=True)
    dummy = ['#![allow(warnings)]', 'use std::marker::PhantomData;', 'pub struct P<T>(PhantomData<T>);',
             'impl<T> Clone for P<T> { fn clone(&self) -> Self { P(PhantomData) } }', 'impl<T> Copy for P<T> {}',
             'pub type FxHashMap<K, V> = std::collections::HashMap<K, V>;', 'pub struct Checker;',
             'pub trait Program {}', 'pub mod evaluator { pub struct Result; }']
    for n, arity in sorted(names.items()):
        if n == 'Program':
            continue
        if arity:
            ps = ', '.join('A%d = ()' % i for i in range(arity))
            us = ', '.join('A%d' % i for i in range(arity))
            dummy.append('pub struct %s<%s>(PhantomData<(%s)>);' % (n, ps, us))
        else:
            dummy.append('pub struct %s;' % n)
    for n in sorted(holders):
        dummy.append("pub struct %s<'c>(&'c mut Checker);" % n)
    for n in sorted(traits - {'Program'}):
        dummy.append('pub trait %s {}' % n)
    lib = ['#![allow(warnings)]', 'pub mod dummy;', 'pub use dummy::*;']
    for f in files:
        base = os.path.basename(f)[:-3]
        body = '\n'.join(l for l in open(f).read().split('\n') if not l.startswith('use '))
        open(os.path.join(src, base + '.rs'), 'w').write('use crate::*;\nuse std::fmt::Display;\n' + body)
        lib.append('pub mod %s;' % base)
    open(os.path.join(src, 'dummy.rs'), 'w').write('\n'.join(dummy) + '\n')
    open(os.path.join(src, 'lib.rs'), 'w').write('\n'.join(lib) + '\n')
    open(os.path.join(scratch, 'Cargo.toml'), 'w').write(
        '[package]\nname = "gosigcheck"\nversion = "0.0.0"\nedition = "2021"\n[workspace]\n')


def main():
    stub_dir = sys.argv[1]
    scratch = sys.argv[2] if len(sys.argv) > 2 else 'target/scratch/gosig/checkcrate'
    extra = set()
    for _ in range(4):
        build(stub_dir, scratch, extra)
        r = subprocess.run(['cargo', 'check', '--quiet'], cwd=scratch, capture_output=True, text=True,
                           env=dict(os.environ, CARGO_TARGET_DIR=os.path.join(os.path.abspath(scratch), 'target')))
        missing = set(re.findall(r'cannot find type `([A-Za-z0-9_]+)`', r.stderr))
        if r.returncode == 0:
            print('ok: stubs compile against dummy types')
            return
        if not missing - extra:
            print(r.stderr)
            sys.exit(1)
        extra |= missing
    print(r.stderr)
    sys.exit(1)


if __name__ == '__main__':
    main()
