//! Port of `internal/transformers/declarations` (TypeScript 7), plus the transformer base it builds on
//! (`internal/transformers`: `transformer.go` and the utilities it uses).
//!
//! Only the diagnostics are used (`tsc` reports them whenever `declaration`/`composite` is on), but the transform
//! is ported faithfully: which nodes are visited, in what order and with which node-builder flags decides which
//! diagnostics fire. Entry point: `get_declaration_diagnostics` (Go `compiler.getDeclarationDiagnostics`) is in
//! `tsrs_compiler`; it builds a `DeclarationTransformer` with `new_declaration_transformer` and runs
//! `transform_source_file` while lending the file's checker to the transformer (see `Resolver`).
//!
//! Layout (one Rust file per Go file; transform.go is split by line range):
//! - types.rs: the hand-ported data model of all Go files (structs, host trait, constants).
//! - `Resolver` and `Transformer` come from tsrs_transformers (re-exported).
//! - transform_{1,2,3}.rs (transform.go 1–1339, 1340–2327, 2328–end), diagnostics.rs, tracker.rs, util.rs,
//!   supplementalreferences.rs: function bodies (stubs generated by tools/gosig with declarations.json).

pub(crate) use std::cell::{Cell, OnceCell, RefCell};
pub(crate) use std::fmt::Display;
pub(crate) use std::rc::Rc;

pub(crate) use rustc_hash::{FxHashMap, FxHashSet};
pub(crate) use tsrs_ast::{self as ast, *};
pub(crate) use tsrs_checker::{self as checker, Checker, CheckerSlot, EmitResolver, SymbolAccessibility, SymbolAccessibilityResult, SymbolTracker};
pub(crate) use tsrs_core::collections::Set;
pub(crate) use tsrs_core::jsnum::{self, Number};
pub(crate) use tsrs_core::tspath;
pub(crate) use tsrs_core::{alloc_slice, alloc_str, alloc_vec, CompilerOptions, Tristate, P};
pub(crate) use tsrs_diagnostics::{self as diagnostics, Message};
pub(crate) use tsrs_modulespecifiers::ModuleSpecifierGenerationHost;
pub(crate) use tsrs_printer::{self as printer, EmitContext};
pub(crate) use tsrs_scanner as scanner;
pub(crate) use tsrs_tsoptions::outputpaths::OutputPaths;
pub(crate) use tsrs_transformers as transformers;

/// Go package `nodebuilder` (flags only).
pub(crate) mod nodebuilder {
    pub use tsrs_checker::{Flags, InternalFlags};
}

mod types;

// Go: `declarations` imports `transformers`; the base types moved to tsrs_transformers and are re-exported here so
// existing paths keep compiling.
pub use tsrs_transformers::{is_original_node_single_line, is_simple_copiable_expression, is_simple_inlineable_expression, Resolver, Transformer};
pub use types::*;

mod diagnostics_;
mod supplementalreferences;
mod tracker;
mod transform_1;
mod transform_2;
mod transform_3;
mod util;

pub use diagnostics_::*;
pub use supplementalreferences::*;
pub use tracker::*;
pub use transform_1::*;
pub use transform_2::*;
pub use transform_3::*;
pub use util::*;
