use crate::*;

// Stubs generated by tools/gosig. Keep the signatures; replace the todo!() bodies.

// Non-function declarations in transform.go:1-1339 (hand-ported in types.rs):
//   type ReferencedFilePair (transform.go:23)
//   type OutputPaths (transform.go:28)
//   type DeclarationEmitHost (transform.go:34)
//   type thisPropertyAssignmentKey (transform.go:46)
//   type DeclarationTransformer (transform.go:63)
//   const declarationEmitNodeBuilderFlags (transform.go:215)
//   const declarationEmitInternalNodeBuilderFlags (transform.go:223)

// transform.go:53
pub(crate) fn get_this_property_assignment_key(name: Option<P<Node>>, node: P<Node>, is_static: bool) -> thisPropertyAssignmentKey {
    todo!()
}

// transform.go:103
pub fn new_declaration_transformer(host: &'static dyn DeclarationEmitHost, context: P<EmitContext>, compiler_options: P<CompilerOptions>, declaration_file_path: &str, declaration_map_path: &str) -> P<DeclarationTransformer> {
    todo!()
}

impl DeclarationTransformer {
    // transform.go:142
    pub fn get_diagnostics(&self) -> Vec<P<Diagnostic>> {
        todo!()
    }

    // transform.go:146
    pub(crate) fn should_strip_internal(&self, node: Option<P<Node>>) -> bool {
        todo!()
    }

    // transform.go:150
    pub(crate) fn is_internal_declaration(&self, node: Option<P<Node>>, source_file: P<SourceFile>) -> bool {
        todo!()
    }

    // transform.go:203
    pub(crate) fn get_leading_comment_ranges_of_node(&self, node: P<Node>, source_file: P<SourceFile>) -> Vec<CommentRange> {
        todo!()
    }
}

// transform.go:210
pub(crate) fn has_internal_annotation(comment_range: CommentRange, source_file: P<SourceFile>) -> bool {
    todo!()
}

impl DeclarationTransformer {
    // transform.go:226
    pub(crate) fn visit(&self, node: P<Node>) -> Option<P<Node>> {
        todo!()
    }
}

// transform.go:276
pub(crate) fn throw_diagnostic(result: &SymbolAccessibilityResult) -> P<SymbolAccessibilityDiagnostic> {
    todo!()
}

impl DeclarationTransformer {
    // transform.go:280
    pub(crate) fn visit_source_file(&self, node: P<SourceFile>) -> P<Node> {
        todo!()
    }

    // transform.go:310
    pub(crate) fn collect_file_references(&self, source_file: P<SourceFile>) {
        todo!()
    }
}

// transform.go:316
pub(crate) fn node_or_syntax_list_children(node: P<Node>) -> Vec<P<Node>> {
    todo!()
}

// transform.go:323
pub(crate) fn flatten_syntax_lists(nodes: &[P<Node>]) -> Vec<P<Node>> {
    todo!()
}

impl DeclarationTransformer {
    // transform.go:327
    pub(crate) fn append_cjs_exports(&self, combined_statements: P<NodeList>) -> P<NodeList> {
        todo!()
    }

    // transform.go:341
    pub(crate) fn transform_source_file(&self, node: P<SourceFile>) -> P<Node> {
        todo!()
    }
}

// transform.go:382
pub(crate) fn create_empty_exports(factory: &NodeFactory) -> P<Node> {
    todo!()
}

impl DeclarationTransformer {
    // transform.go:386
    pub(crate) fn transform_and_replace_late_painted_statements(&self, statements: P<NodeList>) -> P<NodeList> {
        todo!()
    }

    // transform.go:464
    pub(crate) fn get_referenced_files(&self, output_file_path: &str) -> Vec<P<FileReference>> {
        todo!()
    }

    // transform.go:519
    pub(crate) fn get_lib_references(&self) -> Vec<P<FileReference>> {
        todo!()
    }

    // transform.go:535
    pub(crate) fn get_type_references(&self) -> Vec<P<FileReference>> {
        todo!()
    }

    // transform.go:551
    pub(crate) fn setup_diagnostic_context(&self, input: P<Node>) -> (bool, Box<dyn FnMut()>) {
        todo!()
    }

    // transform.go:573
    pub(crate) fn visit_declaration_subtree(&self, input: P<Node>) -> Option<P<Node>> {
        todo!()
    }

    // transform.go:708
    pub(crate) fn check_name(&self, node: P<Node>) {
        todo!()
    }

    // transform.go:723
    pub(crate) fn transform_mapped_type_node(&self, input: P<Node>) -> P<Node> {
        todo!()
    }

    // transform.go:742
    pub(crate) fn transform_heritage_clause(&self, clause: P<Node>) -> Option<P<Node>> {
        todo!()
    }

    // transform.go:761
    pub(crate) fn transform_import_type_node(&self, input: P<Node>) -> P<Node> {
        todo!()
    }

    // transform.go:778
    pub(crate) fn transform_constructor_type_node(&self, input: P<Node>) -> P<Node> {
        todo!()
    }

    // transform.go:788
    pub(crate) fn transform_function_type_node(&self, input: P<Node>) -> P<Node> {
        todo!()
    }

    // transform.go:797
    pub(crate) fn transform_conditional_type_node(&self, input: P<Node>) -> P<Node> {
        todo!()
    }

    // transform.go:815
    pub(crate) fn transform_type_reference(&self, input: P<Node>) -> Option<P<Node>> {
        todo!()
    }

    // transform.go:820
    pub(crate) fn transform_expression_with_type_arguments(&self, input: P<Node>) -> Option<P<Node>> {
        todo!()
    }

    // transform.go:827
    pub(crate) fn transform_type_parameter_declaration(&self, input: P<Node>) -> Option<P<Node>> {
        todo!()
    }

    // transform.go:841
    pub(crate) fn transform_variable_declaration(&self, input: P<Node>) -> Option<P<Node>> {
        todo!()
    }
}

// transform.go:859
pub(crate) fn has_any_binding_initializers(binding_pattern: P<Node>) -> bool {
    todo!()
}

impl DeclarationTransformer {
    // transform.go:875
    pub(crate) fn transform_cjs_require_variable_declaration(&self, input: P<Node>) -> Option<P<Node>> {
        todo!()
    }

    // transform.go:907
    pub(crate) fn recreate_binding_pattern(&self, input: P<Node>) -> Option<P<Node>> {
        todo!()
    }

    // transform.go:929
    pub(crate) fn recreate_binding_element(&self, e: P<Node>) -> Option<P<Node>> {
        todo!()
    }

    // transform.go:947
    pub(crate) fn transform_index_signature_declaration(&self, input: P<Node>) -> P<Node> {
        todo!()
    }

    // transform.go:960
    pub(crate) fn transform_call_signature_declaration(&self, input: P<Node>) -> P<Node> {
        todo!()
    }

    // transform.go:969
    pub(crate) fn transform_property_signature_declaration(&self, input: P<Node>) -> Option<P<Node>> {
        todo!()
    }

    // transform.go:985
    pub(crate) fn transform_property_declaration(&self, input: P<Node>) -> Option<P<Node>> {
        todo!()
    }

    // transform.go:1004
    pub(crate) fn transform_set_accessor_declaration(&self, input: P<Node>) -> Option<P<Node>> {
        todo!()
    }

    // transform.go:1021
    pub(crate) fn transform_get_accesor_declaration(&self, input: P<Node>) -> Option<P<Node>> {
        todo!()
    }

    // transform.go:1037
    pub(crate) fn update_accessor_param_list(&self, input: P<Node>, is_private: bool) -> P<NodeList> {
        todo!()
    }

    // transform.go:1074
    pub(crate) fn transform_constructor_declaration(&self, input: P<Node>) -> P<Node> {
        todo!()
    }

    // transform.go:1087
    pub(crate) fn transform_construct_signature_declaration(&self, input: P<Node>) -> P<Node> {
        todo!()
    }

    // transform.go:1096
    pub(crate) fn omit_private_method_type(&self, input: P<Node>) -> Option<P<Node>> {
        todo!()
    }

    // transform.go:1122
    pub(crate) fn transform_method_signature_declaration(&self, input: P<Node>) -> Option<P<Node>> {
        todo!()
    }

    // transform.go:1140
    pub(crate) fn transform_method_declaration(&self, input: P<Node>) -> Option<P<Node>> {
        todo!()
    }

    // transform.go:1161
    pub(crate) fn visit_declaration_statements(&self, input: P<Node>) -> Option<P<Node>> {
        todo!()
    }

    // transform.go:1192
    pub(crate) fn try_get_name_of_assigned_expression(&self, unwrapped: P<Node>) -> Option<P<Node>> {
        todo!()
    }

    // transform.go:1212
    pub(crate) fn get_name_of_exported_assigned_expression(&self, unwrapped: P<Node>, is_export_equals: bool) -> P<Node> {
        todo!()
    }

    // transform.go:1227
    pub(crate) fn transform_export_assignment(&self, input: P<Node>, assignment: P<Node>, expression: P<Node>, is_export_equals: bool) -> P<Node> {
        todo!()
    }

    // transform.go:1305
    pub(crate) fn transform_function_like_to_declaration(&self, unwrapped: P<Node>, func_name: P<Node>, mods: P<ModifierList>, full_signature_type: P<Node>) -> P<Node> {
        todo!()
    }

    // transform.go:1331
    pub(crate) fn transform_binary_expression_to_export_declaration(&self, input: P<Node>, name: P<Node>) -> P<Node> {
        todo!()
    }
}
