use crate::*;

// Stubs generated by tools/gosig. Keep the signatures; replace the todo!() bodies.

impl DeclarationTransformer {
    // transform.go:1350
    pub(crate) fn transform_common_js_export(&self, input: P<Node>, name: P<Node>) -> P<Node> {
        todo!()
    }

    // transform.go:1358
    pub(crate) fn transform_common_js_export_worker(&self, input: P<Node>, name: P<Node>) -> Option<P<Node>> {
        todo!()
    }

    // transform.go:1543
    pub(crate) fn wrap_in_cjs_export_namespace(&self, content: P<Node>) -> P<Node> {
        todo!()
    }
}

// transform.go:1569
pub(crate) fn is_common_js_alias_export(node: P<Node>) -> bool {
    todo!()
}

impl DeclarationTransformer {
    // transform.go:1581
    pub(crate) fn transform_class_expression_to_declaration(&self, class_expr: P<Node>, class_name: P<Node>, modifiers: P<ModifierList>) -> P<Node> {
        todo!()
    }

    // transform.go:1608
    pub(crate) fn rewrite_module_specifier(&self, parent: P<Node>, input: P<Node>) -> P<Node> {
        todo!()
    }

    // transform.go:1616
    pub(crate) fn preserve_js_doc(&self, updated: P<Node>, original: P<Node>) {
        todo!()
    }

    // transform.go:1621
    pub(crate) fn preserve_partial_js_doc(&self, updated: P<Node>, original: P<Node>) {
        todo!()
    }

    // transform.go:1637
    pub(crate) fn remove_all_comments(&self, node: P<Node>) {
        todo!()
    }

    // transform.go:1644
    pub(crate) fn ensure_type(&self, node: P<Node>, ignore_private: bool) -> Option<P<Node>> {
        todo!()
    }

    // transform.go:1708
    pub(crate) fn should_print_with_initializer(&self, node: P<Node>) -> bool {
        todo!()
    }

    // transform.go:1712
    pub(crate) fn check_entity_name_visibility(&self, entity_name: P<Node>, enclosing_declaration: P<Node>) {
        todo!()
    }

    // transform.go:1718
    pub(crate) fn transform_top_level_declaration(&self, input: P<Node>) -> Option<P<Node>> {
        todo!()
    }

    // transform.go:1798
    pub(crate) fn transform_type_alias_declaration(&self, input: P<Node>) -> P<Node> {
        todo!()
    }

    // transform.go:1809
    pub(crate) fn transform_interface_declaration(&self, input: P<Node>) -> P<Node> {
        todo!()
    }

    // transform.go:1820
    pub(crate) fn transform_function_declaration(&self, input: P<Node>) -> P<Node> {
        todo!()
    }

    // transform.go:1837
    pub(crate) fn transform_module_declaration(&self, input: P<Node>) -> P<Node> {
        todo!()
    }

    // transform.go:1914
    pub(crate) fn strip_export_modifiers(&self, statement: P<Node>) -> P<Node> {
        todo!()
    }

    // transform.go:1937
    pub(crate) fn build_class_members(&self, class_node: P<Node>, extra_members: &[P<Node>]) -> P<NodeList> {
        todo!()
    }

    // transform.go:1997
    pub(crate) fn transform_class_declaration(&self, input: P<Node>) -> P<Node> {
        todo!()
    }

    // transform.go:2091
    pub(crate) fn visit_this_property_assignments(&self, node: P<Node>) -> Option<P<Node>> {
        todo!()
    }
}

// transform.go:2160
pub(crate) fn is_class_extending_null(node: Option<P<Node>>) -> bool {
    todo!()
}

impl DeclarationTransformer {
    // transform.go:2178
    pub(crate) fn collect_this_property_assignments(&self, class_node: P<Node>) -> Vec<P<Node>> {
        todo!()
    }

    // transform.go:2201
    pub(crate) fn walk_binding_pattern(&self, pattern: P<Node>, param: P<Node>) -> Vec<P<Node>> {
        todo!()
    }

    // transform.go:2222
    pub(crate) fn transform_variable_statement(&self, input: P<Node>) -> Option<P<Node>> {
        todo!()
    }

    // transform.go:2277
    pub(crate) fn transform_enum_declaration(&self, input: P<Node>) -> P<Node> {
        todo!()
    }
}
