[package]
name = "tsrs_linter"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
rustc-hash.workspace = true
tsrs_core.workspace = true
tsrs_ast.workspace = true
tsrs_vfs.workspace = true
tsrs_checker.workspace = true
tsrs_compiler.workspace = true
tsrs_project.workspace = true

[dev-dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tsrs_scanner.workspace = true
