// Code generated by tools/oracle/ast/gen-fields.ts. DO NOT EDIT.

use tsrs_ast::{Node, NodeData};

use crate::Dumper;

pub(crate) fn dump_fields(n: &Node, d: &mut Dumper) {
    match n.data() {
        NodeData::Identifier(x) => {
            d.field_string("Text", x.text());
        }
        NodeData::PrivateIdentifier(x) => {
            d.field_string("Text", x.text());
        }
        NodeData::CaseBlock(x) => {
            d.field_list("Clauses", x.clauses());
        }
        NodeData::CaseOrDefaultClause(x) => {
            d.field_list("Statements", x.statements());
        }
        NodeData::Block(x) => {
            d.field_list("Statements", x.statements());
            d.field_bool("MultiLine", x.multi_line());
        }
        NodeData::VariableStatement(x) => {
            d.field_modlist("modifiers", x.modifiers());
        }
        NodeData::VariableDeclarationList(x) => {
            d.field_list("Declarations", x.declarations());
        }
        NodeData::BindingPattern(x) => {
            d.field_list("Elements", x.elements());
        }
        NodeData::ParameterDeclaration(x) => {
            d.field_modlist("modifiers", x.modifiers());
        }
        NodeData::MissingDeclaration(x) => {
            d.field_modlist("modifiers", x.modifiers());
        }
        NodeData::FunctionDeclaration(x) => {
            d.field_modlist("modifiers", x.modifiers());
            d.field_list("TypeParameters", x.type_parameters());
            d.field_list("Parameters", x.parameters());
        }
        NodeData::ClassDeclaration(x) => {
            d.field_modlist("modifiers", x.modifiers());
            d.field_list("TypeParameters", x.type_parameters());
            d.field_list("HeritageClauses", x.heritage_clauses());
            d.field_list("Members", x.members());
        }
        NodeData::ClassExpression(x) => {
            d.field_modlist("modifiers", x.modifiers());
            d.field_list("TypeParameters", x.type_parameters());
            d.field_list("HeritageClauses", x.heritage_clauses());
            d.field_list("Members", x.members());
        }
        NodeData::HeritageClause(x) => {
            d.field_kind("Token", x.token());
            d.field_list("Types", x.types());
        }
        NodeData::InterfaceDeclaration(x) => {
            d.field_modlist("modifiers", x.modifiers());
            d.field_list("TypeParameters", x.type_parameters());
            d.field_list("HeritageClauses", x.heritage_clauses());
            d.field_list("Members", x.members());
        }
        NodeData::TypeAliasDeclaration(x) => {
            d.field_modlist("modifiers", x.modifiers());
            d.field_list("TypeParameters", x.type_parameters());
        }
        NodeData::EnumDeclaration(x) => {
            d.field_modlist("modifiers", x.modifiers());
            d.field_list("Members", x.members());
        }
        NodeData::ModuleBlock(x) => {
            d.field_list("Statements", x.statements());
        }
        NodeData::ImportDeclaration(x) => {
            d.field_modlist("modifiers", x.modifiers());
        }
        NodeData::NamedImports(x) => {
            d.field_list("Elements", x.elements());
        }
        NodeData::ExportAssignment(x) => {
            d.field_modlist("modifiers", x.modifiers());
            d.field_bool("IsExportEquals", x.is_export_equals());
        }
        NodeData::NamespaceExportDeclaration(x) => {
            d.field_modlist("modifiers", x.modifiers());
        }
        NodeData::NamedExports(x) => {
            d.field_list("Elements", x.elements());
        }
        NodeData::ExportSpecifier(x) => {
            d.field_bool("IsTypeOnly", x.is_type_only());
        }
        NodeData::CallSignatureDeclaration(x) => {
            d.field_list("TypeParameters", x.type_parameters());
            d.field_list("Parameters", x.parameters());
        }
        NodeData::ConstructSignatureDeclaration(x) => {
            d.field_list("TypeParameters", x.type_parameters());
            d.field_list("Parameters", x.parameters());
        }
        NodeData::ConstructorDeclaration(x) => {
            d.field_modlist("modifiers", x.modifiers());
            d.field_list("TypeParameters", x.type_parameters());
            d.field_list("Parameters", x.parameters());
        }
        NodeData::GetAccessorDeclaration(x) => {
            d.field_modlist("modifiers", x.modifiers());
            d.field_list("TypeParameters", x.type_parameters());
            d.field_list("Parameters", x.parameters());
        }
        NodeData::SetAccessorDeclaration(x) => {
            d.field_modlist("modifiers", x.modifiers());
            d.field_list("TypeParameters", x.type_parameters());
            d.field_list("Parameters", x.parameters());
        }
        NodeData::IndexSignatureDeclaration(x) => {
            d.field_modlist("modifiers", x.modifiers());
            d.field_list("Parameters", x.parameters());
        }
        NodeData::MethodSignatureDeclaration(x) => {
            d.field_modlist("modifiers", x.modifiers());
            d.field_list("TypeParameters", x.type_parameters());
            d.field_list("Parameters", x.parameters());
        }
        NodeData::MethodDeclaration(x) => {
            d.field_modlist("modifiers", x.modifiers());
            d.field_list("TypeParameters", x.type_parameters());
            d.field_list("Parameters", x.parameters());
        }
        NodeData::PropertySignatureDeclaration(x) => {
            d.field_modlist("modifiers", x.modifiers());
        }
        NodeData::PropertyDeclaration(x) => {
            d.field_modlist("modifiers", x.modifiers());
        }
        NodeData::ClassStaticBlockDeclaration(x) => {
            d.field_modlist("modifiers", x.modifiers());
        }
        NodeData::StringLiteral(x) => {
            d.field_string("Text", x.text());
            d.field_tokenflags("TokenFlags", x.token_flags());
        }
        NodeData::NumericLiteral(x) => {
            d.field_string("Text", x.text());
            d.field_tokenflags("TokenFlags", x.token_flags());
        }
        NodeData::BigIntLiteral(x) => {
            d.field_string("Text", x.text());
            d.field_tokenflags("TokenFlags", x.token_flags());
        }
        NodeData::RegularExpressionLiteral(x) => {
            d.field_string("Text", x.text());
            d.field_tokenflags("TokenFlags", x.token_flags());
        }
        NodeData::NoSubstitutionTemplateLiteral(x) => {
            d.field_string("Text", x.text());
            d.field_tokenflags("TemplateFlags", x.template_flags());
        }
        NodeData::BinaryExpression(x) => {
            d.field_modlist("modifiers", x.modifiers());
        }
        NodeData::PrefixUnaryExpression(x) => {
            d.field_kind("Operator", x.operator());
        }
        NodeData::PostfixUnaryExpression(x) => {
            d.field_kind("Operator", x.operator());
        }
        NodeData::ArrowFunction(x) => {
            d.field_modlist("modifiers", x.modifiers());
            d.field_list("TypeParameters", x.type_parameters());
            d.field_list("Parameters", x.parameters());
        }
        NodeData::FunctionExpression(x) => {
            d.field_modlist("modifiers", x.modifiers());
            d.field_list("TypeParameters", x.type_parameters());
            d.field_list("Parameters", x.parameters());
        }
        NodeData::CallExpression(x) => {
            d.field_list("TypeArguments", x.type_arguments());
            d.field_list("Arguments", x.arguments());
        }
        NodeData::NewExpression(x) => {
            d.field_list("TypeArguments", x.type_arguments());
            d.field_list("Arguments", x.arguments());
        }
        NodeData::MetaProperty(x) => {
            d.field_kind("KeywordToken", x.keyword_token());
        }
        NodeData::TemplateExpression(x) => {
            d.field_list("TemplateSpans", x.template_spans());
        }
        NodeData::TaggedTemplateExpression(x) => {
            d.field_list("TypeArguments", x.type_arguments());
        }
        NodeData::ArrayLiteralExpression(x) => {
            d.field_list("Elements", x.elements());
            d.field_bool("MultiLine", x.multi_line());
        }
        NodeData::ObjectLiteralExpression(x) => {
            d.field_list("Properties", x.properties());
            d.field_bool("MultiLine", x.multi_line());
        }
        NodeData::PropertyAssignment(x) => {
            d.field_modlist("modifiers", x.modifiers());
        }
        NodeData::ShorthandPropertyAssignment(x) => {
            d.field_modlist("modifiers", x.modifiers());
        }
        NodeData::UnionTypeNode(x) => {
            d.field_list("Types", x.types());
        }
        NodeData::IntersectionTypeNode(x) => {
            d.field_list("Types", x.types());
        }
        NodeData::TypeOperatorNode(x) => {
            d.field_kind("Operator", x.operator());
        }
        NodeData::TypeReferenceNode(x) => {
            d.field_list("TypeArguments", x.type_arguments());
        }
        NodeData::ExpressionWithTypeArguments(x) => {
            d.field_list("TypeArguments", x.type_arguments());
        }
        NodeData::ImportAttributes(x) => {
            d.field_kind("Token", x.token());
            d.field_list("Attributes", x.attributes());
            d.field_bool("MultiLine", x.multi_line());
        }
        NodeData::TypeQueryNode(x) => {
            d.field_list("TypeArguments", x.type_arguments());
        }
        NodeData::MappedTypeNode(x) => {
            d.field_list("Members", x.members());
        }
        NodeData::TypeLiteralNode(x) => {
            d.field_list("Members", x.members());
        }
        NodeData::TupleTypeNode(x) => {
            d.field_list("Elements", x.elements());
        }
        NodeData::FunctionTypeNode(x) => {
            d.field_list("TypeParameters", x.type_parameters());
            d.field_list("Parameters", x.parameters());
        }
        NodeData::ConstructorTypeNode(x) => {
            d.field_modlist("modifiers", x.modifiers());
            d.field_list("TypeParameters", x.type_parameters());
            d.field_list("Parameters", x.parameters());
        }
        NodeData::TemplateHead(x) => {
            d.field_string("Text", x.text());
            d.field_string("RawText", x.raw_text());
            d.field_tokenflags("TemplateFlags", x.template_flags());
        }
        NodeData::TemplateMiddle(x) => {
            d.field_string("Text", x.text());
            d.field_string("RawText", x.raw_text());
            d.field_tokenflags("TemplateFlags", x.template_flags());
        }
        NodeData::TemplateTail(x) => {
            d.field_string("Text", x.text());
            d.field_string("RawText", x.raw_text());
            d.field_tokenflags("TemplateFlags", x.template_flags());
        }
        NodeData::TemplateLiteralTypeNode(x) => {
            d.field_list("TemplateSpans", x.template_spans());
        }
        NodeData::SyntheticExpression(x) => {
            d.field_bool("IsSpread", x.is_spread());
        }
        NodeData::JsxElement(x) => {
            d.field_list("Children", x.children());
        }
        NodeData::JsxAttributes(x) => {
            d.field_list("Properties", x.properties());
        }
        NodeData::JsxOpeningElement(x) => {
            d.field_list("TypeArguments", x.type_arguments());
        }
        NodeData::JsxSelfClosingElement(x) => {
            d.field_list("TypeArguments", x.type_arguments());
        }
        NodeData::JsxFragment(x) => {
            d.field_list("Children", x.children());
        }
        NodeData::JsxText(x) => {
            d.field_string("Text", x.text());
            d.field_bool("ContainsOnlyTriviaWhiteSpaces", x.contains_only_trivia_white_spaces());
        }
        NodeData::SyntaxList(x) => {
            d.field_rawnodes("Children", x.children());
        }
        NodeData::JSDoc(x) => {
            d.field_list("Comment", x.comment());
            d.field_list("Tags", x.tags());
        }
        NodeData::JSDocTypeTag(x) => {
            d.field_list("Comment", x.comment());
        }
        NodeData::JSDocUnknownTag(x) => {
            d.field_list("Comment", x.comment());
        }
        NodeData::JSDocTemplateTag(x) => {
            d.field_list("TypeParameters", x.type_parameters());
            d.field_list("Comment", x.comment());
        }
        NodeData::JSDocReturnTag(x) => {
            d.field_list("Comment", x.comment());
        }
        NodeData::JSDocPublicTag(x) => {
            d.field_list("Comment", x.comment());
        }
        NodeData::JSDocPrivateTag(x) => {
            d.field_list("Comment", x.comment());
        }
        NodeData::JSDocProtectedTag(x) => {
            d.field_list("Comment", x.comment());
        }
        NodeData::JSDocReadonlyTag(x) => {
            d.field_list("Comment", x.comment());
        }
        NodeData::JSDocOverrideTag(x) => {
            d.field_list("Comment", x.comment());
        }
        NodeData::JSDocDeprecatedTag(x) => {
            d.field_list("Comment", x.comment());
        }
        NodeData::JSDocSeeTag(x) => {
            d.field_list("Comment", x.comment());
        }
        NodeData::JSDocImplementsTag(x) => {
            d.field_list("Comment", x.comment());
        }
        NodeData::JSDocAugmentsTag(x) => {
            d.field_list("Comment", x.comment());
        }
        NodeData::JSDocSatisfiesTag(x) => {
            d.field_list("Comment", x.comment());
        }
        NodeData::JSDocThrowsTag(x) => {
            d.field_list("Comment", x.comment());
        }
        NodeData::JSDocThisTag(x) => {
            d.field_list("Comment", x.comment());
        }
        NodeData::JSDocImportTag(x) => {
            d.field_list("Comment", x.comment());
        }
        NodeData::JSDocCallbackTag(x) => {
            d.field_list("Comment", x.comment());
        }
        NodeData::JSDocOverloadTag(x) => {
            d.field_list("Comment", x.comment());
        }
        NodeData::JSDocTypedefTag(x) => {
            d.field_list("Comment", x.comment());
        }
        NodeData::JSDocSignature(x) => {
            d.field_list("TypeParameters", x.type_parameters());
            d.field_list("Parameters", x.parameters());
        }
        NodeData::SourceFile(x) => {
            d.field_list("Statements", x.statements());
        }
        NodeData::ModuleDeclaration(x) => {
            d.field_modlist("modifiers", x.modifiers());
            d.field_kind("Keyword", x.keyword());
        }
        NodeData::ImportEqualsDeclaration(x) => {
            d.field_modlist("modifiers", x.modifiers());
            d.field_bool("IsTypeOnly", x.is_type_only());
        }
        NodeData::ExportDeclaration(x) => {
            d.field_modlist("modifiers", x.modifiers());
            d.field_bool("IsTypeOnly", x.is_type_only());
        }
        NodeData::ImportTypeNode(x) => {
            d.field_bool("IsTypeOf", x.is_type_of());
            d.field_list("TypeArguments", x.type_arguments());
        }
        NodeData::ImportClause(x) => {
            d.field_kind("PhaseModifier", x.phase_modifier());
        }
        NodeData::ImportSpecifier(x) => {
            d.field_bool("IsTypeOnly", x.is_type_only());
        }
        NodeData::JSDocText(x) => {
            d.field_rawstrings("text", x.text());
        }
        NodeData::JSDocLink(x) => {
            d.field_rawstrings("text", x.text());
        }
        NodeData::JSDocLinkPlain(x) => {
            d.field_rawstrings("text", x.text());
        }
        NodeData::JSDocLinkCode(x) => {
            d.field_rawstrings("text", x.text());
        }
        NodeData::TypeParameterDeclaration(x) => {
            d.field_modlist("modifiers", x.modifiers());
        }
        NodeData::JSDocTypeLiteral(x) => {
            d.field_rawnodes("JSDocPropertyTags", x.jsdoc_property_tags());
            d.field_bool("IsArrayType", x.is_array_type());
        }
        NodeData::JSDocParameterOrPropertyTag(x) => {
            d.field_bool("IsBracketed", x.is_bracketed());
            d.field_bool("IsNameFirst", x.is_name_first());
            d.field_list("Comment", x.comment());
        }
        _ => {}
    }
}
