use crate::*;
use tsrs_ast::*;
use tsrs_core::*;
use tsrs_ast as ast;

// Stubs generated by tools/gosig. Keep the signatures; replace the todo!() bodies.

impl PseudoChecker {
    // lookup.go:11
    pub fn get_return_type_of_signature(&self, signature_node: P<Node>) -> Option<P<PseudoType>> {
        todo!()
    }

    // lookup.go:26
    pub fn get_type_of_accessor(&self, accessor: P<Node>) -> Option<P<PseudoType>> {
        todo!()
    }

    // lookup.go:30
    pub fn get_type_of_expression(&self, node: P<Node>) -> Option<P<PseudoType>> {
        todo!()
    }

    // lookup.go:34
    pub fn get_type_of_declaration(&self, node: P<Node>) -> Option<P<PseudoType>> {
        todo!()
    }

    // lookup.go:69
    pub(crate) fn type_from_property_assignment(&self, node: P<Node>) -> P<PseudoType> {
        todo!()
    }

    // lookup.go:88
    pub(crate) fn type_from_expando_property(&self, node: P<Node>) -> P<PseudoType> {
        todo!()
    }

    // lookup.go:98
    pub(crate) fn type_from_property(&self, node: P<Node>) -> P<PseudoType> {
        todo!()
    }

    // lookup.go:124
    pub(crate) fn type_from_variable(&self, declaration: P<Node>) -> P<PseudoType> {
        todo!()
    }

    // lookup.go:146
    pub(crate) fn type_from_accessor(&self, accessor: P<Node>) -> Option<P<PseudoType>> {
        todo!()
    }

    // lookup.go:166
    pub(crate) fn get_type_annotation_from_all_accessor_declarations(&self, node: P<Node>, accessors: AllAccessorDeclarations) -> Option<P<Node>> {
        todo!()
    }

    // lookup.go:177
    pub(crate) fn get_type_annotation_from_accessor(&self, node: P<Node>) -> Option<P<Node>> {
        todo!()
    }
}

// lookup.go:196
pub(crate) fn is_value_signature_declaration(node: P<Node>) -> bool {
    todo!()
}

impl PseudoChecker {
    // lookup.go:201
    pub(crate) fn create_return_from_signature(&self, fn_: P<Node>) -> Option<P<PseudoType>> {
        todo!()
    }

    // lookup.go:216
    pub(crate) fn type_from_single_return_expression(&self, fn_: Option<P<Node>>) -> Option<P<PseudoType>> {
        todo!()
    }

    // lookup.go:262
    pub(crate) fn type_from_expression(&self, node: P<Node>) -> Option<P<PseudoType>> {
        todo!()
    }

    // lookup.go:315
    pub(crate) fn type_from_object_literal(&self, node: P<Node>) -> P<PseudoType> {
        todo!()
    }

    // lookup.go:363
    pub(crate) fn get_accessor_member(&self, accessor: P<Node>, name: P<Node>) -> Option<P<PseudoObjectElement>> {
        todo!()
    }

    // lookup.go:406
    pub(crate) fn can_get_type_from_object_literal(&self, node: P<Node>) -> Vec<P<Node>> {
        todo!()
    }

    // lookup.go:438
    pub(crate) fn type_from_array_literal(&self, node: P<Node>) -> P<PseudoType> {
        todo!()
    }

    // lookup.go:457
    pub(crate) fn can_get_type_from_array_literal(&self, node: P<Node>) -> Vec<P<Node>> {
        todo!()
    }
}

// lookup.go:470
pub(crate) fn is_const_context_propagating_kind(kind: Kind) -> bool {
    todo!()
}

// lookup.go:482
pub fn is_in_const_context(node: P<Node>) -> bool {
    todo!()
}

impl PseudoChecker {
    // lookup.go:494
    pub(crate) fn type_from_primitive_literal_prefix(&self, node: P<Node>) -> Option<P<PseudoType>> {
        todo!()
    }

    // lookup.go:510
    pub(crate) fn type_from_type_assertion(&self, expression: P<Node>, type_node: P<Node>) -> Option<P<PseudoType>> {
        todo!()
    }

    // lookup.go:517
    pub(crate) fn type_from_function_like_expression(&self, node: P<Node>) -> P<PseudoType> {
        todo!()
    }

    // lookup.go:532
    pub(crate) fn clone_type_parameters(&self, nodes: Option<P<NodeList>>) -> Vec<P<Node>> {
        todo!()
    }
}

// lookup.go:546
pub(crate) fn is_undefined_pseudo_type(t: P<PseudoType>) -> bool {
    todo!()
}

// lookup.go:550
pub(crate) fn type_node_could_refer_to_undefined(node: P<Node>) -> bool {
    todo!()
}

// lookup.go:578
pub fn could_already_refer_to_undefined_type(t: P<PseudoType>) -> bool {
    todo!()
}

// lookup.go:597
pub(crate) fn is_optional_initialized_or_rest_parameter(node: P<Node>) -> bool {
    todo!()
}

// lookup.go:610
pub(crate) fn last_required_param_index(params: &[P<Node>]) -> i32 {
    todo!()
}

// lookup.go:619
pub(crate) fn add_undefined_if_definitely_required(expr: P<PseudoType>) -> P<PseudoType> {
    todo!()
}

impl PseudoChecker {
    // lookup.go:631
    pub(crate) fn type_from_parameter(&self, node: P<Node>) -> Option<P<PseudoType>> {
        todo!()
    }

    // lookup.go:649
    pub(crate) fn type_from_parameter_worker(&self, node: P<Node>, self_idx: i32, last_required: i32) -> Option<P<PseudoType>> {
        todo!()
    }

    // lookup.go:687
    pub(crate) fn clone_parameters(&self, nodes: Option<P<NodeList>>) -> Vec<P<PseudoParameter>> {
        todo!()
    }
}

// lookup.go:715
pub(crate) fn is_contextually_typed(node: P<Node>) -> bool {
    todo!()
}
