// Pinned method inventory: every `Method` constant in microsoft/TypeScript
// tsc/internal/api/proto.go @ b85298b6a81f772d080b0455de0ca9d744cd6fd6 (172 entries, same order).
// `status` is the honest implementation state in tsrs; it must only become `Supported` when a real
// compiler-backed test exercises the method (docs/NODE_API.md keeps the matrix in sync).

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Owner { Core, Checker }

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Status {
    /// Dispatches to a real implementation covered by tests.
    Supported,
    /// Dispatches, but with documented gaps (see docs/NODE_API.md).
    Partial,
    /// Not implemented: dispatch returns an explicit `api: unsupported method` error.
    NotImplemented,
}

pub struct MethodInfo { pub name: &'static str, pub owner: Owner, pub status: Status }

pub const METHODS: [MethodInfo; 172] = [
    MethodInfo { name: "release", owner: Owner::Core, status: Status::Supported },
    MethodInfo { name: "releaseSourceFile", owner: Owner::Core, status: Status::NotImplemented },
    MethodInfo { name: "retainSourceFile", owner: Owner::Core, status: Status::NotImplemented },
    MethodInfo { name: "getCachedSourceFile", owner: Owner::Core, status: Status::NotImplemented },
    MethodInfo { name: "batchRequests", owner: Owner::Core, status: Status::Supported },
    MethodInfo { name: "initialize", owner: Owner::Core, status: Status::Supported },
    MethodInfo { name: "createSnapshot", owner: Owner::Core, status: Status::Supported },
    MethodInfo { name: "updateSnapshot", owner: Owner::Core, status: Status::Supported },
    MethodInfo { name: "getCurrentLanguageServerSnapshot", owner: Owner::Core, status: Status::NotImplemented },
    MethodInfo { name: "createBuildOrchestrator", owner: Owner::Core, status: Status::NotImplemented },
    MethodInfo { name: "disposeBuildOrchestrator", owner: Owner::Core, status: Status::NotImplemented },
    MethodInfo { name: "build", owner: Owner::Core, status: Status::NotImplemented },
    MethodInfo { name: "buildReferences", owner: Owner::Core, status: Status::NotImplemented },
    MethodInfo { name: "cleanBuild", owner: Owner::Core, status: Status::NotImplemented },
    MethodInfo { name: "cleanReferences", owner: Owner::Core, status: Status::NotImplemented },
    MethodInfo { name: "createModuleResolver", owner: Owner::Core, status: Status::Supported },
    MethodInfo { name: "releaseModuleResolver", owner: Owner::Core, status: Status::Supported },
    MethodInfo { name: "resolveModuleName", owner: Owner::Core, status: Status::Supported },
    MethodInfo { name: "parseCommandLine", owner: Owner::Core, status: Status::Supported },
    MethodInfo { name: "readConfigFile", owner: Owner::Core, status: Status::Supported },
    MethodInfo { name: "parseJsonConfigFileContent", owner: Owner::Core, status: Status::Supported },
    MethodInfo { name: "parseConfigFile", owner: Owner::Core, status: Status::Supported },
    MethodInfo { name: "createSourceFile", owner: Owner::Core, status: Status::NotImplemented },
    MethodInfo { name: "createSourceFileFromFile", owner: Owner::Core, status: Status::NotImplemented },
    MethodInfo { name: "transpileModule", owner: Owner::Core, status: Status::Supported },
    MethodInfo { name: "transpileModuleFromFile", owner: Owner::Core, status: Status::Supported },
    MethodInfo { name: "transpileDeclaration", owner: Owner::Core, status: Status::Supported },
    MethodInfo { name: "transpileDeclarationFromFile", owner: Owner::Core, status: Status::Supported },
    MethodInfo { name: "getDefaultProjectForFile", owner: Owner::Core, status: Status::Supported },
    MethodInfo { name: "getSymbolAtPosition", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getSymbolsAtPositions", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getSymbolAtLocation", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getSymbolsAtLocations", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getSymbolOfSourceFile", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getSymbolsOfSourceFiles", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getTypeOfSymbol", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getTypesOfSymbols", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getDeclaredTypeOfSymbol", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getNonMissingTypeOfSymbol", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getSourceFile", owner: Owner::Core, status: Status::NotImplemented },
    MethodInfo { name: "getSourceFileNames", owner: Owner::Core, status: Status::Supported },
    MethodInfo { name: "getSourceFileMetadata", owner: Owner::Core, status: Status::Supported },
    MethodInfo { name: "getModeForUsageLocation", owner: Owner::Core, status: Status::NotImplemented },
    MethodInfo { name: "getModeForResolutionAtIndex", owner: Owner::Core, status: Status::NotImplemented },
    MethodInfo { name: "getResolvedModule", owner: Owner::Core, status: Status::NotImplemented },
    MethodInfo { name: "getResolvedModuleFromModuleSpecifier", owner: Owner::Core, status: Status::NotImplemented },
    MethodInfo { name: "getResolvedTypeReferenceDirective", owner: Owner::Core, status: Status::NotImplemented },
    MethodInfo { name: "getResolvedTypeReferenceDirectiveFromTypeReferenceDirective", owner: Owner::Core, status: Status::NotImplemented },
    MethodInfo { name: "getConfigFileNames", owner: Owner::Core, status: Status::Supported },
    MethodInfo { name: "getConfigSourceFile", owner: Owner::Core, status: Status::NotImplemented },
    MethodInfo { name: "resolveName", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getSymbolsInScope", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getSignaturesOfType", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getResolvedSignature", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getTypeAtLocation", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getTypeAtLocations", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getTypeAtPosition", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getTypesAtPositions", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getParentOfSymbol", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getMembersOfSymbol", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getExportsOfSymbol", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getExportSymbolOfSymbol", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getSymbolOfType", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getTargetOfType", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getFreshTypeOfType", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getRegularTypeOfType", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getTypesOfType", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getTypeParametersOfType", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getOuterTypeParametersOfType", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getLocalTypeParametersOfType", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getThisTypeOfType", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getAliasTypeArgumentsOfType", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getAliasSymbolOfType", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getObjectTypeOfType", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getIndexTypeOfType", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getCheckTypeOfType", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getExtendsTypeOfType", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getBaseTypeOfType", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getConstraintOfType", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getTypeParameterOfMappedType", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getConstraintTypeOfMappedType", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getNameTypeOfMappedType", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getTemplateTypeOfMappedType", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getTypeParametersOfSignature", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getParametersOfSignature", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getThisParameterOfSignature", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getTargetOfSignature", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getContextualType", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getContextualTypeForArgument", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getAwaitedType", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getBaseTypeOfLiteralType", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getNonNullableType", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getTypeFromTypeNode", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getWidenedType", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getParameterType", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getTypeParameterAtPosition", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "isArrayLikeType", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "isTypeAssignableTo", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getShorthandAssignmentValueSymbol", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getTypeOfSymbolAtLocation", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "typeToTypeNode", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "signatureToSignatureDeclaration", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "typeToString", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "isContextSensitive", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getReturnTypeOfSignature", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getRestTypeOfSignature", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getTypePredicateOfSignature", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getBaseTypes", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getPropertiesOfType", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getApparentPropertiesOfType", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getApparentType", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getReducedType", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getPropertyOfType", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getTypeOfPropertyOfType", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getIndexInfoOfType", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getIndexInfosOfType", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getConstraintOfTypeParameter", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getDefaultFromTypeParameter", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getBaseConstraintOfType", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getTypeArguments", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getImportAdderEdits", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getTrueTypeOfConditionalType", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getFalseTypeOfConditionalType", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getConstantValue", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getSignatureFromDeclaration", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getExportSpecifierLocalTargetSymbol", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getAliasedSymbol", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getImmediateAliasedSymbol", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getTargetSymbol", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getExportSymbolOfSymbolForChecker", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getFullyQualifiedName", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getExportsOfModule", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getMemberInModuleExports", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getJsDocTags", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getDocumentationComment", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "isArrayType", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "isReadonlySymbol", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getReferencesToSymbolInFile", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getReferencedSymbolsForNode", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getSignatureUsages", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getCompletionsAtPosition", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getSyntacticDiagnostics", owner: Owner::Core, status: Status::Supported },
    MethodInfo { name: "getBindDiagnostics", owner: Owner::Core, status: Status::Supported },
    MethodInfo { name: "getSemanticDiagnostics", owner: Owner::Core, status: Status::Supported },
    MethodInfo { name: "getSuggestionDiagnostics", owner: Owner::Core, status: Status::Partial },
    MethodInfo { name: "getDeclarationDiagnostics", owner: Owner::Core, status: Status::Supported },
    MethodInfo { name: "getProgramDiagnostics", owner: Owner::Core, status: Status::Supported },
    MethodInfo { name: "getGlobalDiagnostics", owner: Owner::Core, status: Status::Supported },
    MethodInfo { name: "getConfigFileParsingDiagnostics", owner: Owner::Core, status: Status::Supported },
    MethodInfo { name: "printNode", owner: Owner::Core, status: Status::NotImplemented },
    MethodInfo { name: "formatNodeForInsertion", owner: Owner::Core, status: Status::NotImplemented },
    MethodInfo { name: "emit", owner: Owner::Core, status: Status::Supported },
    MethodInfo { name: "emitToString", owner: Owner::Core, status: Status::Supported },
    MethodInfo { name: "getJavaScriptEmit", owner: Owner::Core, status: Status::Supported },
    MethodInfo { name: "getDeclarationEmit", owner: Owner::Core, status: Status::Supported },
    MethodInfo { name: "getAnyType", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getStringType", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getNumberType", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getBooleanType", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getVoidType", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getUndefinedType", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getNullType", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getNeverType", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getUnknownType", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getBigIntType", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getESSymbolType", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getNonPrimitiveType", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getWellKnownSymbols", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "getWellKnownSignatures", owner: Owner::Checker, status: Status::NotImplemented },
    MethodInfo { name: "startCPUProfile", owner: Owner::Core, status: Status::NotImplemented },
    MethodInfo { name: "stopCPUProfile", owner: Owner::Core, status: Status::NotImplemented },
    MethodInfo { name: "saveHeapProfile", owner: Owner::Core, status: Status::NotImplemented },
];

pub fn method_info(name: &str) -> Option<&'static MethodInfo> {
    METHODS.iter().find(|m| m.name == name)
}
