// Pinned method inventory: every `Method` constant in microsoft/TypeScript
// tsc/internal/api/proto.go @ b85298b6a81f772d080b0455de0ca9d744cd6fd6 (172 entries, same order).
// `status` is the honest implementation state in tsrs; it must only become `Supported` when a real
// compiler-backed test exercises the method (docs/NODE_API.md keeps the matrix in sync).

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Owner { Core, Checker }

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Status {
    /// Dispatches to a real implementation covered by tests.
    Supported,
    /// Dispatches, but with documented gaps (see docs/NODE_API.md).
    Partial,
    /// Not implemented: dispatch returns an explicit `api: unsupported method` error.
    NotImplemented,
}

pub struct MethodInfo { pub name: &'static str, pub owner: Owner, pub status: Status }

pub const METHODS: [MethodInfo; 172] = [
    MethodInfo { name: "release", owner: Owner::Core, status: Status::Supported },
    MethodInfo { name: "releaseSourceFile", owner: Owner::Core, status: Status::Supported },
    MethodInfo { name: "retainSourceFile", owner: Owner::Core, status: Status::Partial },
    MethodInfo { name: "getCachedSourceFile", owner: Owner::Core, status: Status::Partial },
    MethodInfo { name: "batchRequests", owner: Owner::Core, status: Status::Supported },
    MethodInfo { name: "initialize", owner: Owner::Core, status: Status::Supported },
    MethodInfo { name: "createSnapshot", owner: Owner::Core, status: Status::Supported },
    MethodInfo { name: "updateSnapshot", owner: Owner::Core, status: Status::Supported },
    MethodInfo { name: "getCurrentLanguageServerSnapshot", owner: Owner::Core, status: Status::Partial },
    MethodInfo { name: "createBuildOrchestrator", owner: Owner::Core, status: Status::Supported },
    MethodInfo { name: "disposeBuildOrchestrator", owner: Owner::Core, status: Status::Supported },
    MethodInfo { name: "build", owner: Owner::Core, status: Status::Supported },
    MethodInfo { name: "buildReferences", owner: Owner::Core, status: Status::Supported },
    MethodInfo { name: "cleanBuild", owner: Owner::Core, status: Status::Supported },
    MethodInfo { name: "cleanReferences", owner: Owner::Core, status: Status::Partial },
    MethodInfo { name: "createModuleResolver", owner: Owner::Core, status: Status::Supported },
    MethodInfo { name: "releaseModuleResolver", owner: Owner::Core, status: Status::Supported },
    MethodInfo { name: "resolveModuleName", owner: Owner::Core, status: Status::Supported },
    MethodInfo { name: "parseCommandLine", owner: Owner::Core, status: Status::Supported },
    MethodInfo { name: "readConfigFile", owner: Owner::Core, status: Status::Supported },
    MethodInfo { name: "parseJsonConfigFileContent", owner: Owner::Core, status: Status::Supported },
    MethodInfo { name: "parseConfigFile", owner: Owner::Core, status: Status::Supported },
    MethodInfo { name: "createSourceFile", owner: Owner::Core, status: Status::Supported },
    MethodInfo { name: "createSourceFileFromFile", owner: Owner::Core, status: Status::Partial },
    MethodInfo { name: "transpileModule", owner: Owner::Core, status: Status::Supported },
    MethodInfo { name: "transpileModuleFromFile", owner: Owner::Core, status: Status::Supported },
    MethodInfo { name: "transpileDeclaration", owner: Owner::Core, status: Status::Supported },
    MethodInfo { name: "transpileDeclarationFromFile", owner: Owner::Core, status: Status::Supported },
    MethodInfo { name: "getDefaultProjectForFile", owner: Owner::Core, status: Status::Supported },
    MethodInfo { name: "getSymbolAtPosition", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getSymbolsAtPositions", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getSymbolAtLocation", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getSymbolsAtLocations", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getSymbolOfSourceFile", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getSymbolsOfSourceFiles", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getTypeOfSymbol", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getTypesOfSymbols", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getDeclaredTypeOfSymbol", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getNonMissingTypeOfSymbol", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getSourceFile", owner: Owner::Core, status: Status::Supported },
    MethodInfo { name: "getSourceFileNames", owner: Owner::Core, status: Status::Supported },
    MethodInfo { name: "getSourceFileMetadata", owner: Owner::Core, status: Status::Supported },
    MethodInfo { name: "getModeForUsageLocation", owner: Owner::Core, status: Status::Partial },
    MethodInfo { name: "getModeForResolutionAtIndex", owner: Owner::Core, status: Status::Partial },
    MethodInfo { name: "getResolvedModule", owner: Owner::Core, status: Status::Partial },
    MethodInfo { name: "getResolvedModuleFromModuleSpecifier", owner: Owner::Core, status: Status::Partial },
    MethodInfo { name: "getResolvedTypeReferenceDirective", owner: Owner::Core, status: Status::Partial },
    MethodInfo { name: "getResolvedTypeReferenceDirectiveFromTypeReferenceDirective", owner: Owner::Core, status: Status::Partial },
    MethodInfo { name: "getConfigFileNames", owner: Owner::Core, status: Status::Supported },
    MethodInfo { name: "getConfigSourceFile", owner: Owner::Core, status: Status::Partial },
    MethodInfo { name: "resolveName", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getSymbolsInScope", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getSignaturesOfType", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getResolvedSignature", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getTypeAtLocation", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getTypeAtLocations", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getTypeAtPosition", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getTypesAtPositions", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getParentOfSymbol", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getMembersOfSymbol", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getExportsOfSymbol", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getExportSymbolOfSymbol", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getSymbolOfType", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getTargetOfType", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getFreshTypeOfType", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getRegularTypeOfType", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getTypesOfType", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getTypeParametersOfType", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getOuterTypeParametersOfType", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getLocalTypeParametersOfType", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getThisTypeOfType", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getAliasTypeArgumentsOfType", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getAliasSymbolOfType", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getObjectTypeOfType", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getIndexTypeOfType", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getCheckTypeOfType", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getExtendsTypeOfType", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getBaseTypeOfType", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getConstraintOfType", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getTypeParameterOfMappedType", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getConstraintTypeOfMappedType", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getNameTypeOfMappedType", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getTemplateTypeOfMappedType", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getTypeParametersOfSignature", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getParametersOfSignature", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getThisParameterOfSignature", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getTargetOfSignature", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getContextualType", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getContextualTypeForArgument", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getAwaitedType", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getBaseTypeOfLiteralType", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getNonNullableType", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getTypeFromTypeNode", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getWidenedType", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getParameterType", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getTypeParameterAtPosition", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "isArrayLikeType", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "isTypeAssignableTo", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getShorthandAssignmentValueSymbol", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getTypeOfSymbolAtLocation", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "typeToTypeNode", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "signatureToSignatureDeclaration", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "typeToString", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "isContextSensitive", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getReturnTypeOfSignature", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getRestTypeOfSignature", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getTypePredicateOfSignature", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getBaseTypes", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getPropertiesOfType", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getApparentPropertiesOfType", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getApparentType", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getReducedType", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getPropertyOfType", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getTypeOfPropertyOfType", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getIndexInfoOfType", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getIndexInfosOfType", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getConstraintOfTypeParameter", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getDefaultFromTypeParameter", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getBaseConstraintOfType", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getTypeArguments", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getImportAdderEdits", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getTrueTypeOfConditionalType", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getFalseTypeOfConditionalType", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getConstantValue", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getSignatureFromDeclaration", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getExportSpecifierLocalTargetSymbol", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getAliasedSymbol", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getImmediateAliasedSymbol", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getTargetSymbol", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getExportSymbolOfSymbolForChecker", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getFullyQualifiedName", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getExportsOfModule", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getMemberInModuleExports", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getJsDocTags", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getDocumentationComment", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "isArrayType", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "isReadonlySymbol", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getReferencesToSymbolInFile", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getReferencedSymbolsForNode", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getSignatureUsages", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getCompletionsAtPosition", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getSyntacticDiagnostics", owner: Owner::Core, status: Status::Supported },
    MethodInfo { name: "getBindDiagnostics", owner: Owner::Core, status: Status::Supported },
    MethodInfo { name: "getSemanticDiagnostics", owner: Owner::Core, status: Status::Supported },
    MethodInfo { name: "getSuggestionDiagnostics", owner: Owner::Core, status: Status::Partial },
    MethodInfo { name: "getDeclarationDiagnostics", owner: Owner::Core, status: Status::Supported },
    MethodInfo { name: "getProgramDiagnostics", owner: Owner::Core, status: Status::Supported },
    MethodInfo { name: "getGlobalDiagnostics", owner: Owner::Core, status: Status::Supported },
    MethodInfo { name: "getConfigFileParsingDiagnostics", owner: Owner::Core, status: Status::Supported },
    MethodInfo { name: "printNode", owner: Owner::Core, status: Status::Partial },
    MethodInfo { name: "formatNodeForInsertion", owner: Owner::Core, status: Status::Partial },
    MethodInfo { name: "emit", owner: Owner::Core, status: Status::Supported },
    MethodInfo { name: "emitToString", owner: Owner::Core, status: Status::Supported },
    MethodInfo { name: "getJavaScriptEmit", owner: Owner::Core, status: Status::Supported },
    MethodInfo { name: "getDeclarationEmit", owner: Owner::Core, status: Status::Supported },
    MethodInfo { name: "getAnyType", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getStringType", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getNumberType", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getBooleanType", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getVoidType", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getUndefinedType", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getNullType", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getNeverType", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getUnknownType", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getBigIntType", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getESSymbolType", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getNonPrimitiveType", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getWellKnownSymbols", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "getWellKnownSignatures", owner: Owner::Checker, status: Status::Partial },
    MethodInfo { name: "startCPUProfile", owner: Owner::Core, status: Status::NotImplemented },
    MethodInfo { name: "stopCPUProfile", owner: Owner::Core, status: Status::NotImplemented },
    MethodInfo { name: "saveHeapProfile", owner: Owner::Core, status: Status::NotImplemented },
];

pub fn method_info(name: &str) -> Option<&'static MethodInfo> {
    METHODS.iter().find(|m| m.name == name)
}
// Go `unmarshalers` (proto.go): the params type each method decodes into, for Go's error text
// `failed to unmarshal *api.<Type>`. `None` = `noParams`.
pub const PARAMS_TYPES: &[(&str, Option<&str>)] = &[
    ("batchRequests", Some("BatchRequestsParams")),
    ("release", Some("ReleaseParams")),
    ("releaseSourceFile", Some("ReleaseSourceFileParams")),
    ("retainSourceFile", Some("RetainSourceFileParams")),
    ("getCachedSourceFile", Some("GetCachedSourceFileParams")),
    ("initialize", None),
    ("createSnapshot", Some("CreateSnapshotParams")),
    ("updateSnapshot", Some("UpdateSnapshotParams")),
    ("getCurrentLanguageServerSnapshot", Some("GetCurrentLanguageServerSnapshotParams")),
    ("createBuildOrchestrator", Some("CreateBuildOrchestratorParams")),
    ("disposeBuildOrchestrator", Some("DisposeBuildOrchestratorParams")),
    ("build", Some("BuildParams")),
    ("buildReferences", Some("BuildParams")),
    ("cleanBuild", Some("CleanBuildParams")),
    ("cleanReferences", Some("CleanBuildParams")),
    ("createModuleResolver", Some("CreateModuleResolverParams")),
    ("releaseModuleResolver", Some("ReleaseModuleResolverParams")),
    ("resolveModuleName", Some("ResolveModuleNameParams")),
    ("parseCommandLine", Some("ParseCommandLineParams")),
    ("readConfigFile", Some("ReadConfigFileParams")),
    ("parseJsonConfigFileContent", Some("ParseJsonConfigFileContentParams")),
    ("parseConfigFile", Some("ParseConfigFileParams")),
    ("createSourceFile", Some("CreateSourceFileParams")),
    ("createSourceFileFromFile", Some("CreateSourceFileFromFileParams")),
    ("transpileModule", Some("TranspileParams")),
    ("transpileModuleFromFile", Some("TranspileFromFileParams")),
    ("transpileDeclaration", Some("TranspileParams")),
    ("transpileDeclarationFromFile", Some("TranspileFromFileParams")),
    ("getDefaultProjectForFile", Some("GetDefaultProjectForFileParams")),
    ("getSourceFile", Some("GetSourceFileParams")),
    ("getSourceFileNames", Some("GetSourceFileNamesParams")),
    ("getSourceFileMetadata", Some("GetSourceFileParams")),
    ("getModeForUsageLocation", Some("GetModeForUsageLocationParams")),
    ("getModeForResolutionAtIndex", Some("GetModeForResolutionAtIndexParams")),
    ("getResolvedModule", Some("GetResolvedModuleParams")),
    ("getResolvedModuleFromModuleSpecifier", Some("GetResolvedModuleFromModuleSpecifierParams")),
    ("getResolvedTypeReferenceDirective", Some("GetResolvedTypeReferenceDirectiveParams")),
    ("getResolvedTypeReferenceDirectiveFromTypeReferenceDirective", Some("GetResolvedTypeReferenceDirectiveFromReferenceParams")),
    ("getConfigFileNames", Some("GetProjectDiagnosticsParams")),
    ("getConfigSourceFile", Some("GetSourceFileParams")),
    ("getSymbolAtPosition", Some("GetSymbolAtPositionParams")),
    ("getSymbolsAtPositions", Some("GetSymbolsAtPositionsParams")),
    ("getSymbolAtLocation", Some("GetSymbolAtLocationParams")),
    ("getSymbolsAtLocations", Some("GetSymbolsAtLocationsParams")),
    ("getSymbolOfSourceFile", Some("GetSymbolOfSourceFileParams")),
    ("getSymbolsOfSourceFiles", Some("GetSymbolsOfSourceFilesParams")),
    ("getTypeOfSymbol", Some("GetTypeOfSymbolParams")),
    ("getTypesOfSymbols", Some("GetTypesOfSymbolsParams")),
    ("getDeclaredTypeOfSymbol", Some("GetTypeOfSymbolParams")),
    ("getNonMissingTypeOfSymbol", Some("GetTypeOfSymbolParams")),
    ("resolveName", Some("ResolveNameParams")),
    ("getSymbolsInScope", Some("GetSymbolsInScopeParams")),
    ("getSignaturesOfType", Some("GetSignaturesOfTypeParams")),
    ("getResolvedSignature", Some("GetResolvedSignatureParams")),
    ("getTypeAtLocation", Some("GetTypeAtLocationParams")),
    ("getTypeAtLocations", Some("GetTypeAtLocationsParams")),
    ("getTypeAtPosition", Some("GetTypeAtPositionParams")),
    ("getTypesAtPositions", Some("GetTypesAtPositionsParams")),
    ("getParentOfSymbol", Some("GetSymbolPropertyParams")),
    ("getMembersOfSymbol", Some("GetSymbolPropertyParams")),
    ("getExportsOfSymbol", Some("GetSymbolPropertyParams")),
    ("getExportSymbolOfSymbol", Some("GetSymbolPropertyParams")),
    ("getSymbolOfType", Some("GetTypePropertyParams")),
    ("getTargetOfType", Some("GetTypePropertyParams")),
    ("getFreshTypeOfType", Some("GetTypePropertyParams")),
    ("getRegularTypeOfType", Some("GetTypePropertyParams")),
    ("getTypesOfType", Some("GetTypePropertyParams")),
    ("getTypeParametersOfType", Some("GetTypePropertyParams")),
    ("getOuterTypeParametersOfType", Some("GetTypePropertyParams")),
    ("getLocalTypeParametersOfType", Some("GetTypePropertyParams")),
    ("getThisTypeOfType", Some("GetTypePropertyParams")),
    ("getAliasTypeArgumentsOfType", Some("GetTypePropertyParams")),
    ("getAliasSymbolOfType", Some("GetTypePropertyParams")),
    ("getObjectTypeOfType", Some("GetTypePropertyParams")),
    ("getIndexTypeOfType", Some("GetTypePropertyParams")),
    ("getCheckTypeOfType", Some("GetTypePropertyParams")),
    ("getExtendsTypeOfType", Some("GetTypePropertyParams")),
    ("getBaseTypeOfType", Some("GetTypePropertyParams")),
    ("getConstraintOfType", Some("GetTypePropertyParams")),
    ("getTypeParameterOfMappedType", Some("GetTypePropertyParams")),
    ("getConstraintTypeOfMappedType", Some("GetTypePropertyParams")),
    ("getNameTypeOfMappedType", Some("GetTypePropertyParams")),
    ("getTemplateTypeOfMappedType", Some("GetTypePropertyParams")),
    ("getTrueTypeOfConditionalType", Some("GetTypePropertyParams")),
    ("getFalseTypeOfConditionalType", Some("GetTypePropertyParams")),
    ("getTypeParametersOfSignature", Some("GetSignaturePropertyParams")),
    ("getParametersOfSignature", Some("GetSignaturePropertyParams")),
    ("getThisParameterOfSignature", Some("GetSignaturePropertyParams")),
    ("getTargetOfSignature", Some("GetSignaturePropertyParams")),
    ("getContextualType", Some("GetContextualTypeParams")),
    ("getContextualTypeForArgument", Some("GetContextualTypeForArgumentParams")),
    ("getAwaitedType", Some("CheckerTypeParams")),
    ("getBaseTypeOfLiteralType", Some("GetBaseTypeOfLiteralTypeParams")),
    ("getNonNullableType", Some("GetTypePropertyParams")),
    ("getTypeFromTypeNode", Some("GetTypeFromTypeNodeParams")),
    ("getWidenedType", Some("GetWidenedTypeParams")),
    ("getParameterType", Some("GetParameterTypeParams")),
    ("getTypeParameterAtPosition", Some("GetParameterTypeParams")),
    ("isArrayLikeType", Some("IsArrayLikeTypeParams")),
    ("isTypeAssignableTo", Some("IsTypeAssignableToParams")),
    ("getShorthandAssignmentValueSymbol", Some("GetTypeAtLocationParams")),
    ("getTypeOfSymbolAtLocation", Some("GetTypeOfSymbolAtLocationParams")),
    ("typeToTypeNode", Some("TypeToTypeNodeParams")),
    ("signatureToSignatureDeclaration", Some("SignatureToSignatureDeclarationParams")),
    ("typeToString", Some("TypeToTypeNodeParams")),
    ("isContextSensitive", Some("GetContextualTypeParams")),
    ("getReturnTypeOfSignature", Some("GetSignaturePropertyParams")),
    ("getRestTypeOfSignature", Some("CheckerSignatureParams")),
    ("getTypePredicateOfSignature", Some("CheckerSignatureParams")),
    ("getBaseTypes", Some("CheckerTypeParams")),
    ("getPropertiesOfType", Some("CheckerTypeParams")),
    ("getApparentPropertiesOfType", Some("GetTypePropertyParams")),
    ("getApparentType", Some("GetTypePropertyParams")),
    ("getReducedType", Some("GetTypePropertyParams")),
    ("getPropertyOfType", Some("GetPropertyOfTypeParams")),
    ("getTypeOfPropertyOfType", Some("GetPropertyOfTypeParams")),
    ("getIndexInfoOfType", Some("GetIndexInfoOfTypeParams")),
    ("getIndexInfosOfType", Some("CheckerTypeParams")),
    ("getConstraintOfTypeParameter", Some("GetTypePropertyParams")),
    ("getBaseConstraintOfType", Some("CheckerTypeParams")),
    ("getDefaultFromTypeParameter", Some("GetTypePropertyParams")),
    ("getTypeArguments", Some("CheckerTypeParams")),
    ("getImportAdderEdits", Some("GetImportAdderEditsParams")),
    ("getConstantValue", Some("CheckerNodeParams")),
    ("getSignatureFromDeclaration", Some("CheckerNodeParams")),
    ("getExportSpecifierLocalTargetSymbol", Some("CheckerNodeParams")),
    ("getAliasedSymbol", Some("CheckerSymbolParams")),
    ("getImmediateAliasedSymbol", Some("CheckerSymbolParams")),
    ("getTargetSymbol", Some("CheckerSymbolParams")),
    ("getExportSymbolOfSymbolForChecker", Some("CheckerSymbolParams")),
    ("getFullyQualifiedName", Some("CheckerSymbolParams")),
    ("getExportsOfModule", Some("CheckerSymbolParams")),
    ("getMemberInModuleExports", Some("GetMemberInModuleExportsParams")),
    ("getJsDocTags", Some("CheckerSymbolParams")),
    ("getDocumentationComment", Some("CheckerSymbolParams")),
    ("isArrayType", Some("CheckerTypeParams")),
    ("isReadonlySymbol", Some("CheckerSymbolParams")),
    ("getReferencesToSymbolInFile", Some("GetReferencesToSymbolInFileParams")),
    ("getReferencedSymbolsForNode", Some("GetReferencedSymbolsForNodeParams")),
    ("getSignatureUsages", Some("GetSignatureUsagesParams")),
    ("getCompletionsAtPosition", Some("GetCompletionsAtPositionParams")),
    ("printNode", Some("PrintNodeParams")),
    ("formatNodeForInsertion", Some("FormatNodeForInsertionParams")),
    ("emit", Some("EmitParams")),
    ("emitToString", Some("EmitParams")),
    ("getJavaScriptEmit", Some("SelectedFilesEmitParams")),
    ("getDeclarationEmit", Some("SelectedFilesEmitParams")),
    ("getAnyType", Some("GetIntrinsicTypeParams")),
    ("getStringType", Some("GetIntrinsicTypeParams")),
    ("getNumberType", Some("GetIntrinsicTypeParams")),
    ("getBooleanType", Some("GetIntrinsicTypeParams")),
    ("getVoidType", Some("GetIntrinsicTypeParams")),
    ("getUndefinedType", Some("GetIntrinsicTypeParams")),
    ("getNullType", Some("GetIntrinsicTypeParams")),
    ("getNeverType", Some("GetIntrinsicTypeParams")),
    ("getUnknownType", Some("GetIntrinsicTypeParams")),
    ("getBigIntType", Some("GetIntrinsicTypeParams")),
    ("getESSymbolType", Some("GetIntrinsicTypeParams")),
    ("getNonPrimitiveType", Some("GetIntrinsicTypeParams")),
    ("getWellKnownSymbols", Some("GetIntrinsicTypeParams")),
    ("getWellKnownSignatures", Some("GetIntrinsicTypeParams")),
    ("getSyntacticDiagnostics", Some("GetDiagnosticsParams")),
    ("getBindDiagnostics", Some("GetDiagnosticsParams")),
    ("getSemanticDiagnostics", Some("GetDiagnosticsParams")),
    ("getSuggestionDiagnostics", Some("GetDiagnosticsParams")),
    ("getDeclarationDiagnostics", Some("GetDiagnosticsParams")),
    ("getProgramDiagnostics", Some("GetProjectDiagnosticsParams")),
    ("getGlobalDiagnostics", Some("GetProjectDiagnosticsParams")),
    ("getConfigFileParsingDiagnostics", Some("GetProjectDiagnosticsParams")),
    ("startCPUProfile", Some("ProfileParams")),
    ("stopCPUProfile", None),
    ("saveHeapProfile", Some("ProfileParams")),
];

pub fn params_type(method: &str) -> Option<&'static str> {
    PARAMS_TYPES.iter().find(|(m, _)| *m == method).and_then(|(_, t)| *t)
}
