[package]
name = "tsrs_scanner"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
tsrs_core.workspace = true
tsrs_diagnostics.workspace = true
tsrs_ast.workspace = true
rustc-hash.workspace = true
bitflags.workspace = true
unicode-ident.workspace = true
memchr.workspace = true
