use crate::*;
use tsrs_ast::*;
use tsrs_core::*;
use tsrs_ast as ast;
use tsrs_core::tspath::{self, Path};
use tsrs_module::packagejson;
use rustc_hash::FxHashMap;

// Stubs generated by tools/gosig. Keep the signatures; replace the todo!() bodies.

// Non-function declarations in preferences.go (hand-ported in types.rs):
//   type ModuleSpecifierPreferences (preferences.go:141)

// preferences.go:14
pub(crate) fn should_allow_importing_ts_extension(compiler_options: &CompilerOptions, from_file_name: &str) -> bool {
    todo!()
}

// preferences.go:18
pub(crate) fn uses_extensions_on_imports(file: P<SourceFile>) -> bool {
    todo!()
}

// preferences.go:28
pub(crate) fn infer_preference(resolution_mode: ModuleKind, source_file: Option<P<SourceFile>>, module_resolution_is_node_next: bool) -> ModuleSpecifierEnding {
    todo!()
}

// preferences.go:69
pub(crate) fn get_module_specifier_ending_preference(pref: ImportModuleSpecifierEndingPreference, resolution_mode: ModuleKind, compiler_options: &CompilerOptions, source_file: Option<P<SourceFile>>) -> ModuleSpecifierEnding {
    todo!()
}

// preferences.go:114
pub(crate) fn get_preferred_ending(prefs: UserPreferences, host: &dyn ModuleSpecifierGenerationHost, compiler_options: &CompilerOptions, importing_source_file: P<SourceFile>, old_import_specifier: &str, resolution_mode: ModuleKind) -> ModuleSpecifierEnding {
    todo!()
}

// preferences.go:147
pub fn get_allowed_endings_in_preferred_order(prefs: UserPreferences, host: &dyn ModuleSpecifierGenerationHost, compiler_options: &CompilerOptions, importing_source_file: P<SourceFile>, old_import_specifier: &str, syntax_implied_node_format: ModuleKind) -> Vec<ModuleSpecifierEnding> {
    todo!()
}

// preferences.go:213
pub(crate) fn get_module_specifier_preferences(prefs: UserPreferences, host: &dyn ModuleSpecifierGenerationHost, compiler_options: &CompilerOptions, importing_source_file: P<SourceFile>, old_import_specifier: &str) -> ModuleSpecifierPreferences {
    todo!()
}
