//! Port of the pinned `tsc/internal/api/encoder/decoder.go` (hand-written part); the per-kind factories live in
//! `generated.rs`.
//!
//! Unlike the Go decoder, every read is bounds-checked and malformed input yields a [`DecodeError`] instead of a
//! panic or an endless sibling walk: the bytes come from an API client. Accepted input decodes to the same tree
//! the Go decoder builds.

use tsrs_ast::*;
use tsrs_core::arena::Region;
use tsrs_core::{alloc_str, tspath, LanguageVariant, ScriptKind, TextRange, P};

use crate::format::*;

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum DecodeError {
    TooShort(usize),
    UnsupportedVersion(u8),
    InvalidHeader(String),
    NoNodes,
    InvalidKind(u32),
    UnexpectedKind(Kind),
    InvalidTree(String),
    InvalidString(String),
    InvalidExtendedData(String),
    InvalidCommonData { kind: Kind, value: u32 },
    MissingChild,
    InvalidSourceFileName(String),
    Unsupported(Kind),
    /// Input on which the pinned Go decoder panics (the server recovers and returns `panic: <message>`); the
    /// Rust decoder fails at the same point instead of decoding more than Go can.
    GoDecoderPanic(String),
}

impl std::fmt::Display for DecodeError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            DecodeError::TooShort(n) => write!(f, "data too short for header: {n} bytes"),
            DecodeError::UnsupportedVersion(v) => write!(f, "unsupported protocol version {v} (expected {PROTOCOL_VERSION})"),
            DecodeError::InvalidHeader(s) => write!(f, "invalid AST header offsets: {s}"),
            DecodeError::NoNodes => write!(f, "no nodes to decode"),
            DecodeError::InvalidKind(k) => write!(f, "invalid node kind {k}"),
            DecodeError::UnexpectedKind(k) => write!(f, "unexpected node kind {k:?}"),
            DecodeError::InvalidTree(s) => write!(f, "invalid node tree: {s}"),
            DecodeError::InvalidString(s) => write!(f, "invalid string: {s}"),
            DecodeError::InvalidExtendedData(s) => write!(f, "invalid extended data: {s}"),
            DecodeError::InvalidCommonData { kind, value } => write!(f, "invalid common data {value} for {kind:?}"),
            DecodeError::MissingChild => write!(f, "missing required child"),
            DecodeError::InvalidSourceFileName(s) => write!(f, "invalid source file name {s:?}"),
            DecodeError::Unsupported(k) => write!(f, "{k:?} cannot be decoded"),
            DecodeError::GoDecoderPanic(m) => write!(f, "{m}"),
        }
    }
}

impl std::error::Error for DecodeError {}

/// A decoded tree together with the region that owns its nodes. `root()` (and everything reachable from it) is
/// valid only while this value is alive; never store those pointers past it.
pub struct DecodedNode {
    root: P<Node>,
    region: Region,
}

impl DecodedNode {
    pub fn root(&self) -> P<Node> {
        self.root
    }

    pub fn region(&self) -> &Region {
        &self.region
    }
}

/// Go `DecodeNodes`, decoding into a fresh region owned by the result.
pub fn decode_nodes(data: &[u8]) -> Result<DecodedNode, DecodeError> {
    let region = Region::new((data.len() * 4).clamp(4096, 64 << 20));
    let root = {
        let _scope = region.enter();
        decode_nodes_in_current_region(data, &NodeFactory::default())?
    };
    Ok(DecodedNode { root, region })
}

/// Go `DecodeSourceFile`.
pub fn decode_source_file(data: &[u8]) -> Result<DecodedNode, DecodeError> {
    let decoded = decode_nodes(data)?;
    if decoded.root.kind() != Kind::SourceFile {
        return Err(DecodeError::UnexpectedKind(decoded.root.kind()));
    }
    Ok(decoded)
}

/// Go `DecodeNodes` allocating with `factory` in whatever region the caller has entered (the caller owns the
/// lifetime of the result).
pub fn decode_nodes_in_current_region(data: &[u8], factory: &NodeFactory) -> Result<P<Node>, DecodeError> {
    let mut d = Decoder::new(data, factory.clone())?;
    d.decode()
}

pub(crate) struct Decoder<'a> {
    raw: &'a [u8],
    str_table: u32,
    str_data: u32,
    ext_data: u32,
    node_off: u32,
    node_count: usize,
    pub(crate) factory: NodeFactory,
    nodes: Vec<Option<P<Node>>>,
    lists: Vec<Option<P<NodeList>>>,
    is_list: Vec<bool>,
}

fn read_le32(data: &[u8], offset: usize) -> Option<u32> {
    let b = data.get(offset..offset.checked_add(4)?)?;
    Some(u32::from_le_bytes([b[0], b[1], b[2], b[3]]))
}

/// `Kind` from its wire value. `Kind` is a fieldless enum with implicit, contiguous discriminants `0..Count`
/// (generated by tools/gen-ast/gen-flags.ts, same order as Go's iota), so every value below `Count` is a variant.
pub fn kind_from_u32(value: u32) -> Option<Kind> {
    if value < Kind::Count as u32 {
        // SAFETY: see above; `Kind` is `repr(i16)` and `value` is a valid discriminant.
        Some(unsafe { std::mem::transmute::<i16, Kind>(value as i16) })
    } else {
        None
    }
}

/// Accepts UTF-8 plus WTF-8 encoded lone surrogates (`ED A0..BF xx`), the only non-UTF-8 byte strings the
/// encoders produce (Go strings / JS strings with unpaired surrogates).
pub fn is_wtf8(bytes: &[u8]) -> bool {
    let mut rest = bytes;
    loop {
        match std::str::from_utf8(rest) {
            Ok(_) => return true,
            Err(e) => {
                let i = e.valid_up_to();
                let tail = &rest[i..];
                if tail.len() >= 3 && tail[0] == 0xED && (0xA0..=0xBF).contains(&tail[1]) && (0x80..=0xBF).contains(&tail[2]) {
                    rest = &tail[3..];
                } else {
                    return false;
                }
            }
        }
    }
}

impl<'a> Decoder<'a> {
    fn new(data: &'a [u8], factory: NodeFactory) -> Result<Decoder<'a>, DecodeError> {
        if data.len() < HEADER_SIZE {
            return Err(DecodeError::TooShort(data.len()));
        }
        let version = data[HEADER_OFFSET_METADATA + 3];
        if version != PROTOCOL_VERSION {
            return Err(DecodeError::UnsupportedVersion(version));
        }
        let rd = |o| read_le32(data, o).unwrap();
        let (str_table, str_data, ext_data, node_off) =
            (rd(HEADER_OFFSET_STRING_OFFSETS), rd(HEADER_OFFSET_STRING_DATA), rd(HEADER_OFFSET_EXTENDED_DATA), rd(HEADER_OFFSET_NODES));
        let data_len = data.len() as u64;
        if [str_table, str_data, ext_data, node_off].iter().any(|&o| o as u64 > data_len) {
            return Err(DecodeError::InvalidHeader(format!("offsets exceed data length ({data_len})")));
        }
        if !(str_table <= str_data && str_data <= ext_data && ext_data <= node_off) {
            return Err(DecodeError::InvalidHeader(format!(
                "expected strTable <= strData <= extData <= nodeOff (got {str_table}, {str_data}, {ext_data}, {node_off})"
            )));
        }
        let node_count = (data.len() - node_off as usize) / NODE_SIZE;
        Ok(Decoder { raw: data, str_table, str_data, ext_data, node_off, node_count, factory, nodes: Vec::new(), lists: Vec::new(), is_list: Vec::new() })
    }

    fn node_field(&self, i: usize, field: usize) -> u32 {
        // In bounds: i < node_count and node_count records fit after node_off.
        read_le32(self.raw, self.node_off as usize + i * NODE_SIZE + field).unwrap()
    }

    pub(crate) fn read_ext(&self, offset: u32, field: usize) -> Result<u32, DecodeError> {
        let at = self.ext_data as usize + offset as usize + field;
        if at + 4 > self.node_off as usize {
            return Err(DecodeError::InvalidExtendedData(format!("offset {offset}+{field} out of range")));
        }
        Ok(read_le32(self.raw, at).unwrap())
    }

    pub(crate) fn get_string(&self, idx: u32) -> Result<&'static str, DecodeError> {
        let base = self.str_table as usize + idx as usize * 4;
        if base + 8 > self.str_data as usize {
            return Err(DecodeError::InvalidString(format!("string index {idx} out of range")));
        }
        let (start, end) = (read_le32(self.raw, base).unwrap() as usize, read_le32(self.raw, base + 4).unwrap() as usize);
        let region_len = self.raw.len() - self.str_data as usize;
        if start > end || end > region_len {
            return Err(DecodeError::InvalidString(format!("string {idx} range {start}..{end} out of range")));
        }
        let bytes = &self.raw[self.str_data as usize + start..self.str_data as usize + end];
        if !is_wtf8(bytes) {
            return Err(DecodeError::InvalidString(format!("string {idx} is not UTF-8/WTF-8")));
        }
        // SAFETY: UTF-8 or WTF-8 (the tsrs convention for JS strings with lone surrogates, see
        // tsrs_core::stringutil::encode_js_string_rune); `alloc_str` copies the bytes.
        #[expect(clippy::disallowed_methods, reason = "WTF-8 lone surrogates are not UTF-8, so the checked from_utf8 would reject valid input; is_wtf8 checked the bytes above")]
        let text = unsafe { std::str::from_utf8_unchecked(bytes) };
        Ok(alloc_str(text))
    }

    /// Go `collectChildren`, additionally requiring every sibling link to point forward to a record whose parent
    /// is `i` (so the walk terminates and each record has exactly one parent).
    fn collect_children(&self, i: usize) -> Result<Vec<usize>, DecodeError> {
        let mut out = Vec::new();
        if i + 1 >= self.node_count {
            return Ok(out);
        }
        let first = i + 1;
        if self.node_field(first, NODE_OFFSET_PARENT) as usize != i {
            return Ok(out);
        }
        out.push(first);
        let mut cur = first;
        loop {
            let next = self.node_field(cur, NODE_OFFSET_NEXT) as usize;
            if next == 0 {
                break;
            }
            if next <= cur || next >= self.node_count || self.node_field(next, NODE_OFFSET_PARENT) as usize != i {
                return Err(DecodeError::InvalidTree(format!("bad sibling link {cur} -> {next} under {i}")));
            }
            out.push(next);
            cur = next;
        }
        Ok(out)
    }

    fn decode(&mut self) -> Result<P<Node>, DecodeError> {
        if self.node_count < 2 {
            return Err(DecodeError::NoNodes);
        }
        self.nodes = vec![None; self.node_count];
        self.lists = vec![None; self.node_count];
        self.is_list = vec![false; self.node_count];
        for i in (1..self.node_count).rev() {
            let kind = self.node_field(i, NODE_OFFSET_KIND);
            let pos = self.node_field(i, NODE_OFFSET_POS);
            let end = self.node_field(i, NODE_OFFSET_END);
            let data = self.node_field(i, NODE_OFFSET_DATA);
            let parent = self.node_field(i, NODE_OFFSET_PARENT) as usize;
            if i > 1 && parent >= i {
                return Err(DecodeError::InvalidTree(format!("node {i} has parent {parent}")));
            }
            let child_indices = self.collect_children(i)?;
            let loc = TextRange::new(pos as i32, end as i32);
            if kind == SYNTAX_KIND_NODE_LIST {
                let nodes: Vec<P<Node>> = child_indices.iter().filter_map(|&ci| self.nodes[ci]).collect();
                let list = self.factory.new_node_list(nodes);
                list.loc.set(loc);
                self.lists[i] = Some(list);
                self.is_list[i] = true;
                continue;
            }
            let k = kind_from_u32(kind).ok_or(DecodeError::InvalidKind(kind))?;
            let node = self.create_node(k, data, &child_indices).map_err(|e| match e {
                DecodeError::InvalidTree(s) => DecodeError::InvalidTree(format!("at node {i} ({k:?}): {s}")),
                e => e,
            })?;
            node.set_loc(loc);
            node.set_flags(NodeFlags::from_bits_retain(self.node_field(i, NODE_OFFSET_FLAGS)));
            if k == Kind::SourceFile {
                node.as_source_file().is_declaration_file.set(node.flags().intersects(NodeFlags::Ambient));
            }
            self.nodes[i] = Some(node);
        }
        self.nodes[1].ok_or_else(|| DecodeError::InvalidTree("root is a NodeList".into()))
    }

    fn create_node(&mut self, kind: Kind, data: u32, child_indices: &[usize]) -> Result<P<Node>, DecodeError> {
        let common_data = (data >> 24) & 0x3f;
        match data & NODE_DATA_TYPE_MASK {
            NODE_DATA_TYPE_STRING => self.create_string_node(kind, data, common_data),
            NODE_DATA_TYPE_EXTENDED_DATA => self.create_extended_node(kind, data, child_indices, common_data),
            NODE_DATA_TYPE_CHILDREN => self.create_children_node(kind, data, child_indices, common_data),
            _ => Err(DecodeError::InvalidTree(format!("reserved node data type for {kind:?}"))),
        }
    }

    // ── child accessors used by the generated factories ──

    pub(crate) fn node_at_opt(&self, ci: usize) -> Result<Option<P<Node>>, DecodeError> {
        Ok(if ci == 0 { None } else { self.nodes[ci] })
    }

    pub(crate) fn node_at(&self, ci: usize) -> Result<P<Node>, DecodeError> {
        self.nodes[ci].ok_or(DecodeError::MissingChild)
    }

    pub(crate) fn list_at(&self, ci: usize) -> Result<Option<P<NodeList>>, DecodeError> {
        Ok(if ci == 0 { None } else { self.lists[ci] })
    }

    pub(crate) fn modifier_list_at(&self, ci: usize) -> Result<Option<P<ModifierList>>, DecodeError> {
        let Some(list) = self.list_at(ci)? else {
            return Ok(None);
        };
        let mods = self.factory.new_modifier_list_from_slice(list.nodes());
        mods.list.loc.set(list.loc());
        Ok(Some(mods))
    }

    pub(crate) fn single_child(&self, child_indices: &[usize]) -> Result<Option<P<Node>>, DecodeError> {
        Ok(child_indices.first().and_then(|&ci| self.nodes[ci]))
    }

    pub(crate) fn single_node_list_child(&self, child_indices: &[usize]) -> Result<Option<P<NodeList>>, DecodeError> {
        Ok(child_indices.first().and_then(|&ci| self.lists[ci]))
    }

    // ── hand-written extended data (Go decodeExtendedData_*) ──

    pub(crate) fn decode_extended_data_source_file(&mut self, data: u32, child_indices: &[usize], _: u32) -> Result<P<Node>, DecodeError> {
        let off = data & NODE_DATA_STRING_INDEX_MASK;
        let text = self.get_string(self.read_ext(off, 0)?)?;
        let file_name = self.get_string(self.read_ext(off, 4)?)?;
        let path = self.get_string(self.read_ext(off, 8)?)?;
        let language_variant = match self.read_ext(off, 12)? {
            0 => LanguageVariant::Standard,
            1 => LanguageVariant::JSX,
            v => return Err(DecodeError::InvalidExtendedData(format!("languageVariant {v}"))),
        };
        let script_kind = match self.read_ext(off, 16)? {
            0 => ScriptKind::Unknown,
            1 => ScriptKind::JS,
            2 => ScriptKind::JSX,
            3 => ScriptKind::TS,
            4 => ScriptKind::TSX,
            6 => ScriptKind::JSON,
            v => return Err(DecodeError::InvalidExtendedData(format!("scriptKind {v}"))),
        };
        if tspath::get_encoded_root_length(file_name) == 0 || file_name != tspath::normalize_path(file_name) {
            return Err(DecodeError::InvalidSourceFileName(file_name.to_string()));
        }
        let parse_opts = read_le32(self.raw, HEADER_OFFSET_PARSE_OPTIONS).unwrap();
        let opts = SourceFileParseOptions {
            file_name: file_name.to_string(),
            path: tspath::Path(path.into()),
            external_module_indicator_options: ExternalModuleIndicatorOptions { jsx: parse_opts & 1 != 0, force: parse_opts & 2 != 0 },
        };
        let mut stmts = None;
        let mut end_of_file = None;
        for &ci in child_indices {
            if self.is_list[ci] {
                stmts = self.lists[ci];
            } else if let Some(n) = self.nodes[ci].filter(|n| n.kind() == Kind::EndOfFile) {
                end_of_file = Some(n);
            }
        }
        // Go passes a nil statements list when there is none; the Rust AST requires one.
        let stmts = stmts.unwrap_or_else(|| self.factory.new_node_list(Vec::new()));
        let end_of_file = end_of_file.unwrap_or_else(|| self.factory.new_token(Kind::EndOfFile));
        let node = self.factory.new_source_file(opts, text, stmts, end_of_file);
        let sf = node.as_source_file();
        sf.language_variant.set(language_variant);
        sf.script_kind.set(script_kind);
        Ok(node)
    }

    fn ext_text_raw_flags(&self, data: u32) -> Result<(&'static str, &'static str, TokenFlags), DecodeError> {
        let off = data & NODE_DATA_STRING_INDEX_MASK;
        Ok((self.get_string(self.read_ext(off, 0)?)?, self.get_string(self.read_ext(off, 4)?)?, TokenFlags::from_bits_retain(self.read_ext(off, 8)? as i32)))
    }

    fn ext_text_flags(&self, data: u32) -> Result<(&'static str, TokenFlags), DecodeError> {
        let off = data & NODE_DATA_STRING_INDEX_MASK;
        Ok((self.get_string(self.read_ext(off, 0)?)?, TokenFlags::from_bits_retain(self.read_ext(off, 4)? as i32)))
    }

    pub(crate) fn decode_extended_data_template_head(&mut self, data: u32, _: &[usize], _: u32) -> Result<P<Node>, DecodeError> {
        let (t, r, f) = self.ext_text_raw_flags(data)?;
        Ok(self.factory.new_template_head(t, r, f))
    }

    pub(crate) fn decode_extended_data_template_middle(&mut self, data: u32, _: &[usize], _: u32) -> Result<P<Node>, DecodeError> {
        let (t, r, f) = self.ext_text_raw_flags(data)?;
        Ok(self.factory.new_template_middle(t, r, f))
    }

    pub(crate) fn decode_extended_data_template_tail(&mut self, data: u32, _: &[usize], _: u32) -> Result<P<Node>, DecodeError> {
        let (t, r, f) = self.ext_text_raw_flags(data)?;
        Ok(self.factory.new_template_tail(t, r, f))
    }

    pub(crate) fn decode_extended_data_string_literal(&mut self, data: u32, _: &[usize], _: u32) -> Result<P<Node>, DecodeError> {
        let (t, f) = self.ext_text_flags(data)?;
        Ok(self.factory.new_string_literal(t, f))
    }

    pub(crate) fn decode_extended_data_numeric_literal(&mut self, data: u32, _: &[usize], _: u32) -> Result<P<Node>, DecodeError> {
        let (t, f) = self.ext_text_flags(data)?;
        Ok(self.factory.new_numeric_literal(t, f))
    }

    pub(crate) fn decode_extended_data_big_int_literal(&mut self, data: u32, _: &[usize], _: u32) -> Result<P<Node>, DecodeError> {
        let (t, f) = self.ext_text_flags(data)?;
        Ok(self.factory.new_big_int_literal(t, f))
    }

    pub(crate) fn decode_extended_data_regular_expression_literal(&mut self, data: u32, _: &[usize], _: u32) -> Result<P<Node>, DecodeError> {
        let (t, f) = self.ext_text_flags(data)?;
        Ok(self.factory.new_regular_expression_literal(t, f))
    }

    pub(crate) fn decode_extended_data_no_substitution_template_literal(&mut self, data: u32, _: &[usize], _: u32) -> Result<P<Node>, DecodeError> {
        let (t, f) = self.ext_text_flags(data)?;
        Ok(self.factory.new_no_substitution_template_literal(t, f))
    }
}

/// Go `childIterator`.
pub(crate) struct ChildIter<'a> {
    indices: &'a [usize],
    pos: usize,
}

impl<'a> ChildIter<'a> {
    pub(crate) fn new(indices: &'a [usize]) -> ChildIter<'a> {
        ChildIter { indices, pos: 0 }
    }

    pub(crate) fn next_if(&mut self, mask: u8, bit: u8) -> usize {
        if mask & (1 << bit) == 0 {
            return 0;
        }
        let Some(&ci) = self.indices.get(self.pos) else {
            return 0;
        };
        self.pos += 1;
        ci
    }
}

/// Converts a decoded child into a factory parameter: required children must be present (Go would store nil).
pub(crate) trait FromChild<T>: Sized {
    fn from_child(v: Option<T>) -> Result<Self, DecodeError>;
}
impl<T> FromChild<T> for Option<T> {
    fn from_child(v: Option<T>) -> Result<Self, DecodeError> {
        Ok(v)
    }
}
impl FromChild<P<Node>> for P<Node> {
    fn from_child(v: Option<P<Node>>) -> Result<Self, DecodeError> {
        v.ok_or(DecodeError::MissingChild)
    }
}
impl FromChild<P<NodeList>> for P<NodeList> {
    fn from_child(v: Option<P<NodeList>>) -> Result<Self, DecodeError> {
        v.ok_or(DecodeError::MissingChild)
    }
}
pub(crate) fn from_node<R: FromChild<P<Node>>>(v: Option<P<Node>>) -> Result<R, DecodeError> {
    R::from_child(v)
}
pub(crate) fn from_list<R: FromChild<P<NodeList>>>(v: Option<P<NodeList>>) -> Result<R, DecodeError> {
    R::from_child(v)
}

/// The Go zero value of a factory parameter the binary format does not carry (`goDefaultValue`); a required
/// child has none, so it is a decode error.
pub(crate) trait Absent: Sized {
    fn absent() -> Result<Self, DecodeError>;
}
macro_rules! absent_default {
    ($($t:ty),*) => {$(impl Absent for $t { fn absent() -> Result<Self, DecodeError> { Ok(<$t>::default()) } })*};
}
absent_default!(bool, Kind, TokenFlags, NodeFlags, &'static str);
impl<T> Absent for Option<T> {
    fn absent() -> Result<Self, DecodeError> {
        Ok(None)
    }
}
impl<T> Absent for &'static [T] {
    fn absent() -> Result<Self, DecodeError> {
        Ok(&[])
    }
}
impl Absent for P<Node> {
    fn absent() -> Result<Self, DecodeError> {
        Err(DecodeError::MissingChild)
    }
}
impl Absent for P<NodeList> {
    fn absent() -> Result<Self, DecodeError> {
        Err(DecodeError::MissingChild)
    }
}
pub(crate) fn absent<T: Absent>() -> Result<T, DecodeError> {
    T::absent()
}

/// Go `decodeNodeCommonData_SyntheticExpression` panics: the node is checker-internal and never decoded.
pub(crate) fn decode_node_common_data_synthetic_expression(_: u32) -> Result<(&'static dyn std::any::Any, bool), DecodeError> {
    Err(DecodeError::Unsupported(Kind::SyntheticExpression))
}
